### ISSUE TITLE
Does NEST need to link against libneurosim or libpyneurosim?

### ISSUE THREAD

**Issue by sanjayankur31** [nest/nest-simulator#1063]
Hello,

At buildtime, does NEST need to link against libneurosim or libpyneurosim or both? Currently, it expects them both in the same directory, `/usr/lib{,64}`, but at runtime, it seems to require libpyneurosim in `PYTHONPATH` which is not `/usr/lib{,64}` (it should be `/usr/lib{,64}/pythonX.Y/site-packages`). 

I had opened this PR against libneurosim where I'd moved libpyneurosim to the correct python path, but now I'm not sure if that's correct anymore: https://github.com/INCF/libneurosim/issues/12

**Comment by heplesser** [comment]
@jougs Could you answer this one?

**Comment by sanjayankur31** [comment]
@jougs would you have any comments here please?

**Comment by jougs** [comment]
@mdjurfeldt: can you  please comment on this one?

**Comment by mdjurfeldt** [comment]
I've answered this in the libneurosim issue, but copy the text here:

"libpyneurosim is not a Python extension. It is rather support for using connection generators written in Python from C++ code (i.e. the reverse of what Python extensions do). Therefore, libpyneurosim should be installed in ordinary library directories like /usr/lib{,64}. NEST needs to link against both libpyneurosim and libneurosim and these libraries need to be found at link time by the NEST binary.

Also, this means that the comment in the NEST example is wrong. These libraries should not be on PYTHONPATH but on LD_LIBRARY_PATH (if needed).

I've commited an explanation in the libneurosim README.md."

**Comment by mdjurfeldt** [comment]
The NEST example which the citation refers to is https://github.com/nest/nest-simulator/blob/master/pynest/examples/csa_example.py#L55 .

**Comment by pedroernesto** [comment]
When building NEST inside a Miniconda2 Python environment, just at the end I get this error message when linking against the `libneurosim` package installed at /usr/local/. The same happens if `libneurosim` is installed inside the same environment (and found by NEST at such location). 
Note: The Miniconda environment is being setup and NEST configured according to this issue:
https://github.com/nest/nest-simulator/issues/1091

Might this problem be related with a more general one like this?:
https://stackoverflow.com/questions/8823267/linking-against-older-symbol-version-in-a-so-file?

> [ 96%] Built target nest_lib
Scanning dependencies of target nest
[ 97%] Building CXX object nest/CMakeFiles/nest.dir/main.cpp.o
[ 97%] Building CXX object nest/CMakeFiles/nest.dir/neststartup.cpp.o
[ 97%] Building CXX object nest/CMakeFiles/nest.dir/sli_neuron.cpp.o
[ 98%] Linking CXX executable nest
/home/pedroernesto/miniconda2/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /usr/local/lib/libneurosim.so: undefined reference to `memcpy@GLIBC_2.14'
collect2: error: ld returned 1 exit status

**Comment by sanjayankur31** [comment]
This is probably worth a new issue at libneurosim @pedroernesto . I've not seen it on a standard Fedora install that we're building NEST for so it's something to do with your environment from the looks of it:

- https://koji.fedoraproject.org/koji/buildinfo?buildID=1211488
- https://koji.fedoraproject.org/koji/packageinfo?packageID=27709 
- https://src.fedoraproject.org/rpms/nest/blob/master/f/nest.spec
- https://src.fedoraproject.org/rpms/libneurosim/blob/master/f/libneurosim.spec

**Comment by pedroernesto** [comment]
Yes, It seems so. When building NEST outside the Miniconda environment:

`conda deactivate`
`cmake -DCMAKE_INSTALL_PREFIX=$HOME  -Dwith-libneurosim=ON  -Dwith-mpi=/usr/include/mpi -Dwith-gsl=/usr/include/gsl -Dwith-python=2`

only some warnings show up, but NEST is built:

> [ 96%] Built target nest_lib
Scanning dependencies of target nest
[ 97%] Building CXX object nest/CMakeFiles/nest.dir/main.cpp.o
[ 97%] Building CXX object nest/CMakeFiles/nest.dir/neststartup.cpp.o
[ 97%] Building CXX object nest/CMakeFiles/nest.dir/sli_neuron.cpp.o
[ 98%] Linking CXX executable nest
[ 98%] Built target nest
[ 98%] Compiling Cython CXX source for pynestkernel...
warning: pynestkernel.pyx:493:10: Unreachable code
warning: pynestkernel.pyx:493:10: Unreachable code
Scanning dependencies of target pynestkernel
[100%] Building CXX object pynest/CMakeFiles/pynestkernel.dir/pynestkernel.cxx.o
....
[100%] Linking CXX shared module pynestkernel.so
[100%] Built target pynestkernel
