### ISSUE TITLE
Inconsistent behavior for fixed number of connections if set to 0

### ISSUE THREAD

**Issue by jhnnsnk** [nest/nest-simulator#1073]
Plain NEST and Topology behave differently for a fixed indegree (or outdegree) if the number of connections is set to 0:
Plain NEST does not connect as expected, but Topology establishes `all_to_all` connections without warning.
I suggest that also Topology should not connect in this case and I would prepare a pull request if that's fine with you.

Here a reproducer with the latest NEST master (version ab69db50):
```
import numpy as np
import nest
import nest.topology as tp

nnrns = 3
indegree = 0

nest.ResetKernel()
nrns = nest.Create('iaf_psc_exp', nnrns)
nest.Connect(nrns, nrns, {'rule': 'fixed_indegree', 'indegree': indegree})
conns_plain_nest = nest.GetConnections()

nest.ResetKernel()
nrns = tp.CreateLayer({'positions': list((np.random.rand(2*nnrns) - 0.5).reshape(-1, 2)), 'elements': 'iaf_psc_exp'})
tp.ConnectLayers(nrns, nrns, {'connection_type': 'convergent', 'number_of_connections': indegree})
conns_topo = nest.GetConnections()

print('Connections (plain NEST):\n', conns_plain_nest)
print('Connections (Topology):\n', conns_topo)
```
Output:
```
Connections (plain NEST):
 ()
Connections (Topology):
 (array('l', [2, 2, 0, 0, 0]), array('l', [2, 3, 0, 0, 1]), array('l', [2, 4, 0, 0, 2]), array('l', [3, 2, 0, 0, 3]), array('l', [3, 3, 0, 0, 4]), array('l', [3, 4, 0, 0, 5]), array('l', [4, 2, 0, 0, 6]), array('l', [4, 3, 0, 0, 7]), array('l', [4, 4, 0, 0, 8]))
```

**Comment by heplesser** [comment]
@jhnnsnk Thanks for detecting this! The behavior of topology is clearly wrong, it should not create any connections in this case. One could consider `indegree==0` an error, but I think it is easier (and fully consistent) to simply not create connections in this case. The implementation should make sure that nothing is done at all instead of iterating over all targets and doing nothing for each target.
