### ISSUE TITLE
Wrong handling of refractoriness with GSL

### ISSUE THREAD

**Issue by Silmathoron** [nest/nest-simulator#1097]
In all GSL models except the aEIF, the refractoriness is not handled correctly: the GSL ``while`` loop should contain the refractoriness test.

See for instance the [``iaf_cond_alpha``](https://github.com/nest/nest-simulator/blob/master/models/iaf_cond_alpha.cpp#L100) for an example of the problem, and the [``aeif_cond_alpha``](https://github.com/nest/nest-simulator/blob/master/models/aeif_cond_alpha.cpp#L524) for the correct implementation (leaving the spikes out).

This is **always** a problem for conductance-based models (exp or alpha) because the ``V_m`` parameter is used to compute the synaptic current. Thus, every time the while loop is executed in more than one iteration, all synaptic currents except the first one are wrong, making the integration scheme incorrect (even compared to a simple Euler implementation).

For alpha-shaped synapses, this is even worse because the potential also enters the ODE for the conductance.

Incorrect models include at least ``iaf_cond_*``, ``gif_cond_*``, ``iaf_chxk_2008``

**EDIT** from @heplesser's comment, all GSL model need to be corrected, with the clamp included into the ODE function.

**Comment by heplesser** [comment]
@Silmathoron Thanks for discovering this. Actually, fixing this inside the `while` loop will not fully address the problem, since the call to `gsl_odeiv_evolve_apply()` will cause multiple evaluations of the right-hand side. One therefore needs to clamp inside the function evaluating the rhs, as in [ht_neuron](https://github.com/nest/nest-simulator/blob/84c9435810256522ab1c2cc642ff9a09db6d6637/models/ht_neuron.cpp#L73).

@clinssen Could you take note of this in relation to NESTML?

**Comment by Silmathoron** [comment]
Ow, didn't know that, thanks for the precision @heplesser!
Well, that makes things easier: all GSL models need to be corrected then ^^

**Comment by clinssen** [comment]
Note also that `nest/tests/test_refractory.py` might have to be updated, as it does not seem to catch the wrong behaviour.

**Comment by clinssen** [comment]
I am not sure this should be qualified as a bug. Although clamping V_m inside the GSL stepping function is certainly the cleanest approach (and we should do that in any case), does the continued integration of V_m actually cause externally observable behaviour that is faulty?

The dynamics of synaptic conductances is unaffected. This conductance is used to calculate the synaptic transmembrane current, which gets integrated into V_m. The transmembrane current is wrong due to V_m not being clamped in the refractory interval, but V_m gets reset anyway as we are leaving the refractory state. So perhaps this is actually a minor "cleanup" intervention.

@Silmathoron: what are your thoughts?

**Comment by Silmathoron** [comment]
@clinssen as long as this does not conform to the mathematical equation it is supposed to implement, I would say that, yes, this is a bug, as small as the actual discrepancy may be...

But I see your point: if the ``aeif_*`` models are the only ones where the dynamics of V in the rhs function affects another variable, and if their implementations are correct, then there should actually be no effect of this faulty implementation.

**Comment by heplesser** [comment]
@clinssen and I checked pertaining models. We found that in those models, V_m enters only into the derivative of V_m, so that clamping inside the rhs function is not strictly necessary. We therefore change from Bug to Maintenance and remove this from the NEST 3 milestone. For consistency, proper V-clamping in the rhs function should still be implemented.
