### ISSUE TITLE
Error on set_local_device_id

### ISSUE THREAD

**Issue by L24358** [nest/nest-simulator#1109]
Hi,
I've installed NEST and COREM in Ubuntu 18.04 with python 2.7. No errors occurred while installing. I can successively run corem by typing `./corem Retina_scripts/example_1.py` in the command line. And I can import nest using "import nest" in python2.7. However when trying to run sample code NEST_scripts/example1.py, it shows the error:
![screenshot from 2019-01-20 22-07-21](https://user-images.githubusercontent.com/30598859/51440228-e2463180-1cff-11e9-970d-bceaf950cea6.png)
This error occurs at line 34: 
g=nest.Create('corem',1,{'port':float(i),'file':"Retina_scripts/example_1.py"})

**Comment by stinebuu** [comment]
@L24358 Your problem seems to be that COREM has not updated their external module in quite some time, so it is no longer compatible with the newest version of NEST. NEST 2.16 made some changes to the way models are defined, and this also impacts models in external modules. You can see [here](https://nest.github.io/nest-simulator/model_conversion_5g) for a guide on how to update the model in the module. The model you are using seems to be a device, so you need to use a `DeviceNode`.

**Comment by heplesser** [comment]
Closing this issue since it is an issue in an external module.
