### ISSUE TITLE
Phase 5 Tests all fail with ' Open MPI does not support recursive calls of mpirun'

### ISSUE THREAD

**Issue by EricThomson** [nest/nest-simulator#1130]
I'm building `nest-stimulator` directly from a fork of the repo. things are largely working ok. I ran cmake with:

> cmake -DCMAKE_INSTALL_PREFIX:PATH=/home/eric/nest_dev /home/eric/nest_dev/nest-simulator -Dwith-python=3 -Dwith-mpi=ON

While `make` and `make install` ran ok,  phase 5 of the tests (for mpi) all failed with something like:

> **********************************************************
> Open MPI does not support recursive calls of mpirun
> **********************************************************
> Feb 22 10:01:50 unittest::assert_or_die [Fatal]: 
>     Assertion failed: unittest::distributed_collect_assert_or_die: collected 
>     results.
> Feb 22 10:01:50 unittest::assert_or_die [Fatal]: 
>     Exiting with code 1.
> Failed: missed SLI assertion
> Running  /opt/nest/bin/sli /opt/nest/share/doc/nest/topology/mpitests/topo_mpi_test_divergent.sli
> SLI v2.16.0 (C) 2004 The NEST Initiative
> N_MPI: 1

I've attached TEST-core.phase_5.xml (note changed extension to `txt` otherwise it wouldn't let me attach). [TEST-core.phase_5.txt](https://github.com/nest/nest-simulator/files/2894640/TEST-core.phase_5.txt)

I am in Ubuntu 16/Python 3.7 (Anaconda) and have Open MPI 1.10.2.

**Comment by EricThomson** [comment]
Maybe I am wrong to expect these tests to pass on my local machine (i.e., naively, I thought it would test it by spawning multiple processes on my single machine and calling `mpirun ...` on these processes). Maybe I needed to do more to set it up?  If so I will close this issue.

At any rate, it doesn't really matter I'm just using threads currently and it works great, so in practice it will be a few months before I even need mpi.

**Comment by jougs** [comment]
@EricThomson: I was already afraid that I'm the only one capable of getting this error. Thank you so much for also getting (and reporting) it ;-)

May I ask about the exact MPI implementation you are using, i.e. can you please send the output of `mpirun --version`?

I am working on a solution for this (and other issues with our current test setup) since quite some time in PR #1071. Unfortunately the work takes much longer than expected. If you like, you can check out the branch that PR is based on and report your experience back.

**Comment by jougs** [comment]
The problem here is really that the PyNEST testsuite is a submodule of the `nest` Python module. This leads to a situation where importing any test always imports `nest` and thus initializes MPI. If the test in question is now just a *meta-test* importing and running other tests, this might lead to recursive MPI initializations, that don't go well with all implementations.

The only solution to this is to move the PyNEST tests out of the `nest` module and create a proper meta-test for MPI tests, which itself does not initialize MPI, but uses individual subprocesses for running the tests.

**Comment by heplesser** [comment]
@jougs Thank you for the analysis! The distinction between *meta-test* (test runner) and test proper is very useful. We should think about intelligent and robust ways of doing this. Our current setup, also of the SLI-based MPI-tests, is certainly not ideal. I have no objection to moving the PyNEST tests out of the `nest` module.

**Comment by jougs** [comment]
@heplesser: I already have a prototype ready for this and will assemble a PR, once I'm done with #1717.
