### ISSUE TITLE
Segmentation fault in inhomogeneous poisson generator

### ISSUE THREAD

**Issue by babsey** [nest/nest-simulator#1140]
We occur this issue when we create inhomogeneous poisson generator with parameters. However, it works when we create this stimulator without parameters and then set parameter values.

To view the issue, we implemented two examples. This will crash:
```
nest.Create('inhomogeneous_poisson_generator', params={
  'rate_times': [10.0, 110.0, 210.0], 
  'rate_values': [400.0, 1000.0, 200.0]
})
```

Interestingly, this code works:
```
ipg = nest.Create('inhomogeneous_poisson_generator')
nest.SetStatus(ipg, {
    'rate_times': [10.0, 110.0, 210.0],
    'rate_values': [400.0, 1000.0, 200.0]
})
```

We used ipython (6.2.1 - 6.4.0) for Python 3.6.5 with NEST 2.16.0.

I created the issue for these reasons: 
- We want to ask if anyone also occur the same problem.
- We were desperate to find a suitable documentation as well as an example about it.

**Comment by EricThomson** [comment]
I see the same thing (Nest 2.16, Python 3.7 -- I ran it from the command line and got a segfault).

**Comment by hakonsbm** [comment]
When a node is created with parameters, the default parameters are temporarily changed. It is when resetting the default parameters to the old value things go wrong, because the inhomogeneous poisson generator doesn't handle setting empty `rate_times` and `rate_values` vectors (specifically it goes wrong when it tries dereferencing the first value in the empty vector, leading to the segfault).

I'll create a PR fixing the issue.
