### ISSUE TITLE
Do you have some case run nest on ARM-FPGA cluster？

### ISSUE THREAD

**Issue by clancylea** [nest/nest-simulator#1162]
Hello，i want to study nest using ARM-FPGA（ZYNQ） cluster.Recently,i have run on ARM cluster.
But,i found the process with FPGA have some difficulty.
Do you have some case run nest at FPGA cluster.

Others questions:
First,can i use my arm-linux cross-compile to compile nest?
Second,could i run nest without SLI？
Thanks!

**Comment by gtrensch** [comment]
@clancylea NEST can be run on ARM 32bit. This has already been demonstrated with a Raspberry Pi cluster running with MPICH, and also with a Zynq 70xx SoC. Using the PL for acceleration is a subject of research. Since NEST relies on OpenMPI a Zynq-FPGA cluster would require a  communication fabric in the PL and a software stack/layer being able to abstract the implementation details away from NEST. This is not trivial. 
Concerning your questions: 
- No, there isn't a Zynq cluster implementation yet, but we would be very interested if there is one. 
- Yes, you can use the arm-non-eabi-xxx toolchain for cross-compiling. If you compile for Zynq this will be installed with the Xilinx Vivado SDK.  
- No, NEST cannot run without SLI.

**Comment by gtrensch** [comment]
Can we close this?

**Comment by clancylea** [comment]
> Can we close this?

Yes，Thank you！
