### ISSUE TITLE
Protected members in Archiving_Node

### ISSUE THREAD

**Issue by terhorstd** [nest/nest-simulator#1173]
The implementation of the new  `Clopath_Archiving_Node` (introduced in #1095) throws up several questions and problems.

* `private` attributes of `Archiving_Node` became `protected` ([nestkernel/archiving_node.h:200](https://github.com/nest/nest-simulator/pull/1095/files#diff-592a988d91a508d329ba879d523e8d68L200)), which encourages intricate implementation dependencies (it is a "[code smell](https://en.wikipedia.org/wiki/Code_smell)")
* The fact that the new archiver is *derived* from the old one (instead of it's functionality being *integrated* into it) disallows "normal" neurons to use it. This means that the Clopath synapse can only be used by a small subset of neurons that are actually derived from the new archiver.
* In the context of [NESTML](https://github.com/nest/nestml), the approach taken for the Clopath synapse does not work. If the synapse C++ code was to be generated from a high-level description, we cannot derive an archiver, but require a more general archiver infrastructure and a generic way of specifying which neuron attributes need archiving.

This issue is meant as a place to collect issues related to the new archiver.

 @clinssen, @janhahne, @jstapmanns, @ddahmen: feel free to contribute your thoughts and ideas.

**Comment by janhahne** [comment]
Here are some thoughts on this: 

> The fact that the new archiver is derived from the old one (instead of it's functionality being integrated into it) disallows "normal" neurons to use it. This means that the Clopath synapse can only be used by a small subset of neurons that are actually derived from the new archiver.

Without NESTML in the picture this structure is actually ideal: "Normal neurons" cannot use the Clopath synapse anyway, as they do not provide the necessary low-pass filtered versions of the membrane potentials 
```
  f[ S::U_BAR_PLUS ] = ( -u_bar_plus + V ) / node.P_.tau_plus;

  f[ S::U_BAR_MINUS ] = ( -u_bar_minus + V ) / node.P_.tau_minus;

  f[ S::U_BAR_BAR ] = ( -u_bar_bar + u_bar_minus ) / node.P_.tau_bar_bar;
```
that are part of the GSL ODE-systems of the supported neurons and are needed for the calculation of the Clopath synapse. For that reason "normal" neuron models also do not call 
```
    write_clopath_history( Time::step( origin.get_steps() + lag + 1 ),
      S_.y_[ State_::V_M ],
      S_.y_[ State_::U_BAR_PLUS ],
      S_.y_[ State_::U_BAR_MINUS ],
      S_.y_[ State_::U_BAR_BAR ] );
```
Unless we move this integration somehow from the neuron model to the synapse it is pointless to use other neuron models with the Clopath synapse.

Another point here is that many Clopath synapse parameters are actually saved in the `Clopath_Archiving_Node`. Having those parameters in every neuron model without having any influence on the computations seems quite strange and confusing, which was another reason for using a derived class here.

> In the context of NESTML, the approach taken for the Clopath synapse does not work. If the synapse C++ code was to be generated from a high-level description, we cannot derive an archiver, but require a more general archiver infrastructure and a generic way of specifying which neuron attributes need archiving.

In the context of NESTML I completely agree that the current structure is difficult / needs to be changed, at least if one actually wants to model the synapse with NESTML. Until now my impression was that the Clopath synapse and the `Clopath_Archiving_Node` should stay as "fixed" parts of the NEST code base and code generation would allow to add support for the Clopath synapse to a newly specified neuron model. E.g. by providing a simple flag asking if the Clopath synapse should be supported (and in this case adding the differential equations and the  write_clopath_history() to the generated neuron model code and choosing the type as Clopath_Archiving_Node instead of 'Archiving_Node).

If it is actually the plan to model the Clopath synapse itself in NESTML then the situation is quite different of course. However, how do make sure that the neuron models you want to use it with provides the necessary low-pass filtered membrane potential?

**Comment by clinssen** [comment]
Thanks to NESTML being based on a code generation philosophy, we are indeed quite flexible in our targeting. However, one of the arguments for changing the way NEST does things here, is that we wanted to avoid having to "co-generate" (i.e. simultaneously process) the neuron and its connected synapses. This means that shuffling the location of the parameters around (from synapse to neuron or vice versa), or deciding whether "Clopath archiving" is required for a particular node, would have to be taken care of on the NEST side.

**Comment by janhahne** [comment]
@clinssen I completely understand the decision that you want to avoid "co-generation" of neurons and synapses in NESTML. However, I am not sure that I fully understand the consequences regarding the Clopath synapse: After all the Clopath synapse needs the low-pass filtered versions of the membrane potentials from the neuron model, which means that there is a clear dependency between the neuron that needs to provide this information and synapse that needs to receive this information. This makes me wonder how a NESTML version of the Clopath synapse could look like?

**Comment by clinssen** [comment]
It has been decided that NESTML will generate code that completely subsumes the ``Archiving_Node`` and ``Clopath_Archiving_Node`` classes. These two classes will then go away. See discussion in https://github.com/nest/nest-simulator/pull/1820. @terhorstd: are you OK closing this issue?

**Comment by clinssen** [comment]
In the NEST Hackathon of November 2020, it was agreed to close this issue based on the reasons stated above.

See also #1820 for a related PR and discussion.
