### ISSUE TITLE
The -Wall option is obsolete

### ISSUE THREAD

**Issue by ikitayama** [nest/nest-simulator#1184]
There's a compiler which doesn't get along with the -Wall option out there. Platform specific file might be a workaround, but if that's overkill, what should we do?

**Comment by terhorstd** [comment]
Could you please be more specific which compiler can not handle the `-Wall` option? I suppose it is not that *all* compilers consider `-Wall` as obsolete, as your title seems to suggest...

If it is a very platform specific compiler, my first suggestion would be to either fix the compiler or write a wrapper (outside of NEST) that drops `-Wall`. Or is there a reason why this explicitly needs to be handled inside NEST installation scripts?

**Comment by ikitayama** [comment]
If g++ didn’t understand the option then what would the wrapper look like?

**Comment by ikitayama** [comment]
@terhorstd in the meantime, I just set -Dwith-warning=OFF at the CMake config time.

**Comment by terhorstd** [comment]
The g++ compiler understands the -Wall option. If you have a compiler that doesn't, the compiler could be fixed or wrapped. I think for such a general flag that breaks only with a very specific compiler, we would not want to explicitly branch in the NEST code-base.

Since a work-around exists, I am closing this issue.

**Comment by ikitayama** [comment]
+1
