### ISSUE TITLE
Use of synapse types in NEST + PyNN Issue #377

### ISSUE THREAD

**Issue by mschmidt87** [nest/nest-simulator#121]
This issue is related to the pyNN issue 377 "PyNN exhausts NEST 2.6/2.8 synapse model storage" (https://github.com/NeuralEnsemble/PyNN/issues/377).

1. In pyNN, whenever a pyNN.projection is created to establish connections, a new synapse type in NEST is created, which is a misuse of NEST's synapse type. A synapse type in NEST specifies the dynamical model of synapse (e.g. static, STDP etc.) and not the projection/connection it belongs to. It also does not specify whether the synapse is excitatory or inhibitory, because this is independently decided by the synaptic weights. 
This causes pyNN to exhaust NEST's maximal amount of synapse types (256).

2. Some of the NEST examples create new synapse types to distinguish between excitatory and inhibitory synapses, which also a misuse of the synapse type concept. We should discourage NEST users to use NEST synapse types for such things like the differentiation between exc. and inh. synapses, if the only difference between them are the positive/negative synaptic weights.

Examples are the brunel network scripts.

**Comment by jschuecker** [comment]
Solution and implementation plan:
We will use a decorator around a synapse type, that optionally gives every synapse a projection id as an integer. This projection id can be optionally passed to the Connect function, so that this feature will be optional in pyNEST while in PyNN it will be set automatically.
This is independent of pyNN and would cost one integer for each synapse but adds the idea of projections in NEST, if requested by the user (of course the user has to pay for this feature with memory costs).
This could be implemented using a template and will be done by @tammoippen.
PyNN then can identify a projection by filtering synapses for this projection id, which will be implemented by @mschmidt87 and by me.

**Comment by heplesser** [comment]
Closing #121 by #158
