### ISSUE TITLE
Connection descriptors are invalidated after adding new connections, but still accepted by GetStatus

### ISSUE THREAD

**Issue by aserenko** [nest/nest-simulator#1224]
1. When a new connection is created, the connection descriptors (`source-gid, target-gid, target-thread, synapse-id, port`) are rearranged, and ids of the existing connections may change. In this case descriptors returned by GetConnections() before become incorrect.

2. Such incorrect descriptors are still accepted by GetStatus(), because the latter seems to look only at the synapse id, ignoring the fact that the other components of the descriptor are inconsistent. This may lead to quite confusing output.

A minimal reproducing example:
```
other_neurons_ids = nest.Create('parrot_neuron', 1)  # gets id 1
neurons_ids = nest.Create('parrot_neuron', 1)  # gets id 2

# note that we first use the neuron with higher id, this is the cause!
nest.Connect(
	pre=neurons_ids,
	post=neurons_ids,
	conn_spec='one_to_one',
	syn_spec={'weight': 0}
)

connections_ids = nest.GetConnections()
print(
	connections_ids,
	nest.GetStatus(connections_ids, 'weight')
)
```
outputs:
```
(array('l', [2, 2, 0, 0, 0]),)
{'weight': 0.0, 'source': 2, 'target': 2, ...}
```

Now we create one more connection.
```
nest.Connect(
	pre=other_neurons_ids,
	post=other_neurons_ids,
	conn_spec='one_to_one',
	syn_spec={'weight': 2}
)
print(nest.GetConnections())
```
Now the descriptors are all different:
`(array('l', [1, 1, 0, 0, 0]), array('l', [2, 2, 0, 0, 1]))`
Trying to query the synapse by a descriptor stored in advance
```
print(nest.GetStatus(connections_ids))
```
outputs the nonsensical
```
{'weight': 2.0, 'source': 2, 'target': 1, ...}
```
where the 'weight' and 'target' properties are the ones of the synapse which now has id 0, and 'source' has remained intact from the query.

If this is not a bug, I would have suggested the following:
1. Document that storing the return values of GetConnections() for future use is discouraged;
2. Fail GetStatus() if the query descriptor is inconsistent, i.e. its other fields do not match its id.

**Comment by heplesser** [comment]
I assume that his is an effect of the rebuilding of the connection representation after changes to connections introduced with the 5G kernel. I further assume there is no easy work-around, but we need to document this. This would become problematic in particular in connection with structural plasticity when connections change all the time. Or am I to pessimistic?

**Comment by jakobj** [comment]
Yes, this is due to sorting the connections by the source gids, either triggered by a call to `GetConnections` or by `Simulate`. We could add a check that makes sure the available information does match and throw an error if it doesn't but I fear that this would still miss some cases. The first thing that comes to my mind is to be very transparent about the invalidation of connection descriptors, e.g., detecting when someone creates connections after having called `GetConnections` or `Simulate` and emitting a warning that the old descriptors should not be used any more. For structural plasticity, a similar approach should work, shouldn't it? I need to give this some more thought.

**Comment by jakobj** [comment]
I've created #1250 to print a warning when new connections are created that old connection descriptors are not valid any more. I think this is the most we can do, since checking for a match of the available information would lead to significant overhead (essentially `GetStatus` would need to do an additional `GetConnections` in addition to the `GetConnections` issued by the user), so I don't think that's a good idea.
