### ISSUE TITLE
Rounding error in small resolutions

### ISSUE THREAD

**Issue by weidel-p** [nest/nest-simulator#1305]
Setting the resolution to a small value often leads to rounding errors and unexpected behavior.

If I understand correctly, the resolution must be a multiple of the tic length which is by default _0.001 ms_. So a resolution of _0.105 ms_ and _0.102 ms_ should both work.

When I try to set these resolutions, the following happens:

`nest.SetKernelStatus({'resolution': 0.105})` -> `Temporal resolution changed.`

`nest.SetKernelStatus({'resolution': 0.102})` -> `Resolution must be a multiple of the tic length. Value unchanged.`

It's clear that this is a rounding issue as changing the representation of _0.102_ slightly by multiplying _0.0102_ by _10_ fixes the issue.

`nest.SetKernelStatus({'resolution': 0.0102 * 10})`  -> `Temporal resolution changed.`

I assume the responsible line of code is in `simulation_manager.cpp`:

`std::modf( resd * tics_per_ms, &integer_part ) != 0` 

Would it be sufficient to change the comparison with _0_ to a small epsilon or would that lead to other issues?

I'm using the Git commit:
0ac2385db24bdf76c43f310ee5f7da10d274c457

**Comment by heplesser** [comment]
@weidel-p Provided that epsilon is very small indeed (corresponding to the last 1-2 bits), this should be safe. We have some sensitive precision test, they might trigger if my assumption is wrong. Have you had a look at the blame-history to find the issue that introduced the problematic code? That might help us understand better why code is as it is, but in general, comparing floats to 0 exactly makes no sense precisely because of rounding errors.

If you need very high precision/resolution, you may want to consider to change the `tics_per_ms` and `resolution` to powers of 2.
