### ISSUE TITLE
only partially overridden in class ... 

### ISSUE THREAD

**Issue by ikitayama** [nest/nest-simulator#1315]
With a proprietary compiler, I am seeing a lot of warnings like below:

```
"/home/users/go21/go0009/projects/nest-simulator/nestkernel/parameter.h", line 281: warning: overloaded virtual function "nest::Parameter::value" is only partially overridden in class "nest::NormalParameter"
  class NormalParameter : public Parameter
```
Can someone explain as to why it wasn't fully implemented?

**Comment by heplesser** [comment]
This is in the nest-3 branch, isn't it? Any chance this could be related to missing `using` directives?

**Comment by ikitayama** [comment]
Yes, I am on nest-3.

**Comment by ikitayama** [comment]
With an old GCC that comes with RHEL 7.5, I see no warnings.

**Comment by hakonsbm** [comment]
I can confirm getting similar warnings as @ikitayama for `parameter.h` when compiling the nest-3 branch with GCC using the `-Woverloaded-virtual` flag. A warning is issued because a function declaration hides virtual functions from the base class. This can be solved using `using` directives, as noted by @heplesser.

Similar warnings also occur when compiling master, however, for the following member functions:
- `raw_value()` of topology parameter subclasses
- `inside()` of mask subclasses
- `handles_test_event()` of rate_neuron_ipn
- `handles_test_event()` of rate_transformer_node
- `handles_test_event()` of rate_neuron_opn
- `handles_test_event()` of siegert_neuron

**Comment by heplesser** [comment]
@hakonsbm We should fix the missing `using` directives everywhere. I would also suggest to add `-Woverloaded-virtual` to the compiler flags for testing on Travis, maybe just add them to the default compiler flags.

@lekshmideepu @gtrensch Are we counting/reporting compiler warnings in any way? We have the declared aim that NEST should compile without warnings, except where they arise from code beyond our control (Python interface).

**Comment by lekshmideepu** [comment]
@heplesser To my knowledge, we are not counting/reporting compiler warnings.
