### ISSUE TITLE
Missing documentation: How to provide custom functions in extension modules?

### ISSUE THREAD

**Issue by Helveg** [nest/nest-simulator#1317]
[This page](https://nest.github.io/nest-simulator/extension_modules) mentions that it's possible to extend NEST with custom functions and that [this page](https://nest.github.io/nest-simulator/index) should contain information how to. But neither pages seem to contain that information, did we miss it?

> By writing a new module, you can add
> 
> your own neuron models
> your own synapse types
> your own connection **(or other) functions**

> For information about how to write new neuron or synapse models **or functions** as part of your module, please see the corresponding documentation linked on the documentation index.

The use case is that for a workaround for #410 we'd like to expose our own function that executes some additional steps. The users of our module should preferably be able to do something like this:

```
nest.CreateTeacher(param1, param2)
# or
nest.OurModule.CreateTeacher(param1, param2)
```

Are we correct in assuming that this is possible with an extension module? If so, how? And could this be covered in the documentation?

**Comment by Helveg** [comment]
Could a short answer be provided here please? How can I make a custom function in a module and how to call it through PyNEST?

**Comment by Helveg** [comment]
@Silmathoron come get your StackOverflow points https://stackoverflow.com/questions/58690826/how-to-expose-a-custom-function-when-writing-a-nest-simulator-extension-module

**Comment by Silmathoron** [comment]
Hi @Helveg, this is clearly not in the SO spirit...
Furthermore, I'm afraid that a) I did not go deep enough into that part of NEST to give you an answer immediately and b) as mentioned in a previous discussion, the reason none of us has a high enough rep on SO is because we often don't have time to look for answers to these questions (for instance in this case, I cannot spend time looking for the answer)

All I can tell you from my knowledge of Python/Cython/C interactions is that the answer is probably "no, you cannot do that"; however, given that NEST Py/C interactions also heavily rely on SLI, there might be a way I do not know of.

Hopefully, somebody will have time to answer this in after the next developer VC...

**Comment by Helveg** [comment]
Sorry, I'm not implying malicious promotion on SO, it was a cheeky
reference to that previous discussion.

But ok, fingers crossed that there's a way to register a simple function,
really it's just an entry point to prevent the user having to execute a few
workaround steps in python.

Op ma 4 nov. 2019 om 14:23 schreef Tanguy Fardet <notifications@github.com>:

**Comment by heplesser** [comment]
@Helveg As you are looking for a work-around for #410, I assume you have also looked at #1242. If that is a problem you face, would you be interested in contributing a proper solution to NEST instead of creating your own private work-around? By integrating your solution in NEST, others would be able to run your models without the need to install additional modules, helping to spread your work.

We should probably remove the "or other" from the extension module documentation, since we have only ever designed and tested the extension module mechanism for additional neuron, synapse and connection builder types.

If you want to add a new function, take a look at `nestkernel/nestmodule.[h,cpp]`.  In the header,  for each new function a class is defined, declared from `SLIFunction`, and an instance defined. Each class has only an `execute()` method. Naming conventions are described at the top of the header file. The `execute()` method is then defined in the cpp-file.  The method should

1. check that enough arguments are on the SLI operand stack (`OStack`)
1. collect required arguments from the operand stack
1. execute actions as required, interacting with the NEST kernel through the methods declared in `nestkernel/nest.h`
1. push results to the operand stack
1. pop the execution stack `EStack` so that execution can pass to the next SLI command.

At the bottom of `nestmodule.cpp` you will see how to register the new function with the SLI interpreter. This registration can also happen in your `mymodule.cpp`. Any registered function will be immediately available in nest through the SLI interpreter. Function overloading for SLI functions should be implemented using type tries in `mymodule-init.sli`, see `lib/sli/nest-init.sli` for examples.

To call such functions from Python, you can call it through `nest.sli_func(sli_func_to_call, *args)`, which will push the arguments given to the stack, call your function, and return the result, see online documentation for `sli_func()`.

**Comment by Helveg** [comment]
Thanks @heplesser. The workaround however isn't very elegant or desirable to be integrated into NEST I think. If we get it working we'll certainly explain the problem and the solution so we can see if there's anything of value to NEST in there.

Ok so this explanation seems to cover how to add an SLI command that's actually sent to the kernel, correct? I don't think that's required, I think I only need to register a standard function, not an SLI one, so that the workaround is done under the hood in the module instead of in python.

**Comment by heplesser** [comment]
@Helveg I am not sure what you mean by "standard function".  Since you want to use your workaround from Python, I would suggest to do everything that can be done with existing NEST functions such as `Create` from the Python level and then have an additional function at the C++ level (exported to Python via SLI) just for the additional steps necessary. You are right that from inside `execute()`, you should not call SLI functions, just the functions provided via `nest.h`, plus functions/methods to manipulate the stack and to work with tokens collected from or to be pushed to the stack.

**Comment by Helveg** [comment]
With "standard function" I'd mean something like printing "Hello World" and calling a few SLI commands, a generic piece of code (in my case a factory function for a model) that I want available to people that install the module. It seems that I just need python bindings to be added so that the function I wrote is accessible to the user?

**Comment by heplesser** [comment]
@Helveg Have you made progress using the nest API functions from `nest.h`? If so, would you consider closing this issue?

**Comment by Helveg** [comment]
No I haven't tried. Maybe some day we'll give this another go :)
