### ISSUE TITLE
Not all files are checked with static code analysis on large PRs

### ISSUE THREAD

**Issue by hakonsbm** [nest/nest-simulator#1328]
On larger PRs, not all changed files are checked with static code analysis. This is because we are getting the changed files using the GitHub API. Because the GitHub API uses pagination, the code analysis will currently only get the first 30 changed files, while the remaining files are not checked for formatting errors.

Looking at for example [this Travis run](https://travis-ci.org/nest/nest-simulator/jobs/605035767#L1069) of #1282 with 947 changed files, [this Travis run](https://travis-ci.org/nest/nest-simulator/jobs/603833810#L1133) of #1283 with 460 changed files, or [this Travis run](https://travis-ci.org/nest/nest-simulator/jobs/411694777#L1289) of #920 with 279 changed files, only the the first 30 files are checked.

It is possible to increase the number of files returned using `per_page`, but this only goes up to 100. So for PRs with more than 100 changed files we must iterate the pages if we want to check all the files using the GitHub API.

Alternatively it might be possible to get the changed files using plain `git` and the variables set by Travis. The command
```
git diff --name-only --diff-filter=AM HEAD...$TRAVIS_BRANCH
```
could do the trick. @lekshmideepu Has this alternative been discussed before?

**Comment by Silmathoron** [comment]
I am not sure how I feel about fixing this...
Rather that doing that, as was already mentioned during one of the VC, I'd much rather fix how we handle our PRs to make sure that such huge PRs do not happen, given that they make proper code review much more complicated (not to say almost unrealistic).

In the case of changes such as NEST-3, for instance, this would mean 2nd order PRs to the NEST-3 branch, which would be properly reviewed and squashed, thus keeping the log readable for human beings and ensuring that each of the steps was properly checked.
At the end, there would be no need for a complete static code analysis since all checked would have passed on the 2nd order PRs and this issue would vanish altogether.

The only case where such an issue would still exist would then be whenever we decide to change the actual standards and such a change would be done automatically by something like clang anyway.

**Comment by lekshmideepu** [comment]
@hakonsbm I do remember one of the discussions which happened sometime ago where we have discussed the possibility of fixing the issue altogether. Personally I prefer this as we don't have to do static analysis checks for large number of files at once.

**Comment by hakonsbm** [comment]
@Silmathoron I do agree that we generally should try to avoid huge PRs, but in some cases that may be impossible. I therefore don't think we can have something like a hard limit on the number of changed files in a PR. All files should be checked by the static code analysis regardless of the PR size.

@lekshmideepu I'll see if the `git diff` solution can work on Travis then.
