### ISSUE TITLE
GetGlobal and DataConnect variants in PyNEST 2.8

### ISSUE THREAD

**Issue by Silmathoron** [nest/nest-simulator#135]
I am rather new to NEST, but I have been trying to reproduce topological graphs generated by usual graph libraries (graph_tool or snap) into NEST.
Functions that would be especially useful to me are:
- GetGlobalNodes/Leaves
- GetLocalNodes/Leaves
- DataConnect_i_D_s

However, these functions do not appear when I run *dir(nest)*: only DataConnect and GetNodes are present. The second one was especially surprising to me as [release notes from version 2.2.x](https://github.com/nest/nest-releases/blob/master/nest-2.2.x-release_notes.md) stipulate that this function should be deprecated.
Could someone tell me whether this is normal or not? For instance are they new changes because of the extensive modifications of 2.6 release?
Best regards.

**Comment by heplesser** [comment]
@Silmathoron There are some differences in the functions available in SLI (NEST's native intepreter) and PyNEST, which you presumably are using, since you call `dir(nest)`. In PyNEST, `GetNodes()` wraps both `GetGlobalNodes` (default) and `GetLocalNodes` (if called with `local_only=True`). The same holds for `GetLeaves()`. Also, `DataConnect()` on the Python level wraps `DataConnect_i_D_s` or an overloaded variant. Generally, any SLI functions with "appendages" are for internal use only, with the "appendage" providing information on the types of the arguments expected.

Btw, the NEST User mailing list would be a better place for a general enquiry like this than our issue tracker.

**Comment by Silmathoron** [comment]
Thank you for your reply, I'll make sure to use the mailing list in the future.
