### ISSUE TITLE
NodeCollections iterator returns NodeCollections

### ISSUE THREAD

**Issue by terhorstd** [nest/nest-simulator#1361]
in `nest-3` branch there is a problem with NodeCollections:
```python
>>> for n in nodes[::3]:
...    print(n)
NodeCollection(metadata=None, model=iaf_psc_alpha, size=1, first=16)
NodeCollection(metadata=None, model=iaf_psc_alpha, size=1, first=19)
NodeCollection(metadata=None, model=iaf_psc_alpha, size=1, first=22)
NodeCollection(metadata=None, model=iaf_psc_alpha, size=1, first=25)
```
This is expected to return integers (GIDs of nodes) given the documentation.
Problem manifested when using `np.array(nodes)`, which gave wrong results (high-dimensional array of objects)

current docker container of nest-3 branch can reproduce easily.

**Comment by terhorstd** [comment]
There seems to be a test missing for this.

**Comment by stinebuu** [comment]
@terhorstd it is the documentation that is outdated, not the iterator. We used to return the GID, but now we return a single element NodeCollection to make NodeCollection and SynapseCollection consistent, and so that it is possible to do something like
```
for n in nodes[::3]:
    n.set(V_m=-77.)
```

To convert to list, use `nodes.tolist()`, and to numpy array I guess you then need to do `np.array(nodes.tolist())`. This is I admit a bit of a hassle, but we want to keep the ID's in the form of NodeCollection as much as possible, and not convert them to lists.

Where in the documentation do you see this?

**Comment by clinssen** [comment]
Hej! Perhaps there are some hints here that will allow the `tolist()` method to be made implicit:

https://docs.python.org/3/reference/datamodel.html#emulating-container-types

**Comment by stinebuu** [comment]
I think the documentation should be up to date on this now, so I am closing this.
