### ISSUE TITLE
Superfluous omp barriers in `gather_spike_data_`

### ISSUE THREAD

**Issue by jakobj** [nest/nest-simulator#1441]
In `gather_spike_data_` these two barriers seem to be unnecessary, as they appear directly before a `gather_completed_checker_.all_true()` that contains a barrier (https://github.com/nest/nest-simulator/blob/master/nestkernel/completed_checker.cpp#L56):

https://github.com/nest/nest-simulator/blob/master/nestkernel/event_delivery_manager.cpp#L381
https://github.com/nest/nest-simulator/blob/master/nestkernel/event_delivery_manager.cpp#L390

i think they could be removed. this is just to remind us of the issue, we should discuss this carefully.

btw, the same repetition seems to appear in `gather_target_data_`. at least we were consistent. ;)

@suku248 @heplesser

**Comment by heplesser** [comment]
@jakobj Thank you for pointing this out!

In the code you point to,

```c++
#pragma omp barrier
    // Resize mpi buffers, if necessary and allowed.
    if ( not gather_completed_checker_.all_true() and kernel().mpi_manager.adaptive_spike_buffers() )
    {
#pragma omp single
      {
        buffer_size_spike_data_has_changed_ = kernel().mpi_manager.increase_buffer_size_spike_data();
      }
    }
#pragma omp barrier
```
I indeed agree that both barriers can be removed, since `all_true()` contains a barrier and `omp single` has an implicit barrier on completion.

At the same time, I get a strong feeling that we should plan a thorough refactoring session a few months from now to review our thread-parallelism. Barriers hidden in methods to do seem to be good code style, and many documents on threading warn against barriers inside conditionals, since they could lead to deadlocks if not all threads reach them (this seems not to be a problem in NEST). My impression is that it should be possible to express what we want to achieve in clearer and more robust code, if we take a proper step back and look at the bigger picture.
