### ISSUE TITLE
Use nest.Creat() and nest.SetStatus() in a loop

### ISSUE THREAD

**Issue by lslynf** [nest/nest-simulator#1452]
In my program, there are multiple sets of current data. To traverse this data, I want to create a neuron group, and then set the current value to simulate every time. But every time the neuron's nodes accumulate. The procedure is shown below：
```data #2 dimension
for i in range(data.shape[0]):
     neuron_group = nest.Create("iaf_psc_alpha", 39)
     cnt = 0
     for neuron in neuron_group:
           nest.SetStatus([neuron], {"I_e":data[i][cnt]})
           cnt += 1
     spikedetector = nest.Create("spike_detector", 1, params={"withgid": True, "withtime": True})
     nest.Connect(neuron_group, spikedetector)
     nest.Simulate(25)
     #then record the spike event times
```

**Comment by heplesser** [comment]
@lslynf [The NEST Users Mailing List](https://www.nest-simulator.org/mailinglist/postorius/lists/users.nest-simulator.org/) is a much better place for questions about how to use NEST. I will answer briefly here, but please use the mailing list for any follow-up questions.

There are two solutions:
1. If you add `nest.ResetKernel()` as the first line inside the for-loop, you will always get a "clean" NEST kernel for each round.
2. Let N be the number of iterations you do through the for-loop. Then, you could create N x 39 neurons and N spike detectors, initialize your neurons and connect them to spike detectors in groups of 39, and then simulate just once, reading out all N spike detectors at the end. This will probably be a bit faster, since you avoid N ResetKernels.
