### ISSUE TITLE
Phase7: Running PyNEST tests. failed

### ISSUE THREAD

**Issue by zhangliang3** [nest/nest-simulator#1483]
Hi, guys, 
I run "make installcheck" and get the following error:

Phase 7: Running PyNEST tests.
------------------------------

  Using nosetests.

  Failure: TypeError (super() takes at least 1 argument (0 given)) ... ERROR
  ERROR: Failure: TypeError (super() takes at least 1 argument (0 given))
  TypeError: super() takes at least 1 argument (0 given)
  FAILED (errors=1)
/usr/local/nest-simulator/share/nest/extras/do_tests.sh: 751: /usr/local/nest-simulator/share/nest/extras/do_tests.sh: arithmetic expression: expecting primary: " + "
CMakeFiles/installcheck.dir/build.make:74: recipe for target 'CMakeFiles/installcheck' failed
make[3]: *** [CMakeFiles/installcheck] Error 2
CMakeFiles/Makefile2:577: recipe for target 'CMakeFiles/installcheck.dir/all' failed
make[2]: *** [CMakeFiles/installcheck.dir/all] Error 2
CMakeFiles/Makefile2:584: recipe for target 'CMakeFiles/installcheck.dir/rule' failed
make[1]: *** [CMakeFiles/installcheck.dir/rule] Error 2
Makefile:192: recipe for target 'installcheck' failed
make: *** [installcheck] Error 2

Do you have any idea about it? Thanks!

Sincerely
Liang

**Comment by Silmathoron** [comment]
This looks like you're using the master version with python 2, which is no longer supported, try with python 3.
For more precise support, please do as the bug report template tells you:

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. (Minimal) reproducing example
2. Used parameters
3. Command to run
4. How to see error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop/Environment (please complete the following information):**
 - OS: [e.g. iOS, Ubuntu-18.04]
 - Browser: [if applicable, e.g. chrome, safari]
 - Shell: [e.g. bash, zsh]
 - Python-Version: [e.g. Python 3.6]
 - NEST-Version: [e.g. nest-2.18, or git hash]
 - Installation: [e.g. conda packet, apt, with/out MPI, ...]
   (in case you compiled the source code manually, provide the
    "Installation Summary" that you see at the end of the 
    cmake step)

**Additional context**
Add any other context about the problem here.

**Comment by zhangliang3** [comment]
> This looks like you're using the master version with python 2, which is no longer supported, try with python 3.
> For more precise support, please do as the bug report template tells you:
> 
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
>     1. (Minimal) reproducing example
> 
>     2. Used parameters
> 
>     3. Command to run
> 
>     4. How to see error
> 
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Desktop/Environment (please complete the following information):**
> 
>     * OS: [e.g. iOS, Ubuntu-18.04]
> 
>     * Browser: [if applicable, e.g. chrome, safari]
> 
>     * Shell: [e.g. bash, zsh]
> 
>     * Python-Version: [e.g. Python 3.6]
> 
>     * NEST-Version: [e.g. nest-2.18, or git hash]
> 
>     * Installation: [e.g. conda packet, apt, with/out MPI, ...]
>       (in case you compiled the source code manually, provide the
>       "Installation Summary" that you see at the end of the
>       cmake step)
> 
> 
> **Additional context**
> Add any other context about the problem here.

Thanks very much

Best Wishes

Liang
