### ISSUE TITLE
MUSIC tutorial on ReadTheDocs needs updating

### ISSUE THREAD

**Issue by stinebuu** [nest/nest-simulator#1495]
**Describe the bug**
The MUSIC tutorial on ReadTheDocs is outdated and needs to be updated to fit with NEST 3.0. Especially the [MUSIC with SLI](https://nest-simulator.readthedocs.io/en/latest/tutorials/music_tutorial/music_tutorial_sli.html) documentation, which references `subnet` and outdated functions like `LayoutNetwork`. The other pages are outdated as well though.

**Screenshots**
Looking very quickly at the first Python example in [Connect two NEST simulations using MUSIC](https://nest-simulator.readthedocs.io/en/latest/tutorials/music_tutorial/music_tutorial_2.html) you can see some of the outdated code:

![MUSIC_tutorial](https://user-images.githubusercontent.com/21308850/78131178-eb11b780-741a-11ea-9878-93484ddeba77.png)

**Comment by sarakonradi** [comment]
A brief update: 

After discussing this issue with @stinebuu, we figured that the best approach would be to begin updating the code blocks. @stinebuu will give me access once those are up-to-date, so that we can improve the documentation accordingly.

@jougs Do you have any input regarding the MUSIC tutorial's content, and whether or not any parts of the text need to be rewritten? Thanks!
