### ISSUE TITLE
Multimeter sampling with offset parameter

### ISSUE THREAD

**Issue by zbarni** [nest/nest-simulator#1508]
**Description: The multimeter returns unexpected samples for certain `interval` and `offset` parameter combinations**

The multimeter records an unexpected first sample when it is created and connected after some initial simulation period. The multimeter documentation is not complete, but if I remember correctly, we implemented the `offset` parameter #669 to record the first sample relative to `0.`, including a test meant to verify exactly such scenarios with initial simulation time and later recorder creation. However, the test fails to cover some more specific scenarios.

**To Reproduce**
There are 2 slightly different examples of strange recordings, both adapted from the existing [unittest](https://github.com/nest/nest-simulator/blob/v2.20.0/testsuite/unittests/test_multimeter_offset.sli). Steps to reproduce the behavior:

### Scenario 1
```
import nest

simtimeinit = 10
simtime = 20.
recoffs = 1.
recint = 3.
recstart = 10.  # this is not important, remains for comparison with the unittest
recstop = 30.

resolution = 0.1

nest.SetKernelStatus({'resolution': resolution})
neuron = nest.Create('iaf_psc_exp')

mm1 = nest.Create("multimeter", 1)
nest.SetStatus(mm1, {"withtime": True, "record_from": ["V_m"],
                            'interval': recint, 'offset': recoffs,
                            'start': recstart, 'stop': recstop})
nest.Connect(mm1, neuron, syn_spec={'delay': 0.1})

nest.Simulate(simtimeinit)

mm2 = nest.Create("multimeter", 1)
nest.SetStatus(mm2, {"withtime": True, "record_from": ["V_m"],
                            'interval': recint, 'offset': recoffs,
                            'start': recstart, 'stop': recstop})
nest.Connect(mm2, neuron, syn_spec={'delay': 0.1})

nest.Simulate(simtime)
times = nest.GetStatus(mm1)[0]['events']['times']
times2 = nest.GetStatus(mm2)[0]['events']['times']
print(times)
print(times2)
```

**Expected behavior**
Returns
```
[13. 16. 19. 22. 25. 28.]
[10.1 13.  16.  19.  22.  25.  28. ]
```
even though the two outputs should be equal. The sample at `10.1` looks incorrect. Note that this error depends on `simtimeinit`, e.g., it only occurs for `simtimeinit >= 10.0`.

### Scenario 2
```
import nest
resolution = 0.1
interval = 60.
offset = 170.3

initial_sim_time = 110.

nest.SetKernelStatus({'resolution': resolution})
neuron = nest.Create('iaf_psc_exp')
##################
nest.Simulate(initial_sim_time)

multimeter = nest.Create("multimeter", 1)
nest.SetStatus(multimeter, {"withtime": True, "record_from": ["V_m"],
                            'interval': interval, 'offset': offset})
nest.Connect(multimeter, neuron, syn_spec={'delay': 0.1})
nest.Simulate(250.)
times = nest.GetStatus(multimeter)[0]['events']['times']
print(times[0])
```
**Expected behavior**
Returns `230.3`, instead of `170.3` if the offset was relative to `0.` There seems to be a relation between the recording interval, offset, and the initial simulation time before creation. For this case, the first sample if off by exactly 1 interval (60.0 ms), but if we set `initial_sim_time = 121.` (so larger than `2*interval`, the first sample is recorded at `290.3`, so it'd be off by twice the interval.

**Desktop/Environment (please complete the following information):**
 - OS: Linux Mint 19.2 Cinnamon
 - Python-Version: 3.6
 - NEST-Version: 2.20.0, 2.18.0
 - Installation: barebone (no conda), with MPI

**Additional context**
I'm not sure the behaviour in the two scenarios are related, or whether this is an issue in the `Multimeter` or the `UniversalDataLogger`. If somehow these are correct behaviours, the documentation should be extended accordingly.

**Comment by stinebuu** [comment]
@zbarni For the second scenario, if `offset` is `0.0`, we get a sample at `120.0`, so shouldn't the time be `290.3` and not `170.3` when we have the offset? The result we are currently getting is at any rate wrong, I just need to understand better I think.

For the first scenario the samples are `[12. 15. 18. 21. 24. 27.]` when `offset` is `0.0` and with `offset=1.0` they are `[13. 16. 19. 22. 25. 28.]`, so 1 away from the original sample. So the sample for scenario 2 should be `170.3` from the original sample as well?

**Comment by zbarni** [comment]
Hi @stinebuu! If I recall correctly from #669, we implemented the `offset` to record data at all times `t == n * h == offset + k * interval`, where h is the simulation resolution and `n` and `k` are non-negative integers (n>=1, k>=0). Or at least that was the idea. In other words, if one sets `offset = x`, the first sample should always be `x`, and the interval counting should start from there (relative to `x`). However, I now noticed that for `offset = 0.` the first sample is at `interval` and not `0.`, so there's this exception.

The implementation you described would require the first sample to be at `offset + k_ * interval`, but `k_ >= 0` would not hold anymore. Actually, `min(k_)`  would depend directly on the simulation time elapsed before the multimeter creation. To put this in the context of the second scenario where `offset = 170.3`, 

- the first sample should be at `290.3` as you said, if we simulated `initial_sim_time = 110.` ms in the beginning (or in the range `(60., 120.]` )
- for `initial_sim_time = 121.` (or in the range `(120., 180.]` ), the first sample should then be at `350.7`, since the "original sample" would have been at `180.` with `offset = 0.`. 

What's more, this possibility still doesn't explain the problem in scenario # 1, where the first sample is somehow at `10.1` if `initial_sim_time >= 10.` and correct (`13.`) for `initial_sim_time < 10.`..

That said, I think this is not the intended behaviour of the current implementation, but I might be wrong. We actually tested for such cases in the [unittest](https://github.com/nest/nest-simulator/blob/v2.20.0/testsuite/unittests/test_multimeter_offset.sli), but it seems we didn't cover all possible cases..

**Comment by stinebuu** [comment]
@zbarni Ah, I think I understand now. So for the first scenario, because `offset` is `1`, interval is `3`, the samples should occur at `1, 4, 7, 10, 13, 16, 19,..`, but since we start to record at `10`, only `13, 16, 19,..` should be recorded? `10.1` should at any rate not be there.

For scenario 2, as `interval` is 60, the first sample should be at `170.3` and the next should then be `230.3`?

Sorry if these questions seems basic, I just want to make sure I understand.

**Comment by zbarni** [comment]
Precisely. You can actually remove `rec_start` to see all the samples. And don't worry about the questions, they're not basic.. I also spent a lot of time figuring out the supposed behaviour, and the documention could also use a much needed improvement.

**Comment by stinebuu** [comment]
@zbarni I have added a PR to address the issue, #1564. Hopefully it takes care of most corner cases! I added your two test cases and also added one of my own.

**Comment by zbarni** [comment]
Thanks! Can you briefly describe what the issue was?

**Comment by stinebuu** [comment]
Sure! In `universal_data_logger_impl.h` we find the next recording step based on current simulation time, `interval` and `offset`. If `offset` was not 0, we go one `interval` step back and add offset.
https://github.com/nest/nest-simulator/blob/10ad3af021fd2ef6d999087bc3f56db6791c5db9/nestkernel/universal_data_logger_impl.h#L120-L125

This is correct if we have not simulated before, because `offset` is set relative to `0.0`. But, if we have already simulated,   `offset` will no longer be relative to `0.0` and we might then go too far.

For your second scenario for instance, initial simtime is `110.0`, `interval` is `60` and the multimeter is created after the initial simulation, so offset is not set before the initial simtime is finished. Then, for the second simulation (with the multimeter) next recording time will first be `120` because recording interval is 60 and then, because of the offset, we say that the next recording time should be `120 - 60 + 170.3 = 230.3`, which is one interval too much.

Now I have done so that if we have a `offset` we calculate the next recording step from `0.0`. We first say that next recording step should be `offset`, and then we add `interval` until we have reached  current simulation time. This way, `offset` will always be set relative to `0.0`. Basically
```
if offset:
    new_rec_step = offset
    while new_rec_step <= current time:
        new_rec_step += interval
```
See [here for implementaion](https://github.com/stinebuu/nest-simulator/blob/6d6427d089080054afd145244b7c3fa1e803f832/nestkernel/universal_data_logger_impl.h#L120-L130).

For your second scenario again, after the initial simulation, we say that next recording step should be `offset`, and then don't add anything, because `170.3 > 110.0`. If initial simulation time had been `250.0` however, we would say next recording step is `170.3` then add interval until next recording step is greater than current time: `170.3 + 60 = 230.3, 230.3 + 60 = 290.0`.

Does this make sense?

**Comment by zbarni** [comment]
Thanks for the detailed response, I think this should do it..

**Comment by heplesser** [comment]
@zbarni Can this issue be closed then? Feel free to close it yourself!

**Comment by stinebuu** [comment]
@heplesser I think we should wait for #1564 to be merged! :)
