### ISSUE TITLE
Cross-check examples against publications

### ISSUE THREAD

**Issue by sarakonradi** [nest/nest-simulator#1516]
This issue follows up on #1504 and invites us to check that the PyNEST examples that refer to publications properly match those publications.

@heplesser pointed out a very interesting point regarding the Brette and Gerstner example: 

> Another interesting point is that the default parameter values of the aeif_conda_alpha model actually don't agree with the values in Brette & Gerstner. In particular, membrane potential is reset to -60 mV in the NEST example instead of to E_L = -70.6 mV in the paper. To simulate the model as in the paper, change line 52 to

``` python
neuron = nest.Create("aeif_cond_alpha", params={'V_peak': 20.0, 'V_reset': -70.6})
```
There may be instances like this elsewhere in the examples that need to be updated.

**Comment by clinssen** [comment]
This issue seems overly broad and not practical to address (unless we can find a PhD student with many spare cycles). I would suggest to create seperate issues for specific cases to prevent feature creep.

**Comment by clinssen** [comment]
The NEST Hackathon of November 2020 agrees that this issue is overly broad, and to only address the aeif_cond_alpha initial values issue raised by @heplesser.

This issue, of aeif_cond_alpha initial conditions not matching the values in the corresponding publication, has apparently already been fixed in the relevant script (``pynest/examples/brette_gerstner_fig_2c.py``) in the meantime.

Taken together, this issue can be closed without further action.
