### ISSUE TITLE
Fast trace calculator

### ISSUE THREAD

**Issue by sepehrmn** [nest/nest-simulator#1519]
For many studies of neural data, such as reservoir computing, it is necessary to have a continuous trace of spiking activity. For really large simulations, this can be computationally expensive and require a lot of memory. It is useful to have it done in real-time with the simulation and take advantage of NEST's parallelization. A few years back I wrote a fast memory-efficient device that accomplishes  #436 this but NEST has changed since. I can now invest some more time to make it compatible with the current NEST version and have it merged.

Any issues or suggestions?

**Comment by sepehrmn** [comment]
@clinssen any issues/suggestions/complaints about this?

**Comment by clinssen** [comment]
It seems like the previous PR stranded only because of minor details, like having a lot of lines in a function. However, @heplesser raised questions about the desirability of this feature. Because I was not part of this discussion, perhaps it might help to describe the use case in a bit more detail. You mention reservoir computing; do you mean that the rate calculated by your proposed device will be used exclusively in the readout neurons? Could you also elaborate on why we could not just use a neuron for this purpose as a leaky integrator, with the threshold set to infinity? How is the "fast trace calculator" fundamentally different?

**Comment by sepehrmn** [comment]
@clinssen yes you are right. This device was done and almost got merged but there were minor refactoring issues that I did not have time to finish at the time. 

> do you mean that the rate calculated by your proposed device will be used exclusively in the readout neurons?

Yes, in the reservoir computing context.

> Could you also elaborate on why we could not just use a neuron for this purpose as a leaky integrator, with the threshold set to infinity? How is the "fast trace calculator" fundamentally different?

This device was motivated by the need for performance and efficiency in large simulations. There are many ways to accomplish this but all except having a native NEST device have had limitations or disadvantages. For example, one could stop the simulation, get the data, free up the memory and continue until the next desired time step for collecting the trace but this is very expensive. While this may not be an issue for a small number of neurons, to scale to 100k+ something like this is needed. It is also convenient as it saves a lot of code.

Are you suggesting using a multimeter on a neuron that does the same compuation? Don't you have to basically create 1 extra neuron for every neuron in your network for that? This device does not miss any spiking information and you can specify time windows (e.g.,   filter_start_times = [49.0, 99.0] , filter_stop_times = [50.0, 100.0]) and an interval. I'm not sure how the performance would compare to a multimeter (probably would be faster).  If this does not provide a sufficient answer, we would have to look at what has changed past 3 years in such a setup. Let me know.

**Comment by benef23** [comment]
Hi @sepehrmn and @clinssen,

thank you for suggesting this new device, this is exactly what I am searching for and the proposed implementation sounds very promising!

My use case:
I am implementing neural networks that are not based on exact spike time information encoding, but information is encoded in the spike frequency. With the 'spike_detector' device it's possible to read out exact spike timings, however in a frequency encoded network (which potentially includes noise on the exact spike time) I am rather interested in the real-time frequencies of the individual neuron connections. This would be the only way to read out the information of the neural network at the output layer. But in addition, I am also interested in frequencies of individual and group connections in order to investigate the network behavior and e.g. better balance network load by optimizing synapse weights and individual neuron normalization etc. 
Currently this would be possible by attaching a LIF neuron with infinite threshold to the neurons to read out the frequency as membrane potential, however the LIF neuron brings other characteristics that are not easy tuneable or just not desired. A frequency recording device, where you can set filter times, but also the filter windows would be much more intuitive and directly useful in order to inspect AND read out frequencies in the network.

Importance:
In the Neurorobotics Platform (www.neurorobotics.net) we have currently implemented a LIF with infinite threshold in order to connect neuron output to muscle activation (or robot motor setpoint) in a closed loop simulation. However, this is currently the only way implemented to interface neural network and body in real-time. A frequency readout with variable window size would open up many more possibilities to process the network output directly and improve the interface. 

Optional: 
I also couldn't find a device to _generate_ a spike train with fixed frequency, except the poisson generator that comes with noise. We are currently implementing this feed in indirectly by attaching a DC source. However, a fixedfrequency_genertor device would be much more intuitive and better to use for the research of frequency encoding networks.


@sepehrmn, I saw your #436. Where you able to reimplemented the device for the actual Nest version so that I can check it out?

**Comment by sepehrmn** [comment]
@benef23 many thanks for your message. Unless something has changed in how NEST progresses the simulation (which I highly doubt it), making it compatible with the current NEST version should only require investment of time to do some refactoring.

Since there is demand and no objections, I guess this is a "GO"?

@jougs would you please direct me to resources or comment as NESTIO pertains to this work?

**Comment by jougs** [comment]
@sepehrmn: I think if you look at the current implementation of the `spike_detector`, it should become clear what you have to do to have your new device use the NESTio infrastructure. In particular, you have to
* register the names of the recordables in `calibrate()`
* return the correct device type in `get_type()`
* hand the recorded values over to `write()` in `update()`.

I suggest that we discuss the details and further details in the PR once that's up for review. Please make sure to mention me there.

**Comment by sepehrmn** [comment]
Many thanks. I expect to have the pull request up in around a month.

**Comment by sepehrmn** [comment]
Started preparing it for a new pull request. should be this week.

**Comment by sepehrmn** [comment]
Finishing and will be up by the end of this week for peer review. Closing the issue.
