### ISSUE TITLE
Skip documentation when installing cross-compiled NEST

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#152]
This is issue is based on a report by Babak Keshavarz on NEST User 10 Nov 2015.

Running `make install` on a cross-compiled NEST may lead to a crash during the installation of NEST Online documentation because the cross-compiled SLI executable may not work on the machine executing make. 

Installing the documentation is the last step in the NEST install process. We should check whether SLI can run, and if not, issue an message pointing out that online help is not installed.

See also #153.

**Comment by steffengraber** [comment]
I added a set of helping tools for the NEST documentation. See pull request #157.
The python tool generate_help2jsonhtml.py in extras/userdoc/generator extract the whole documentation from the code files (".sli", ".cpp", ".cc", ".h") and write it to HTML and JSON files.
See the documentation: extras/userdoc/README.md.
It is very fast and maybe it is an solution.

**Comment by apeyser** [comment]
A --without-doc configure flag should be added, since it appears to me that no such flag exists.

Every solution will require some set of tools, which will lead to corner cases with failures on top of wasted compilation time. We already have the "IS_BLUEGENE" flag to suppress slidoc because of this problem (among others). We should have a configuration that skips all of it from the get go.

**Comment by jougs** [comment]
Also see trac.791 for a related issue.

**Comment by apeyser** [comment]
Yes -- a number of options should be explicitly disable-able such as docs and readline, instead of being the result of special-case flags (such as enable-bluegene). Whether they are done by implicit checks and disabling, or by failing on tests and requiring explicit disabling is a further question of complexity. But a first cut is making sure that one can disable things like docs piecewise.

**Comment by tammoippen** [comment]
With #213 being merged, installing NEST skips generating the help documentation when cross compiling; see [here](https://github.com/nest/nest-simulator/blob/master/sli/CMakeLists.txt#L145). Hence closing as fixed.
