### ISSUE TITLE
Empty NodeCollection constructor

### ISSUE THREAD

**Issue by BSVogler** [nest/nest-simulator#1522]
nest3 encourages the use of NodeCollections instead of neuron id lists 

> One thing you should not do is to use your knowledge about neuron ids to set up loops

When adding several neurons from node collections to a node collection it is **not** possible to create an empty node collection:

```python
neurons = nest.NodeCollection()
neurons += nest.create(…)
neurons += nest.create(…)
```

The workaround `nest.NodeCollection([])` causes a crash when attempting to connect. As this is seemingly an invalid call it should throw an error.

I would like the introduction of the no-parameter constructor.

Alternatives is currently only working like this:
```python
neuronslist = []
neuronslist.extend(nest.create(…).tolist())
neuronslist.extend(nest.create(…).tolist())
neurons = NodeCollection(neuronslist)
```

This leads to code, where you manage node collections and node id lists side-by-side with redundancy.

**Comment by heplesser** [comment]
@BSVogler Just to make sure I understand you correctly: You would want avoid the redundancy of lists and node collections that occurs in your last code example above, correct? At the same time you want to avoid 
```python
neurons = nest.create(…)
neurons += nest.create(…)
```
where the first line is just assignment and the second an updating assignment, because you want all in a loop?

@hakonsbm @stinebuu What would you think about supporting empty NCs?

**Comment by stinebuu** [comment]
@heplesser @BSVogler I see no problem with having empty NodeCollections. We actually support empty SynapseCollections already, so it would be nice for consistency as well. I can have a look, it shouldn't be too difficult to implement I think.

**Comment by Silmathoron** [comment]
I encountered a similar issue and I think it was related to the fact that ``NodeCollection`` are kind of "typed", in the sense that they check if they contain neurons or devices, and user-defined collections are currently not properly typed in that respect.
I see two main possibilities:
* add a parameter asking for the type of the empty ``NodeCollection``
* use the type of the first nodes added to the initially empty collection (so type afterwards)

**Comment by BSVogler** [comment]
> where the first line is just assignment and the second an updating assignment, because you want all in a loop?

Not necessarily a loop. For example I want to create different neurons and then update a parameter for all of them with `nodecolelction.set()`. Basically I just want to replace the rather ugly alternative with the suggested clean solution.
> I encountered a similar issue and I think it was related to the fact that `NodeCollection` are kind of "typed", in the sense that they check if they contain neurons or devices, and user-defined collections are currently not properly typed in that respect.

If there are two types, why not use two different python types like NeuronCollection and DeviceCollection in combination with a factory method based on the first added node?

**Comment by stinebuu** [comment]
The problem with the empty NodeCollection is not the type, it is the fact that no nodes are created. When you try to connect for instance, we check the node and try to connect that node to others, but the node is not there so an error occurs. The same problem occurs if you try to set a parameter, because you are trying to set a parameter on a node that doesn't exist. NodeCollections do not distinguish between neurons or devices, but different schemes in NEST does. This is taken care of through the nodes though, and doesn't impact the NodeCollection.

As @heplesser said the following is possible, and then you can update all parameters at once:
```
neurons = nest.create(…)
neurons += nest.create(…)
neurons.set(...)
```

Note though that different model types have different parameters. If I remember correctly and you have a NodeCollection consisting of different models, updating a parameter that only pertain to one model is still possible and will only update the nodes with that parameter.

**Comment by hakonsbm** [comment]
Because it is possible to create an empty NodeCollection, and get an empty NodeCollection from for example `GetNodes()`, I think we should make empty NodeCollections aware that they are empty. Using an empty NodeCollection when joining or connecting can then be done properly. Also printing an empty NodeCollection should explicitly state that it is empty.

**Comment by BSVogler** [comment]
> As @heplesser said the following is possible, and then you can update all parameters at once:

This is bugged.
After adding a node collection to the collection of the same type a proxy node out of nowhere appears, causing some set commands to fail.

```python
collection = nest.Create(neuronmodel, num_neurons)
print(collection[0])
# prints NodeCollection(metadata=None, model=iaf_psc_alpha, size=1, first=6)
collection += nest.Create(neuronmodel, num_neurons)
print(collection[0])
#prints NodeCollection(metadata=None, model=proxynode, size=1, first=0, last=0)
```

**Comment by stinebuu** [comment]
@BSVogler I am not able to reproduce this unfortunately, could give the code to reproduce it?

**Comment by Silmathoron** [comment]
@hakonsbm in your [proposal](https://github.com/nest/nest-simulator/issues/1522#issuecomment-617174613), would:

```python
nc = nest.NodeCollection()
nc += nest.Create("spike_detector")
```

lead to the same object as

```python
nc = nest.Create("spike_detector")
```

I think it would be really great if it did; currently doing
```python
nc = nest.NodeCollection([])
nc += nest.Create("spike_detector")
```
leads to a composite ``NodeCollection`` which does not seem to be usable. E.g. trying to do ``nc[0]`` leads to

    NESTErrors.Invalid part or offset into NodeCollectionComposite: ('Invalid part or offset into NodeCollectionComposite in Take_g_a: ', 'Invalid part or offset into NodeCollectionComposite', 'Take_g_a', ': ')

**Comment by BSVogler** [comment]
The idea behind hakonsbm proposal is any type information should be based on the content. The current implementation seems to be based on the content during creation. Therefore I would agree that [the described behavior](https://github.com/nest/nest-simulator/issues/1522#issuecomment-645221311) by Silmathorono should be changed.
