### ISSUE TITLE
regressiontests/issue-779-1016.py may fail due to insufficient PATH

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#1547]
**Describe the bug**
`regressiontests/issue-779-1016.py` fails because the `nest` executable is not found.

**To Reproduce**
1. Invoke `make installcheck` in a shell in which `nest` is not in the `PATH`
2. Alternatively, invoke `python .../issue-779-1016.py` in a shell in which `nest` is not in the `PATH`

**Expected behavior**
Test passes or at least does not fail because of not finding NEST.

**Desktop/Environment (please complete the following information):**
 - OS: macOS 10.14
 - Shell: bash
 - Python-Version: 3.7
 - NEST-Version: master

**Analysis**
The problem seems to be that when the Python script is run from `do_tests.sh` and then invokes `nest` via `subprocess.check_output()`, the subprocess does not seem to inherit the environment `PATH` variable including the path to `nest` correctly. To make the test more robust and ensure that the correct `nest` is tested, I suggest to [build the nest invocation with the absolute path to the executable](https://github.com/nest/nest-simulator/blob/9ca796ef014058d01240bb977954e6b3e9d6b841/testsuite/regressiontests/issue-779-1016.py#L46).

**Comment by jougs** [comment]
During my work on #1686, I have [seen](https://travis-ci.org/github/nest/nest-simulator/jobs/705926332#L7917) the same test fail. The reason for failure in my case was that I (accidentally) removed the setting of the environment variable `PYTHON` from `do_tests.sh`, which in turn lead to `run_tests.sh` not being able to execute Python tests in situations when PyNEST was not enabled. The fix for my problem is in d449855.

I have now tried to reproduce the problem described here, but was not able to do so. Could you please try to reproduce with a more recent version, and/or give me a pointer to an instance on Travis where this is failing? Thanks!

**Comment by jougs** [comment]
@heplesser: ping!

**Comment by heplesser** [comment]
@jougs Works well for me now, too, so I will close the issue.
