### ISSUE TITLE
PyNEST+MUSIC+OpenMP fails to work

### ISSUE THREAD

**Issue by JanneM** [nest/nest-simulator#156]
PyNEST and MUSIC (1.1.15) fails on the receiving side when OpenMP is enabled and two models are connected using MUSIC. The sending side works. SLI models are unaffected. It happens when explicitly setting either local_num_threads or _total_num_virtual_procs on the receiving side. This is reproducible on both architectures I have access to (Linux/AMD64 and K). 

The error message complains that the port "event_in" does not exist, but "event_in" is not used as a port name anywhere:

Traceback (most recent call last):
  File "./receivenest.py", line 13, in <module>
    params = {'port_name': 'music_in'})
  File "/home/janne/bin/n28/lib/python2.7/site-packages/nest/lib/hl_api_helper.py", line 138, in stack_checker_func
    return f(*args, **kwargs)
  File "/home/janne/bin/n28/lib/python2.7/site-packages/nest/lib/hl_api_nodes.py", line 44, in Create
    sr(cmd)
  File "/home/janne/bin/n28/lib/python2.7/site-packages/nest/__init__.py", line 79, in catching_sli_run
    raise _kernel.NESTError("{0} in {1}{2}".format(errorname, commandname, message))
pynestkernel.NESTError: MUSICPortUnknown in SetDefaults_l_D: The port event_in does not exist.

I'm attaching a simple test case (remove the ".txt" endings - is there a better way to add things like this?):

[receivenest.py.txt](https://github.com/nest/nest-simulator/files/36323/receivenest.py.txt)
[sendnest.py.txt](https://github.com/nest/nest-simulator/files/36325/sendnest.py.txt)
[ompfault.music.txt](https://github.com/nest/nest-simulator/files/36324/ompfault.music.txt)

Run it with:

$ mpirun -np 2 music ompfault.music

If you comment out the local_num_threads statement in receivenest, the test works. Keep it in, or uncomment total_num_virtual_procs, and it fails.

**Comment by mdjurfeldt** [comment]
The reason for this is that setting total_num_virtual_threads causes Network::reset () to be called which causes clearing of the Network::music_in_portlist_. This also clears the port name which the music_event_in_proxy had registered (event_in) and music_event_in_proxy is never given a new chance to register it.

I guess there are two possible solutions:

1. Introduce a new virtual method in the API for Node which tells a model to setup its pristine state. Network::init_ should then call it when cloning pristine models.

2. Put in a special call into music_event_in_proxy in the MUSIC section of Network::init_ which does the same.

Since this anyway has to be solved differently in NEST 3, I suggest that we do the quick-and-dirty 2 for now.  Comments?

**Comment by mdjurfeldt** [comment]
My previously suggested solution 1 is somewhat invasive in that all nodes will have an extra method. Solution 2 has the ugly effect of requiring network.cpp to #include "music_event_in_proxy.h".

I'll now instead prepare a pull request for solution 3 which is to maintain a pristine copy of music_in_portlist representing the state after models have been loaded. This is then used to initialize the list in Network::init_ instead of clearing it.

**Comment by JanneM** [comment]
I can confirm that pull request #165 indeed solves this issue. I'll close this issue.
