### ISSUE TITLE
Providing key:dictionary pair to SetStatus via PyNEST generates uninformative error message

### ISSUE THREAD

**Issue by jakobj** [nest/nest-simulator#1575]
Calling the following line in pynest (3115cf68bda26e282c7f7a20fc00a7755eeb2b5b)
```python
nest.SetStatus(n, {'test_dict': {}})
```
leads to the following error:
```bash
nest.lib.hl_api_exceptions.DictError: ("DictError in get_d: Key '/test_dict' does not exist in dictionary.", 'DictError', 'get_d', ": Key '/test_dict' does not exist in dictionary.")
```

instead of the more informative response from SLI (`n << /test_dict << >> >> SetStatus`):
```bash
May 01 16:34:40 SetStatus_id [Error]: DictError
    Unused dictionary items:  test_dict
```

This in itself would be just a minor inconvencience, but if I actually implement `test_dict` in the corresponding model
```c++
  DictionaryDatum test_dict;
  if ( d->known( "test_dict" ) )
  {
    updateValue< DictionaryDatum >( d, "test_dict", test_dict );
  }
```

pynest still throws the same error as above, while SLI succeeds.

I'm digging into the pynest api, but maybe @hakonsbm @stinebuu could point me in the right direction?

**Comment by hakonsbm** [comment]
@jakobj The problem is the `n0.get(key)` in `SetStatus()`, here:
https://github.com/nest/nest-simulator/blob/6c9bf2a803c537763d7f48d7d520c7201c90cc20/pynest/nest/lib/hl_api_info.py#L290-L291
The key (`'test_dict'`) is not in the resulting dictionary when calling `GetStatus()` in `get()`, so it throws an error. `SetStatus()` should probably check if the parameter key exists in the model before getting to this point.

**Comment by stinebuu** [comment]
@jakobj Did @hakonsbm's comment help you solve the problem?
