### ISSUE TITLE
Collect dependencies in central file 

### ISSUE THREAD

**Issue by sarakonradi** [nest/nest-simulator#1612]
As @terhorstd pointed out in #1515, we should have a central file where dependencies are collected, as we do for the documentation (conda environment). 

The "Dependencies" section in ``doc/installation/linux_install.rst`` could then have an additional sentence like "For the full list of requirements, check here".

**Comment by terhorstd** [comment]
This is also interesting in the context of #1589.

**Comment by terhorstd** [comment]
The development dependencies  (#1757) maybe are different from the build dependencies.

**Comment by terhorstd** [comment]
For the documentation we may consider loading the `environment.yml` in `conf.py` and exposing the dependencies as variables. Then the maintenance of version numbers in the documentation becomes much easier. Have a look at this [stackoverflow post](https://stackoverflow.com/a/33845358/14085246).

**Comment by heplesser** [comment]
Using one central `environment.yml` file seems to make a lot of sense. We should also use it in our CI build scripts then, both to avoid duplicity and to test the file itself. One point I wonder about is about the relation between `pip` and `conda` here. I know conda can handle `environment.yml` files that have a separate "pip" section for packages not available from conda, but I don't know how it is the other way around. It would be good if conda users could use the `environment.yml` file as well.

**Comment by heplesser** [comment]
It seems @jougs pretty much just answered my question in #1843.

**Comment by jougs** [comment]
I think that it could be a bit confusing to have a set of requirement files in each location where we need them and expect users to infer their meaning based on location, i.e.
* top-level `environment.yml` and `requirements.txt` for runtime requirements
* `extras/environment.yml` and `extras/requirements.txt` for build requirements
* `doc/environment.yml` and `doc/requirements.txt` for documentation requirements
* `testsuite/environment.yml` and `testsuite/requirements.txt` for testing requirements 

Alternatively, we could have
* `extras/conda-environment-nest-{doc,test,build,run}.yml`
* `extras/pyenv-requirements-{doc,test,build,run}.txt`

**Comment by heplesser** [comment]
I quite like @jougs' alternative suggestion with respective files under `extra`.

**Comment by jougs** [comment]
In a video call with @heplesser today, we came to the conclusion that the requirements for building, testing and running NEST are sufficiently similar and lightweight that those can be in a single requirements file, while the ones for doc building are much different and considerably heavier. If we wanted to increase maintainability and reduce the risk of colliding with an infamous thermostat, we could thus get away with only

* `extras/conda-environment-nest-simulator.yml` defining the conda environment `nest-simulator` and using `extras/pyenv-requirements-nest.simulator.txt`
* `extras/conda-environment-nest-simulator-doc.yml` defining the conda environment `nest-simulator-doc` and using `extras/pyenv-requirements-nest.simulator-doc.txt`

**Comment by jougs** [comment]
@terhorstd, @jessica-mitchell, @sarakonradi, @steffengraber: Do you have any thoughts about the last proposal? I'd like to implement the doc-related changes already in the context of #1843 to save us from restructuring things yet again in the near future. Any objections? Thanks!

**Comment by heplesser** [comment]
@jougs I would consider to add one more environment: `...nest-simulator-server...`: `...nest-simulator...` + Flask & Co for those who want to run the server.

**Comment by jessica-mitchell** [comment]
This sounds good to me, thanks

**Comment by jougs** [comment]
The recent discussions here and in [today's open NEST developer video conference](https://github.com/nest/nest-simulator/wiki/2021-03-15-Open-NEST-Developer-Video-Conference) suggest that the situation cannot be easily fixed for everyone.

Conda seems to be used as an universal package manager (i.e. not just for `pip` installable Python modules) on all platforms from Linux to Mac and seems to be here to stay. At the same time, it is too demanding to maintain multiple dependency lists in different formats and make sure (and test) that they are all up to date. 

One possibly way out could be to define conda as the default path for installing dependencies for NEST and declare all other ways of installation unsupported. Users who want to install dependencies from their distribution's repository or from PyPI will have to find out about required packages themselves. 

If this idea is going to be implemented, it has to be clearly documented and all installation instructions have to be adapted accordingly (esp. all `apt-get` lines or similar have to be reviewed very carefully), so that building NEST will always work<sup>TM</sup> with conda.

Opinions? Volunteers?!

**Comment by steffengraber** [comment]
Here is the recipe for building the nest-simulator package on conda-forge:
https://github.com/conda-forge/nest-simulator-feedstock/blob/master/recipe/meta.yaml
Could be a starting point.
