### ISSUE TITLE
Reset network 

### ISSUE THREAD

**Issue by daphnecor** [nest/nest-simulator#1618]
**Motivation**
There are use cases with the nest library where different sets of inputs are compared or the network is trained by repeatedly changing the weights (e.g. by using STDP). Nest 2 allows this with the deprecated method ResetNetwork. It is not documented what the best practice is in this case. Nest 3 offers no replacement, thus requiring to reestablish the previous state manually.

**Proposal**
We think it is useful to implement a method that resets everything except some specified parameter *k*. It would be similar to the ResetKernel() method, but with the additional option to keep connections and some parameter(s) intact. 

**Example**
Synaptic plasticity enables the weights to change. Here, we want to reset all parameters except the connectivity (so here "w").

```python
ResetNetwork(except=[‘w’]) # Reset everything except the weight parameter
```

**Example code** 
This is how ResetNetwork() currently is being used. This method is called within a for loop ([entire script here](https://github.com/daphnecor/Transients/blob/master/LeakySimulator.py)).

```python
def simulate(self):

        nest.ResetNetwork() # forget all previous simulation data
        nest.SetKernelStatus({'time':0.}) # turn back the clock
        nest.Simulate(1000.) # simulate for a certain time period (ms)
        
        # etc….
```

**Additional Material**
[Mailing List thread](https://www.nest-simulator.org/mailinglist/hyperkitty/list/users@nest-simulator.org/thread/V4GTO2P77EVD4VDXIMZRC263L3IRRKP3/#V4GTO2P77EVD4VDXIMZRC263L3IRRKP3)

Daphne Cornelisse and Benedikt S. Vogler ( @BSVogler )

**Comment by heplesser** [comment]
@daphnecor @BSVogler The crucial problem about `ResetNetwork()` is to define precisely which state `ResetNetwork()` is supposed to reset to, and to implement this reasonably efficiently. Once this is precisely defined, one can also consider ways to retain (not reset) certain properties.

So, which "moving parts" do we have in a NEST simulation (not certain the list below is complete)?

1. State variables of neurons (eg membrane potential, synaptic currents or conductances, adaptation variables as in AdEx neurons, calcium concentrations for structural plasticity)
1. State variable of synapses, especially the synaptic weight, but also activity trace variables.
1. Spike buffers in neurons (both incoming and spike history).
1. Spike buffers in the NEST kernel.
1. Data buffers in recording devices.
1. Files connected to recording devices.
1. Random number generators.
1. The clock.

To which values should the state variables of neurons and synapses be reset? NEST2 resets the state variables to built-in defaults (neurons only). This works fine if all neurons have been created with default values for the membrane potential, but if the membrane potential had been randomized originally, then after NEST2-`ResetNetwork()`, all neurons would have the hard-coded default value of `V_m`.  One possible choice would be to reset to the value of the membrane potential upon the first call to `Simulate()` since the most recent `ResetKernel()`. But this would require storing a copy of all neuron state variables at this point to have them available for later resetting.

If we extend this to synapses, it would become more problematic, because we would need to store copies of all synaptic state variables at a huge cost in memory. When simulations include structural plasticity, synapses even come and go during a simulation and defining what to reset to in a general way would become even more difficult (we'd have to track which synapses existed at a certain point).

If I understand your use case correctly, you essentially want to reset neuron state, while keeping  the learned weights and drop spikes that are in transit. I think it might make more sense to do this explicitly, e.g., using

```python
nest.FlushSpikes()    # does not exist yet
neurons.set({'V_m': -75.0})   # add possibility to set synaptic currents/conductances, too
```

Instead of resetting simulation time, all devices in NEST have an `origin` parameter that allows you to shift the time relative to which `start` and `end` are interpreted.

**Comment by BSVogler** [comment]
Thank you for your response.
When storing the initial state it would ca. require twice the memory after initialization. Because the memory is not used for calculations it could be stored in a compressed format. The memory overhead could be made explicit by adding a `dump` and `load` method.

```python
create_net()
initial = nest.dump() # does not exist
nest.simulate()
weights = getweights()
nest.load(initial) # does not exist
setweights(weights) #assuming same topology
```
Dumping and loading can be used in other use cases

For this use case flushing the spikes with it other effects of activity like the calcium concentrations and activity traces (and maybe the buffers) would also work. To say something about the implementation of affected fields I would have to look at the implementation in nest first.

I welcome to see both methods implemented.

**Comment by jougs** [comment]
We had an extensive discussion about this during our [last hackathon](https://github.com/nest/nest-simulator/wiki/NEST-Hackathon-01.07---03.07-2020). The conclusion is that this is too general to fix and we will thus close it. Please feel free to create new feature requests for *concrete* functionality that is missing in order to support certain use cases. Please also make sure to provide a minimal example of what you want to achieve and mock functions for the things that you would want to see implemented.
