### ISSUE TITLE
PyNEST doesn't handle MPI or MUSIC induced changes in argv

### ISSUE THREAD

**Issue by mdjurfeldt** [nest/nest-simulator#163]
The MPI standard specifies that MPI_Init may change the contents of argc and argv. The mpich MPI implementation does this and MUSIC uses this mechanism to replace argc and argv according to the contents of the MUSIC specification file.

PyNEST translates the contents of sys.argv for the nest kernel, but it does not do the backwards translation needed after NEST startup, since args may have changed.

**Comment by apeyser** [comment]
Shouldn't we just move the MPI Init out of NEST and pass the communicator in? These problems occur because we keep on recreating interfaces that have already been written --- and it produces all those #ifdef's that cause problems.

I can fix it --- is this a theoretical problem, or is there an existing case where this causes a failure?

**Comment by apeyser** [comment]
Ah, I misread what was pointing to what. So you've already put in the code and have the pull request. 

Can you give me the case information for this? Has this broken something currently, are you worried about a future case, or is it general correctness?

**Comment by JanneM** [comment]
It breaks things when you have a PyNEST model that also uses command line arguments for its operation. You get all the MUSIC-related arguments mixed in with the ones meant for the model.

**Comment by mdjurfeldt** [comment]
This is responding to the problem Jan has. My change makes current
behaviour of pynest align with the behavior of a corresponding C++
application in that argv gets retrieved from the MUSIC configuration file.

At the same time this fixes a difference in behavior which pynest had
depending on MPI implementation:

Before my change, pynest under OpenMPI would get the users command line
arguments into sys.argv, but under mpich, the user would see something
different.

Now user command line arguments gets into argv also under mpich (not
tested).

Best regards,
Mikael

**Comment by mdjurfeldt** [comment]
On Fri, Nov 20, 2015 at 3:59 PM, Alexander Peyser <notifications@github.com>
wrote:

> Shouldn't we just move the MPI Init out of NEST and pass the communicator
> in?
>
This is a good idea.  However since this is a change in the API for the
user, I suggest that we do it in NEST3.

**Comment by apeyser** [comment]
Agreed that's a major revision for NEST 3. Thanks for the update on the root issue. Which issue # for Jan's problem? That way I can start to work backwards through my message backlog...

I'll look over your pull request next week.

**Comment by mdjurfeldt** [comment]
He hasn't reported it as an issue.

But what I did is rather straightforward:

1. Changed neststartup to use an extra level of indirection for argc and
argv.

2. Cleared argv and filled it from argv_bytes again after pynestkernels
call to neststartup

**Comment by JanneM** [comment]
I didn't report it here as it seemed a MUSIC problem to me. Should I open an issue on it, just to make it formal? Also, how do I share things like test cases? Check them in on a branch on my forked nest-simulator repo and refer to them fro here?

**Comment by apeyser** [comment]
@JanneM: MUSIC is also on github https://github.com/INCF/MUSIC, so you can put the issue there and reference from here or visa versa. That way when I forget about it, I can chase it down.

The goal of the tests would be ultimately integration, correct? Then you can do precisely what you suggest, since they'll be part of this repo eventually. There's also Gist (see at the headline of any github page) which will let you put up scripts and snippets to share that can be linked for things that aren't supposed to go into any repository, but need to be shared.

**Comment by apeyser** [comment]
Pull #164 merged. I'll close this issue and if someone would like to add test cases or any other documentation, just reopen.
