### ISSUE TITLE
Add junitparser to installation requirements

### ISSUE THREAD

**Issue by clinssen** [nest/nest-simulator#1652]
"Since the transition to the new test summary generator, the testsuite requires the Python ``junitparser`` package to be available." (@heplesser)

This should be added to https://github.com/nest/nest-simulator/blob/master/doc/installation/linux_install.rst, but perhaps also to other places, e.g. the requirements of the .deb packages?

What should happen in case junitparser cannot be found: fail tests, or only issue a warning?

Via https://github.com/nest/nest-simulator/pull/1578#issuecomment-647108209

**Comment by heplesser** [comment]
@sarakonradi @clinssen  Looking at the description of dependencies, I find them quite complex, explaining what you need and why (or not). Doesn't that confuse users? Wouldn't it be simpler to just list the full set of requirements, since almost everyone anyways will want the full package? Possibly mark one or the other as optional? We also need to point out that Python is needed to run the testsuite ...
