### ISSUE TITLE
ImportError: libpython3.7m.so.1.0: cannot open shared object file: No such file

### ISSUE THREAD

**Issue by daiminghuan** [nest/nest-simulator#1677]
**Describe the bug**
 I create new envs which contains python3.8 and nest ,but when I  type python and import nest, the error is as above , please help me, thank you!
**To Reproduce**
1. I installed miniconda3
2. in base env, i use command : "conda create --name nest -c conda-forge nest-simulator ". then :"conda activate nest "and "python" and "import nest",then the error as below:
3. Command to run ：in base env, i use command : "conda create --name nest -c conda-forge nest-simulator ". then :"conda activate nest "and "python" and "import nest",then the error as below:
4. How to see error

**Expected behavior**
A clear and concise description of what you expected to happen. ：Should be an interactive interface

**Screenshots**

> 
![image](https://user-images.githubusercontent.com/51187217/86876817-17268e00-c118-11ea-9bc9-510528da71b7.png)

> 

**Desktop/Environment (please complete the following information):**
 - OS: [Ubuntu-20.04]
 - Browser: [if applicable, e.g. chrome, safari]
 - Shell: [bash]
 - Python-Version: [ in base env is Python 3.7 ，but when i installing nest-simulator in nest env, Python3.8 is automatically installed]
 - NEST-Version: [nest-2.20]
 - Installation: [ conda packet,without MPI, ...]
   (in case you compiled the source code manually, provide the
    "Installation Summary" that you see at the end of the 
    cmake step)

**Additional context**

**Comment by terhorstd** [comment]
This is obviously a misconfiguration in your environment, since the error states **Python 3.7** not 3.8 as you would expect.
For a more detailed answer, it would help, if you fill the other sections of the issue template, especially: how can we reproduce your error, which environment are you running in (ubuntu? mac? conda? nest version?...)

**Comment by daiminghuan** [comment]
> This is obviously a misconfiguration in your environment, since the error states **Python 3.7** not 3.8 as you would expect.
> For a more detailed answer, it would help, if you fill the other sections of the issue template, especially: how can we reproduce your error, which environment are you running in (ubuntu? mac? conda? nest version?...)
thank you! 
My operating system is ubuntu20.04, I use conda to install nest, when i installed nest ,then create a new env, and then I activate the new environment, in the new environment, I use the conda list command to view the version of python, which is 3.8, 
After that is what I said above. 
By the way, the python version in the base environment is 3.7.

**Comment by terhorstd** [comment]
It looks like installing nest first, and then creating a new environment with a different python version might cause the problem. This is a well known thing for conda and is not very obvious at first. If something is not found in an environment, search falls back to the base environment. That is fine, as long as packages in base and sub environment are compatible. It is very fragile however, since at some point you can not change/update anything in base, because all sub envrionments will break. Your issue seems to be exactly this dependency conflict. NEST in your base env is installed for Python3.7, your new environment uses Python3.8 and does not have a `nest` module. Falling back to base, it's kind-of there, but completely mixed up with Python versions and library dependencies.

The general approach would be that your base environment should be as empty as possible in order to not cause conflicts with other environments. Always install packages only in the new environments (don't worry about duplicates, conda will link the packages if they are used in multiple environments, and not produce disk eating copies).

In this case:
uninstall packages from the base environment, create and activate new environment, reinstall packages there.

In the general case:
Get a good overview which packages are installed where. You can use `conda env export -n base` and `conda env export -n yournestenv` (replacing the yournestenv name with what you chose). Make sure each environment contains all dependencies. One way to make this obvious would be to reduce conda stack to `0` (conda docs [here](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#nested-activation)), and/or to a certain degree by not auto-activating the base environment (conda docs [here](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#conda-init)). Then packages from base do not 'leak' into your new environments. Note however, that packages from your system will usually also be available in your conda env and might cause similar conflicts.

**Comment by terhorstd** [comment]
@sarakonradi, maybe we can add parts of this to the documentation. The conda docs may not be specific enough to understand these implications, so a page or paragraph for the case described here (and maybe also #1687) might help to avoid this type of problem.

**Comment by daiminghuan** [comment]
> It looks like installing nest first, and then creating a new environment with a different python version might cause the problem. This is a well known thing for conda and is not very obvious at first. If something is not found in an environment, search falls back to the base environment. That is fine, as long as packages in base and sub environment are compatible. It is very fragile however, since at some point you can not change/update anything in base, because all sub envrionments will break. Your issue seems to be exactly this dependency conflict. NEST in your base env is installed for Python3.7, your new environment uses Python3.8 and does not have a `nest` module. Falling back to base, it's kind-of there, but completely mixed up with Python versions and library dependencies.
> 
> The general approach would be that your base environment should be as empty as possible in order to not cause conflicts with other environments. Always install packages only in the new environments (don't worry about duplicates, conda will link the packages if they are used in multiple environments, and not produce disk eating copies).
> 
> In this case:
> uninstall packages from the base environment, create and activate new environment, reinstall packages there.
> 
> In the general case:
> Get a good overview which packages are installed where. You can use `conda env export -n base` and `conda env export -n yournestenv` (replacing the yournestenv name with what you chose). Make sure each environment contains all dependencies. One way to make this obvious would be to reduce conda stack to `0` (conda docs [here](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#nested-activation)), and/or to a certain degree by not auto-activating the base environment (conda docs [here](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#conda-init)). Then packages from base do not 'leak' into your new environments. Note however, that packages from your system will usually also be available in your conda env and might cause similar conflicts.
thank you ! I get it
