### ISSUE TITLE
Make installcheck fails on SLI execution

### ISSUE THREAD

**Issue by francesshei** [nest/nest-simulator#1722]
Hello everyone, 
I'm having troubles installing NEST 2.18.0 on top of a previous version of NEST (2.12.0). 
I know it should be better to proceed with a fresh install, but I have to substitute the NEST version inside the Human Brain Project's Neurorobotics Platform (NRP): since the NRP is a collection of different software components I didn't want to delete its folder containing NEST to avoid future missing directories issues.

Here are the steps that I followed: 
- ``` cmake -DCMAKE_INSTALL_PREFIX:PATH=$HBP/nest-simulator ~/NEST/nest-simulator-2.18.0``` (where ```$HBP\nest-simulator``` is the folder containing the old NEST and ```~/NEST/nest-simulator-2.18.0``` is the folder where I unpacked the tarball)
- I added the line ```source /home/nrp/Documents/NRP/nest-simulator/bin/nest_vars.sh-``` to the ~/.bashrc
- ``` make```
- ``` make install```

So far everything seemed to work, but running ```make installcheck ``` gave an error: 
``` Scanning dependencies of target installcheck
Execute NEST's testsuite....
 Phase 1: Testing if SLI can execute scripts and report errors
-------------------------------------------------------------
  Running test 'selftests/test_pass.sli'... Running  mpirun -np 1 /home/nrp/Documents/NRP/nest-simulator/bin/nest /home/nrp/Documents/NRP/nest-simulator/share/doc/nest/selftests/test_pass.sli
/home/nrp/Documents/NRP/nest-simulator/bin/nest: symbol lookup error: /home/nrp/Documents/NRP/nest-simulator/bin/nest: undefined symbol: _ZN4nest4Node15send_test_eventERS0_ljb

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 10927 RUNNING AT realnet-Precision-T3610
=   EXIT CODE: 127
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
```

If I start Python from terminal and give the command ``` >>> import nest``` the output is:
```[INFO] [2020.8.14 9:54:57 /home/nrp/Documents/NRP/nest-simulator/nestkernel/rng_manager.cpp:226 @ Network::create_rngs_] : Creating default RNGs
[INFO] [2020.8.14 9:54:57 /home/nrp/Documents/NRP/nest-simulator/nestkernel/rng_manager.cpp:221 @ Network::create_rngs_] : Deleting existing random number generators
[INFO] [2020.8.14 9:54:57 /home/nrp/Documents/NRP/nest-simulator/nestkernel/rng_manager.cpp:226 @ Network::create_rngs_] : Creating default RNGs
[INFO] [2020.8.14 9:54:57 /home/nrp/Documents/NRP/nest-simulator/nestkernel/rng_manager.cpp:272 @ Network::create_grng_] : Creating new default global RNG
python: /home/nrp/Documents/NRP/nest-simulator/sli/slistartup.cc:266: SLIStartup::SLIStartup(int, char**): Assertion `std::strlen( argv[ 0 ] ) > 0' failed.
Aborted (core dumped)
```

Ubuntu-18.04
Python 2.7

I will attach the content archived in ```~/reports```, as  ```~/reports/nest.yqcHi``` is empty
[reports.zip](https://github.com/nest/nest-simulator/files/5073577/reports.zip)

**Comment by heplesser** [comment]
@jougs Could you take a look a this?

**Comment by jougs** [comment]
@francesshei: I am afraid this is the kind of things you have to deal with if you mix old and new installations... So the short answer is: don't! Always do fresh installs.

My somewhat longer suggestion is to at least move the old installation out of the way temporarily and make sure no environment variable (from the top of my head `PATH`, `LD_LIBRARY_PATH`, `NEST_DOC_DIR`, `NEST_DATA_DIR` and `NEST_INSTALL_DIR` might be problematic, but there may be more) refers to the old source or installation directories.

In particular, you must not `source` the `nest_vars.sh` of an old version before installing a new one (as you did). That has a high potential to mess things up. A lot of things have changed in the 3 years since 2.12.0.

You might also want to check the resulting executable (`<nest_install_dir>/bin/nest`) and Python module (`<nest_install_dir>/lib/python<python_version>/site-packages/nest/pynestkernel.so`) for traces of the old installation (using `ldd`). Those must not be in there.

May I also ask why you don't use the latest 2.20.0 release and instead go again for an outdated version (2.18.0)?

**Comment by francesshei** [comment]
Thanks @jougs for the suggestions! 
Some environment variables that you mentioned were indeed referring to a system-wide NEST installation so that is something to fix.
The ```nest_vars.sh``` were not supposed to be the old ones as I added the path the ```cmake``` output was telling me, but I might have misunderstood that command. 
I can't look for old installation trace as I'm back with the original NRP: since the NEST unsuccessful installation was breaking the platform, I looked the repo documentation and found a way to revert to the original version: 
``` 
cd $HBP 
rm -rf nest-simulator
git clone https://bitbucket.org/hbpneurorobotics/nest-simulator.git
```
where $HBP is the var containing the NRP folder directory.
After cloning their modified forked NEST, one can rebuild the platform with one of their script. 

This, however, suggest me that I might as well go for your short answer and try a fresh install. 

I'm using the older NEST 2.18.0 because I have to use a custom cerebellar module that is not compatible with the 2.20.0 yet

**Comment by jougs** [comment]
> The `nest_vars.sh` were not supposed to be the old ones as I added the path the `cmake` output was telling me, but I might have misunderstood that command.

Usually one only sets `nest_vars.sh` *after* the installation to make the `nest` executable and Python module available without having to type their full path. Because you want to install over an existing installation, your old *existing* installation is in the same directory as the *new* one will be in. This can lead to old versions of libraries (and their symbols) being picked up during compilation. The libraries are then overwritten and the symbols don't work with the new libraries. This could explain the erros you get.

> I'm using the older NEST 2.18.0 because I have to use a custom cerebellar module that is not compatible with the 2.20.0 yet

Fair enough.

---

I'm closing this one now, as the problems are most likely not actually existing with our (only) supported way of installation, namely an installation into a fresh directory.
