### ISSUE TITLE
Spelling question: "postsynaptic" or "post-synaptic"?

### ISSUE THREAD

**Issue by clinssen** [nest/nest-simulator#1797]
The jury seems to be divided:

```bash
nest-simulator $ grep -r post-synaptic | wc -l
128
nest-simulator $ grep -r postsynaptic | wc -l
194
```

Numbers for NESTML are comparably split. I would suggest naming this "postsynaptic" consistently (also for NESTML).

cc @abigailm @sarakonradi

**Comment by jd41** [comment]
This is far from the only inconsistent spelling and naming within the NEST documentation, and I think for efficiency reasons they should be discussed and solved once rather than once per word.^1

For example, one particular thing that caused comprehension problems for me when I started to learn NEST was that the documentation freely switches between "status dictionary", "parameter dictionary", "status", "parameters" between and within pages without ever confirming explicitly that this means the same thing. @sarakonradi told me that such problems (terms whose precise definition wasn't clear) also came up in benchmarking meetings.

Part of the glossary work I am doing with @sarakonradi @steffengraber @terhorstd was getting a list of terms which will also be useful to agree to one variant for such words. Fixing American vs British English is something that a semi-automated tool can and should do, rather than doing it piecewise in GH issues.

I propose renaming the issue to "Inconsistent word/phrase choices in the NEST documentation".

(sub) ^1 post-synaptic vs postsynaptic doesn't seem like the most important thing to me, as it's just stylistic.

**Comment by sarakonradi** [comment]
I agree with using "postsynaptic" consistently. 

Not sure if I would rename the issue, as "Inconsistent word/phrase choices in the NEST documentation" may be too broad and impractical to address. I would propose updating the spelling of "postsynaptic" for now and discussing other terms in separate issues.
