### ISSUE TITLE
NEST 2.4 random number information available in docs

### ISSUE THREAD

**Issue by Helveg** [nest/nest-simulator#1816]
**Describe the flaw**
It seems that the documentation [here](https://nest-simulator.readthedocs.io/en/stable/guides/random_numbers.html) is quite old. Is everything there still up to date? If so the NEST 2.4 version number that appears a few times is quite confusing. There's also an unformatted code block [here](https://nest-simulator.readthedocs.io/en/stable/guides/random_numbers.html#basics-of-parallel-simulation-in-nest). Are the examples still how one should go about RNGs in NEST 2.20?

**Comment by stinebuu** [comment]
@hakonsbm @jougs @heplesser Will this be fixed in #1549?

@sarakonradi @terhorstd What is our policy on fixing documentation for different versions, should this be fixed for NEST 2.20.1? Because #1549 is a NEST 3.0 feature.

**Comment by hakonsbm** [comment]
@stinebuu Yes. Random number generation is being rewritten, so all relevant documentation will be updated.

**Comment by heplesser** [comment]
The material on that page is mostly still correct, even if old, but some of the presentation is non-sensical in today's context. Since it will still be a few months before NEST3 will be officially released, I think an update would not hurt (but it should not delay 2.20.1 any further!). 

I would suggest changes as follows:
- Rewrite the "Changes in ... NEST 2.4" section without any reference to NEST 2.2, just summarise features available today briefly
- Update the "Examples" section. You can probably borrow examples from the randomizing section of the "NEST by Example" notebook in the docs.
- Fix formatting, especially of code blocks, where necessary.

**Comment by heplesser** [comment]
Closing now that #1816 is merged.
