### ISSUE TITLE
InvalidNodeCollection after reset

### ISSUE THREAD

**Issue by BSVogler** [nest/nest-simulator#1821]
In some use-cases I want to keep the access via variable to some nodes even after the net is reset and reconfigured. By using the ids this was possible before. Now using a node collection it will crash and requires the recreation by storing the ids redundantly.

```python3
import nest
neuron = nest.Create("iaf_psc_alpha")
nc = nest.NodeCollection([1])
ids = nc.tolist()
#reset
nest.ResetKernel()
#create neuron with id 1 again
neuron = nest.Create("iaf_psc_alpha")

#printing the nc will show that this refers to id 1
print(nc) #NodeCollection(metadata=None, model=iaf_psc_alpha, size=1, first=1)
nc.get() #now any access via the NodeCollection will crash with InvalidNodeCollection
#now we update the reference by recreating the node collection
nc = nest.NodeCollection(ids)
#printing indicates no change, but now it is 'repaired'
print(nc) #NodeCollection(metadata=None, model=iaf_psc_alpha, size=1, first=1)
nc.get() #now it will work again
```

I don't know about the internals of the NodeCollection. Wouldn't it be easier to add something like `nc.reinstante()` or even better do this automatically when this is accessed after a reset?

**Comment by hakonsbm** [comment]
@BSVogler It's a bit unclear to me what you want to do here. If you just want to use the status of the nodes, you can save the dict from `nc.get()` in a variable before calling `ResetKernel()`.

When calling `ResetKernel()`, all created nodes are destroyed. So all node IDs in a NodeCollection, and therefore the NodeCollection itself, becomes invalid. This is equivalent to using 2.20, where doing a `GetStatus()` on node IDs after calling `ResetKernel()` will lead to an `UnknownNode` error.

If reinstating the nodes of a NodeCollection after resetting is the goal here, one could save the status before resetting, then create a new NodeCollection with the same specifications.

Some mechanism to reinstate the nodes from an invalid NodeCollection could be implemented. However, then the status of all nodes would have to be saved in case the user would want to reinstate them. Saving the status of all nodes all the time would cause a big overhead, especially for larger networks.

**Comment by BSVogler** [comment]
I think I missed adding the crucial step where the nodes are recreated after the reset. The problem is that the node collection then refers to existing node ids but calling get will cause a crash. I think I will need to look again at the minimum example.

**Comment by hakonsbm** [comment]
If you create a NodeCollection, then `ResetKernel`, the NodeCollection is invalidated and can no longer be used, even if the node IDs it contains are recreated. This is because we want to avoid errors where metadata etc. of the new node IDs do not correspond to the old node IDs. And, as you demonstrate in the example, it's easy to recreate the NodeCollection again with `NodeCollection(ids)`.

However, perhaps printing the nodes should give an indication that the NodeCollection is invalid. Would that remove the confusion and resolve this issue, @BSVogler?

**Comment by BSVogler** [comment]
It is only easy here because the example here is a minimal example. I have code with a lot of node collections which all need to be stored twice to refresh them. But it bothers me more that you cannot upgrade lists of ids with node collections when upgrading from nest 2 to 3. Currently NodeCollections are a not a superset of the functionality.

Why not use both? A method to refresh the metadata and an indicator in the print statement?

**Comment by stinebuu** [comment]
@BSVogler Are you still having problems with this?

**Comment by BSVogler** [comment]
@stinebuu This is about some enhancement about the implementation in nest 3, so this issue persists.

**Comment by heplesser** [comment]
> I missed adding the crucial step where the nodes are recreated after the reset. The problem is that the node collection then refers to existing node ids but calling get will cause a crash.

The proper way to recreate nodes after a `ResetKernel` is through calling `Create()`, which will give you a new node collection to work on. Keeping node collections viable across a `ResetKernel` would be extremely difficult, because the meaning of node ids represented by a `NodeCollection` depends on the details of the `Create()` calls executed before and after the `ResetKernel`. Only if they are identical would a retained or reconstructed `NodeCollection` be meaningful. Since the NEST kernel has no way of controlling this, we must invalidate existing `NodeCollections` on `ResetKernel`. I would also advise against converting node collections to lists of IDs to be able to reconstruct them later, as you show in your example above. 

The current implementation ensures robust behaviour and we do not plan to change it. I have created #1952 to remind us to improve the error message for invalid node connections. I will close this issue for now.

I this is related to the EBRAINS NRP and and you would like support to converting NEST2-based code to NEST3, please create an EBRAINS support request.
