### ISSUE TITLE
One-neuron network calls synapse constructor thousands of times

### ISSUE THREAD

**Issue by clinssen** [nest/nest-simulator#1835]
Creating a network with two neurons and one synapse calls the synapse constructor slightly over 1024 times, and the copy constructor another just-over-1024 times:

```python
import nest

PRE = nest.Create("iaf_cond_exp", 1)
POST = nest.Create("iaf_cond_exp", 1)

nest.Connect(PRE, POST, conn_spec={"rule": "one_to_one"}, syn_spec={"synapse_model": 'stdp_synapse'})
```

yields

```
STDP constructor called
STDP copy constructor called
STDP constructor called
STDP copy constructor called
STDP constructor called
STDP copy constructor called

              -- N E S T --
  Copyright (C) 2004 The NEST Initiative

 Version: master@211a6bd00
 Built: Nov  6 2020 12:25:53

 This program is provided AS IS and comes with
 NO WARRANTY. See the file LICENSE for details.

 Problems or suggestions?
   Visit https://www.nest-simulator.org

 Type 'nest.help()' to find out more about NEST.


Nov 09 09:40:13 ConnectionManager [Warning]: 
    New connections created, connection descriptors previously obtained using 
    'GetConnections' are now invalid.
STDP copy constructor called
STDP constructor called
... 1024 times ...
STDP constructor called
STDP copy constructor called
... 1024 times ...
STDP copy constructor called
```

The number 1024 is of course conspicuous as a power of two. Could a connbuilder expert take a look at this and clarify whether this is expected behaviour?

Thanks to @zbarni for reporting this!

**Comment by heplesser** [comment]
@hakonsbm Could this somehow be related to the 2^10=1024 block size of the `BlockVector`? If adding the first element to a connector adds a block (because the connector and thus BV is only created when the first synapse of a given type is created), and this would trigger construction of all elements in that block, that could explain it. One way to test would be to change the `block_size_shift` and see if the number of calls changes correspondingly.

**Comment by hakonsbm** [comment]
Reducing the block size reduced the number of calls to the constructor, and `gdb` confirmed that it's the `BlockVector` causing this. Is it causing problems with some synapse models?

**Comment by clinssen** [comment]
That's great, thanks for clearing that up. I don't think it caused any errors, just confusion. The only question would be whether this merits documentation somewhere.

**Comment by heplesser** [comment]
I also wonder why this happens. I suspect that the construction of the first block in the `BlockVector` [which happens here](https://github.com/nest/nest-simulator/blob/b08590af6d721ab66f8a72dcde053cff00d56512/libnestutil/block_vector.h#L312) actually constructs every element in the block. And I fear that the same happens for every block that is added to the `BlockVector`, so that each synapse is in a way constructed twice: once by default when the `BlockVector` is constructed, and once then the actual synapse is constructed during network construction.

This may affect performance. I wonder if we could avoid the element construction at time of vector construction by adding, for each new block, an empty vector in which we *reserve* `max_block_size` elements.

**Comment by hakonsbm** [comment]
@heplesser That's right. When a new block in the `BlockVector` is created, all elements in that block are default constructed. Then, when adding an element to the `BlockVector`, it is copy constructed into the space of the already created element in the block.

I've done some simple benchmarks comparing filling a `BlockVector` against filling an `std::vector` with a reserved number of elements. It looks like reserving the memory and filling an `std::vector` is about 40 % faster than filling a `BlockVector`, when filling them with 10 000 000 objects. However, filling the `BlockVector` only takes 3.1 seconds.

Anyway, I can restructure the `BlockVector` to reserve instead of default fill each block and see what the actual change is when connecting.

**Comment by hakonsbm** [comment]
Restructuring the `BlockVector` to reserve instead of default filling each block proved more complicated than I first thought. I have instead done some profiling of the connection step in `hpc_benchmark.sli`. I used scale=1 which results in 126.6 million connections, and 123609 blocks. The profiling shows that adding new connections to the `BlockVector` (including allocation of new blocks) takes about 5 % of the connection time. Assuming a connection time of 30 seconds, this amounts to only 1.5 second, so there is not much to gain there.

**Comment by clinssen** [comment]
Closing the issue as: expected behaviour; not an issue.
