### ISSUE TITLE
Use squash and merge for PRs

### ISSUE THREAD

**Issue by Silmathoron** [nest/nest-simulator#1856]
GitHub now handles authorship correctly with "Squash and merge" (including potential co-authors), meaning that we could now use this to merge PRs and have only one commit per PR, making this history a lot easier to browse.

**Comment by terhorstd** [comment]
This is not an issue with the code and this should probably be discussed on the list or in the VC. I have put it on the [agenda](https://github.com/nest/nest-simulator/wiki/2020-12-07-Open-NEST-Developer-Video-Conference) for monday.

**Comment by terhorstd** [comment]
Thanks for bringing this up and our comprehensive discussion in yesterday's [meeting](https://github.com/nest/nest-simulator/wiki/2020-12-07-Open-NEST-Developer-Video-Conference).

For reference:
The joint conclusion was to squash some PRs where it makes sense and is requested by the developer.

Since Github handles force-pushes to PR branches gracefully, the possibility of the developer squashing upstream (before or during the PR) still leaves more sensible options open. In general, squashing different steps of the PR into a single commit may obscure bug-finding by bisection, so it is not advised for larger/non-trivial change sets.
