### ISSUE TITLE
Unify nomenclature of synapse names

### ISSUE THREAD

**Issue by clinssen** [nest/nest-simulator#1930]
Neuron models have a consistent naming: the class name (for example, `gif_cond_exp`) is the same as the file name (`gif_cond_exp.{h,cpp}"`) and the name under which it is registered in the `ModelsModule` (`gif_cond_exp`).

For synapses, this is, however, not the case. For example, the class might be called `STDPConnection`, the filename is `stdp_connection.{h,cpp}` and the user-facing name it is given in `ModelsModule` is `stdp_synapse`.

The suggestion is to rename the classes and file names to the name under which the model is registered. Mostly, this will end in "_synapse". Only the "rate" and "diffusion" connections will remain with suffix "_connection". Note that this means that class names will not be in camel case (as is currently already the case for neuron/node models).

As a secondary issue, the keyword `synapses` in the call `nest.Models(mtype, ...)` should be changed to `connections`.

Pertaining documentation and in particular the 2🠒3 transition guide (see also #1929) has to be adapted accordingly.

**Comment by jougs** [comment]
@heplesser: do you have an opinion about this? In my opinion, this should be implemented as quickly as possible.

**Comment by heplesser** [comment]
@jougs @clinssen This seems very sensible. I believe the `_connection` part of class and thus file names came from a technical/developer point of view, while the `_synapse` name exported to the user interface reflects the user perspective. The inconsistency is confusing. Even though this will not affect the user interface because only class and source file names are modified, I would want to include this in the NEST3 milestone.

Concerning changing `mtype='synapses'` to `mtype='connections'`: This seems a bit contradictory, since we change to "synapse" everywhere else now. So I would suggest to either keep "synapses" or go all the way to graph terminology and complement "nodes" with "edges". In any case, I would (at least silently) accept the singular ('node', 'synapse'/'edge') as well. And I think there are some typos in the docstring for the mtype parameter.

**Important**: Any PR for this should build on #1549 and only be merged after that PR, otherwise I fear chaos.

**Comment by heplesser** [comment]
@abigailm Do you have any comments?

**Comment by jougs** [comment]
I think there's two aspects to this, which we probably could easily separate:
1. renaming the C++ classes for internal consistency reasons and to make the help extraction more automatic
    in my view, this should be done asap
2. the user-facing `Models` command; after more thinking, my proposal here would be a full-on refactoring: 
    - rename the `mtype` keyword to `model_type`
    - accept `neurons`, `devices`, `stimulators`, `recorders`, `synapses` or a similar selection of terms
    - do the filtering internally - this command is likely only used interactively and thus performance is not critical

**Comment by jougs** [comment]
This PR is an important step in making the fixes to the PyNEST help system proposed in #1926 more useful by also allowing to display the help for synapse models. More background information about this can be found in [this comment](https://github.com/nest/nest-simulator/pull/1926#issuecomment-780482157).

**Comment by clinssen** [comment]
Now that we are renaming a vast number of C++ classes anyway, do we want to go to a CamelCase format for class names, and an underscore_format for file names and model names?

Most synapse classes are already in this format, but neuron classes are typically not, for example, compare:
```C++
register_connection_model< StaticConnectionHomW >( "static_synapse_hom_w" );
```
and
```C++
kernel().model_manager.register_node_model< hh_cond_beta_gap_traub >( "hh_cond_beta_gap_traub" );
```
In this example, ``hh_cond_beta_gap_traub`` would be renamed to ``HHCondBetaGapTraub``.

**Comment by jougs** [comment]
@clinssen: No!

In general, I totally agree with you that class names should be CamelCase. But not here. 

The whole point of this issue is that we *always* want
* the name, a model is registered with
* the name of the class implementing it, and
* the file name under which this implementation is stored

to be exactly the same. The reason is that that makes the generation of model documentation easier and we thus always know which file to present when the user calls for `help()`.

So, what we want here is that the files for a model `model_name` are called `model_name.{h,cpp}` and the model is registered under the name `model_name`. As you point out, this is already the case for neurons, but should also be done for synapses.

**Comment by clinssen** [comment]
@heplesser: do you mean that this issue is effectively blocked until #1549 is merged?

**Comment by heplesser** [comment]
I removed my comment concerning #1549. @jougs assured me that Git will be smart enough to sort things out ;).

**Comment by heplesser** [comment]
This is part of the NEST 3.0 milestone because it affects documentation rendering.
