### ISSUE TITLE
PyPI serves a namesquatted NEST package

### ISSUE THREAD

**Issue by Helveg** [nest/nest-simulator#2007]
Although install instructions don't mention nest is pip installable, `nest` is being name squatted on PyPI and poses a security risk to NEST users (pip install nest > import nest > You've executed arbitrary Python code). Once liberated we could upload basic wheels (for example whatever `cmake` without flags produces).

Since this package's last release is from 2012, is defunct and its README says "UNKNOWN" I don't think there'll be any issue to kick out the squatter following PEP541 for being either an [invalid project](https://www.python.org/dev/peps/pep-0541/#invalid-projects) (it has no functionality) or [abandoned project](https://www.python.org/dev/peps/pep-0541/#removal-of-an-abandoned-project).

If #1959 is merged it might be a good opportunity to secure this package name since I aligned NEST's package name from `PyNEST` to `nest` because:

* The name `PyNEST` has never actually been relevant before as CMake has never installed package metadata before this PR.
* PEP8 specifies package names need to be lowercase.
* It's already always been `import nest`, not `import pynest`

What we'd need to do is:
* Contact the owner of https://pypi.org/project/nest/
* If they're unresponsive open a request to transfer, see [full procedure](https://www.python.org/dev/peps/pep-0541/#how-to-request-a-name-transfer)

**Comment by Helveg** [comment]
@clinssen Have you had any success contacting the owner or started the procedure with the Python Packaging Authority yet?

**Comment by clinssen** [comment]
Hi Robin! We actually discussed this during a hackathon session today. Our conclusion was that, with a growing NEST ecosystem, we would instead prefer to stay consistent in the naming, and register nest-simulator, nestml, nest-desktop, in general, nest-*.

Personally I don't have a strong opinion on grabbing the "nest" entry on PyPI, but in any case, if we have an entry there it should be somehow functional (otherwise we'd just have another defunct package). So that means that we'd have to set things up so ``pip install nest-simulator`` would actually install NEST. I'm not sure if it would be a reasonable approach to write a ``setup.py`` script that grabs the latest release tarball, and attempts to run cmake/make/make install in a user-local directory (that is to say, if that wouldn't be a kludge).

Do you have any suggestions for what we should expect to happen when someone does a ``pip install nest[-simulator]``?

**Comment by Helveg** [comment]
Well if #1959 is merged you could have a CI pipeline that uploads the source tree as a source distribution and modify `setup.py` so that it CMakes it and installs it to the Python interpreter of the `pip` that invoked the install command. You could even leverage pips [`install-option`](https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-install-option) to allow to set CMake flags.

**Comment by Helveg** [comment]
🎉 #2073 

we can upload the 3.0 release to `nest-simulator` with this

**Comment by heplesser** [comment]
Closing.
