### ISSUE TITLE
Calling ``nest.Connect()`` modifies ``syn_spec`` dictionary when given

### ISSUE THREAD

**Issue by clinssen** [nest/nest-simulator#2069]
If ``syn_spec`` is a Python dictionary, calling ``nest.Connect(pre, post, syn_spec=syn_spec)`` modifies the ``syn_spec`` dictionary. This could lead to confusion and unexpected results.

This occurs in the function:
https://github.com/nest/nest-simulator/blob/2080ce33d9578df092ad296a3a49c0ab69d00742/pynest/nest/lib/hl_api_connection_helpers.py#L58

Adding a call to ``copy.deepcopy(syn_spec)`` at the top of this function would surely resolve this, but do we consider this a clean enough solution?

**Comment by heplesser** [comment]
deepcopy() sounds reasonable to me.

**Comment by heplesser** [comment]
Are there any other cases where the PyNEST API modifies dictionaries? It shouldn't do that.

**Comment by stinebuu** [comment]
@clinssen Do you want to create a fix for this, or should someone from the PyNEST Team handle this?

**Comment by clinssen** [comment]
I'd be happy to work on this, but planning-wise it would be after the NEST Conference. No complaints if there are any volunteers before that time! 

Suggest to (self-)assign somebody to this issue when work on a fix is begun.

**Comment by stinebuu** [comment]
@clinssen @heplesser using `deepcopy()` leads to problems when connecting with syn_spec's containing `nest.Paramater` or a `CollocatedSynapse`. The problem arises because of our datums, it seems to me that is not straight forward to copy them. We need to add a `__reduce__` function to the Cython class, but I am not able to do it correctly.

The `syn_spec` is currently only changed when we give it a list/tuple for one of the synapse parameters. Using `copy()` instead of `deepcopy()` seems to work at the moment. Do you think this is a good enough solution, or do you think it is better with the deep copy? If so, I think someone other than me needs to have a look.
