### ISSUE TITLE
Review and correct Arbor backend test

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#2151]
The Arbor backend test fails currently as shown here: https://github.com/nest/nest-simulator/runs/3510427486?check_suite_focus=true#step:16:8270. Preliminary investigation indicates that MPI communication happens, but returns incorrect results at least for `min_delay`, typically 0. This might be due to a mismatch in datatype.

This issue was discovered in connection with #2148; during the review of #2076, the test was actually never run for a combination of reasons.

The following questions occurred to me in this context:
1. Since we do not test against Arbor, but a Python script imitating Arbor, how certain are we that our script correctly mimics Arbor? Should we at least be explicit about the Arbor version we target here?
2. Building the Arbor backend has no other requirements than building NEST with MPI, so I suggest to include the Arbor backend test in the FULL build instead of having a separate target—otherwise we run ≈1200 tests twice just to run one additional test.
3. I am not happy with the `mpiutil[_impl].h` files: they provide small code only needed for the Arbor backend and I think it would be better to include that code directly in the Arbor backend files. At least the file names should make clear that these files are related to the Arbor backend.

**Comment by hakonsbm** [comment]
1. The version that our script mimics is not an official version of Arbor, but a branch that implements receiving spikes from NEST (https://github.com/apeyser/arbor/tree/feature/nestio). That branch is based on Arbor master a few commits after version 0.2.2, from 2019.
2. The FULL build includes MUSIC, but NEST cannot be compiled with both MUSIC and the Arbor backend because they are mutually exclusive.
3. I agree that they should be included in the Arbor backend files.

**Comment by heplesser** [comment]
> * The version that our script mimics is not an official version of Arbor, but a branch that implements receiving spikes from NEST (https://github.com/apeyser/arbor/tree/feature/nestio). That branch is based on Arbor master a few commits after version 0.2.2, from 2019.

That should be made very clear in the test, and in the arbor backend code (which seems to lack any documentation, both user and developer doc). I'd suggest to give the precise hash of the Arbor version that this is based on.
> * The FULL build includes MUSIC, but NEST cannot be compiled with both MUSIC and the Arbor backend because they are mutually exclusive.
That is unfortunate. I guess it is related to control over the MPI communicator?

**Comment by hakonsbm** [comment]
> I'd suggest to give the precise hash of the Arbor version that this is based on.

Will do.

> I guess it is related to control over the MPI communicator?

That is my guess as well. @jougs may know more about it.

**Comment by jougs** [comment]
I totally agree with the assessment so far, but  want to add some additional points: To the best of my knowledge no one ever used the Arbor *recording* backend (I'd really like that term used, as there are also *stimulation* backends and this is not one of them) and it never really left the proof of concept phase. Considering the ancient version of Arbor against which we build, the code is unmaintained and probably outdated on *both* sides of the interface.

My proposal is (and has already been two years ago) that we put the Arbor recording backend into an extension module in its own repository with its own CI setup and a README that explains requirements and how things should be built and used. If the code starts rotting there due to missing ownership, the code would at least not cause work for any of us and anyone interested in picking it up again would be in a much better situation, as there would be less clutter around the actual thing they really want.

@suku248, @w-klijn, @bcumming, @halfflat might also have an opinion or thoughts about this

**Comment by heplesser** [comment]
@jougs I agree with your analysis and suggestion. To move on (and avoid shipping "unstable" code with NEST 3.1), I suggest that we remove the Arbor backend including tests from NEST master immediately. Once the new module system is ready, we prepare an extension module with the Arbor backend. That could then even have a test setup including a real Arbor. 

@espenhgn might also be interested in this discussion.

**Comment by w-klijn** [comment]
Stability is important. The code will not be lost and can be updated at a later stage.

**Comment by w-klijn** [comment]
I did a quick check with the Arbor people and the rest of the cosim team. The interface appears to be not longer in use.

**Comment by espenhgn** [comment]
> @espenhgn might also be interested in this discussion.

This functionality is of little use to me if it does not support an Arbor version with the place_pwlin API which to my knowledge was added much more recently.
