### ISSUE TITLE
The 'Install Nest' section doesn't explain how to run Python tests

### ISSUE THREAD

**Issue by yurivict** [nest/nest-simulator#2192]
[Install Nest](https://nest-simulator.readthedocs.io/en/v3.1/installation/index.html)

**Comment by jougs** [comment]
You are right in that the basic installation instructions (from packages) don't talk about this. This is mostly because we assume that in those cases the tests have been run by the pipeline resulting in the package and the user won't gain much from running the tests again.

The [advanced installation instructions](https://nest-simulator.readthedocs.io/en/v3.1/installation/index.html#advanced-installation) for building from source, clearly mention the command `make installcheck`  after the call to `make install`.
