### ISSUE TITLE
Build error on Fedora rawhide (what will become Fedora 24 - GCC 6)

### ISSUE THREAD

**Issue by sanjayankur31** [nest/nest-simulator#220]
This is what I get when trying to build nest using my rpm on Fedora rawhide (24). It builds perfectly on Fedora 23. The one major different between Fedora 23 and rawhide/24 is that rawhide/24 is now using GCC 6 for builds, while F23 is using GCC 5.3.1

```
listartup.cc:81:15: error: cannot convert 'std::ifstream {aka std::basic_ifstream<char>}' to 'bool' in return
   return ( in );
               ^
```

Complete build log files can be found here: https://ankursinha.fedorapeople.org/misc/nest-rawhide-logs/

**Comment by heplesser** [comment]
@sanjayankur31 Others have reported the same problem with the not yet released GCC6 (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=811669). As far as I understand the C++98 standard, this code should be legal.

**Comment by sanjayankur31** [comment]
Ah, I'll keep checking the build with every GCC update. The default C++ standard for GCC 6 is C++14. I wonder if that has anything to do with this. I'll keep investigating. Cheers!

https://gcc.gnu.org/gcc-6/changes.html

**Comment by sanjayankur31** [comment]
It does look like a standard thing - I tested this with 
```
SET(CMAKE_CXX_STANDARD 11)
```
on an older gcc and it still failed - so, I'm just forcing cmake to use the 98 standard. If, nest only supports the 98 standard, maybe we should add this to CMakeLists.txt:
```
SET(CMAKE_CXX_STANDARD 98)
```

@tammoippen - what do you think?^

https://cmake.org/cmake/help/v3.1/prop_tgt/CXX_STANDARD.html#prop_tgt:CXX_STANDARD

**Comment by heplesser** [comment]
@sanjayankur31 C++11 indeed changed the way streams are convertible to bool, see [C++ Reference](http://en.cppreference.com/w/cpp/io/basic_ios/operator_bool). Together with the rules for [contextual conversion](http://en.cppreference.com/w/cpp/language/implicit_conversion) of [if conditions](http://en.cppreference.com/w/cpp/language/if) in C++11, this means that `if ( in )` still works, while `return ( in );` does no longer, since it requires implicit conversion from stream to bool. The proper fix for this would be to change line 81 to
```
return ( not in.fail() );
```
But I think we can tidy up the code a little more and demand that the file is [good](http://en.cppreference.com/w/cpp/io/basic_ios/good)
``` 
 if ( in.good() )
  {
    result = fullname;
    return true;
  }
  else
  {
    result.erase();
    return false;
  }
}
```

**Comment by jougs** [comment]
I this is indeed the only place where GCC6 fails, I agree with @heplesser's suggestion to tidy up the code. I'm happy to review a PR in this direction.

**Comment by sanjayankur31** [comment]
I'm not sure if this is the only place where it fails - it is the first place it fails - and this causes the build to abort. We'll only know about the other places once we fix this and re-run the compilation from what I know.

**Comment by tammoippen** [comment]
@sanjayankur31 The variable `CMAKE_CXX_STANDARD` is first introduced to cmake 3.1. We need to change the `cmake_minimum_required()` version then, since the standard cmake on most distributions is still 2.8.12, e.g. on JUQUEEN. We should look for a backward compatible way, e.g. something discribed [here](https://stackoverflow.com/questions/10851247/how-to-activate-c-11-in-cmake).

**Comment by sanjayankur31** [comment]
@tammoippen sure, that makes sense in general. This commit is luckily not a change related to a feature that was added in C++11, so it shouldn't break anything.
