### ISSUE TITLE
remove SLI from nest

### ISSUE THREAD

**Issue by dulingkang** [nest/nest-simulator#2302]
**Is your feature request related to a problem? Please describe.**
SLI is a new language, not in common use,  not easily to debuging.

**Describe the solution you'd like**
Remove SLI, use pybind11 replace

**Describe alternatives you've considered**
Easily provide C++ and Python api.

**Comment by jougs** [comment]
SLI is actually a really old language that is still is use for quite some of the larger models that must run on machines that don't support running Python. Moreover, most of the NEST testsuite is written in SLI and SLI datatypes are the basis for just about everything in the NEST kernel. Due to the varied requirements of our user community, we can't just just drop it as your proposal suggests.

That said, we are currently working on disentangling NEST's simulation kernel from SLI *and* Python in order to have it more modular and reusable (see e.g. #1717, #2208), but it's definitely not as trivial as just using pybind11 or something along those lines and be done.

**Comment by jougs** [comment]
If you have concrete problems with the current implementation, you can of course open follow-up issues here on GitHub or discuss with us on our [mailing list](https://www.nest-simulator.org/mailinglist/postorius/lists/users.nest-simulator.org/).
