### ISSUE TITLE
Unintuitive parametrization of gaussian2D

### ISSUE THREAD

**Issue by ackurth** [nest/nest-simulator#2388]
**Is your feature request related to a problem? Please describe.**
The parametrization for ```nest.spatial_distributions.gaussian2D``` is in my humble opinion somewhat unintuitive. While I see that this is a standard parametrization for the two-dimensional Gaussian probability distribution, I have a hard time to relate the parameters directly to a tilted ellipse describing the cloud of points one sees when sampling from such a distribution.
For spatial connections, thinking of this tilted ellipse seems to be more natural in my opinion.
What do you think?

**Describe the solution you'd like**
Coordinates used in the Gaussian part of the [Gabor function](https://en.wikipedia.org/wiki/Gabor_filter) seem to me more intuitive.

**Additional context**
See #2387

**Comment by heplesser** [comment]
@ackurth I think you have a point, but I am a bit reluctant to introduce a change that is not backward compatible. But I suppose one could deprecate the old scheme and for the time being, at least at the Python level, support the old and new parameterizations simultaneously, since both use different sets of parameters. One feature not supported by the Gabor scheme is an offset of the center as provided by the `mean_{x,y}` parameters of the current parameterization. That can always be achieved in different ways, if needed.

@hakonsbm Do you remember why the x and y values are passed in independently instead of as a 2D vector? I suppose because NEST does not support vector-value parameter objects?

**Comment by hakonsbm** [comment]
@heplesser I don't remember, but that reason seems possible. Not sure about the benefit of passing them as a 2D vector, though.

**Comment by heplesser** [comment]
I discovered a number of additional surprises and created #2391 as follow up. 

@ackurth If you agree, kindly close this issue and let's continue discussion in the new one.

**Comment by ackurth** [comment]
Closing the issue due it followed up by #2391.
