### ISSUE TITLE
Some models internally force integration timestep below a certain value

### ISSUE THREAD

**Issue by clinssen** [nest/nest-simulator#2389]
There are several models (adaptive exponential IAF models, ``glif_cond``, ``iaf_chxk_2008``) which internally force the integration timestep to be no greater than 0.01, e.g.:
https://github.com/nest/nest-simulator/blob/6adfd2cbb2df87123453cd2b46ef1aee40837d40/models/aeif_cond_exp.cpp#L381
I wanted to discuss whether this is an issue. This would mean that different nodes in the simulation are integrated at different timesteps; does this have any side effects on recording? Perhaps this is as intended; perhaps it should just use the kernel timestep but raise an exception if the step is too large; perhaps there should in any case be a notice in the documentation about this behaviour.

When NESTML generates code for a model, it could conceivably insert such a timestep limit (or exception raising) if the ODE-toolbox ODE benchmarking found a small timestep to be necessary.

**Comment by heplesser** [comment]
@clinssen As far as I can see, `iaf_chxk_2008` initialises `B_.IntegrationStep_` to the simulation resolution, so nothing special happens in that model. For `glif_cond`, I am not quite sure why it sets this low initial value for `B_.IntegrationStep_`, since the dynamics are not that fast; the comment in that code suggest that this setting migrated there from the aeif models.

Now, `B_.IntegrationStep_` is updated by the GSL adaptive stepsize solver during simulation, the line you showed above sets only the initial value. And it is only the internal step size for the GSL solver.

The one thing special about the aeif-models is that they check for threshold crossings *inside* the `while`-loop around the GSL-solver calls, while all or most other models just call the GSL solver until the end of a time step is reached. The aeif models as different here because the exponentially growing current would otherwise lead to instability.
