### ISSUE TITLE
Wrong release to dowload from the documentation

### ISSUE THREAD

**Issue by lionelkusch** [nest/nest-simulator#2398]
**Describe the flaw**
The link for the current release of the page : https://nest-simulator.readthedocs.io/en/v3.3/installation/index.html point to the version 2.20.

"Download the source code for the [current release](https://github.com/nest/nest-simulator/archive/v2.20.0.tar.gz)."

**Suggest an improvement**
You should update the link with the last release.

**Comment by JanVogelsang** [comment]
@jessica-mitchell Where do I find the .rst-files for this page? Was unable to find them on GitHub.

**Comment by jessica-mitchell** [comment]
@JanVogelsang nest/master has some major changes to the structure of the docs folder since the release of v3.3 so you won't find the files there. Unfortunately once the release is out it's fixed: so we cant update the docs for 3.3 version.
this is part of a larger issue of ensuring docs are up-to-date by avoiding links to specific versions and testing links prior to releases. (which we have started looking into for the CI pipeline).

**Comment by jessica-mitchell** [comment]
@lionelkusch thanks for pointing out this flaw, but as I mentioned above the documentation is fixed once the release is created so we cannot update links. In master, we do not link to a specific version for downloading NEST anymore.

I am closing this as this is resolved in master
