### ISSUE TITLE
Support Intel compiler suite and MKL

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#242]
A range of HPC sites provide the Intel compiler suite and MKL. Currently, we provide no instructions on how to build NEST with the Intel compiler suite with pertaining libraries. It seems, though, that the Intel tools may provide significant performance advantages, see #237, so it may be useful to support the Intel tools. #237 also contains the current state of experience with building with Intel tools.

**Comment by heplesser** [comment]
@lekshmideepu Do you know if Travis also allows us to test with Intel compilers?

**Comment by lekshmideepu** [comment]
@heplesser  Short answer is "yes", but with restrictions. There is an interesting thread in the [Travis](https://github.com/travis-ci/travis-ci/issues/4604) and [intel](https://software.intel.com/en-us/forums/intel-c-compiler/topic/564473) pages.
As ICC is a proprietary software one cannot use it directly on Travis due to the licensing issues. But the good thing is, Intel has a special [licensing](https://software.intel.com/en-us/qualify-for-free-software/opensourcecontributor) program for open source projects. As I understand, we need to get a 
that special license and could use it on Travis by encrypting  it and assign to the env. variable INTEL_SERIAL_NUMBER.
