### ISSUE TITLE
Registration of currents of a given synapse

### ISSUE THREAD

**Issue by krzyLadda** [nest/nest-simulator#2456]
Is it possible to record the current flowing through one selected synaptic connection. 

Suppose I have an iaf_psc_alpha neuron that is stimulated by multiple synapses. It is possible to record the input currents (excitatory and inhibitory ) to the neuron with a multimeter. But I would like to record currents from individual sysnaps. How to do this?

**Comment by heplesser** [comment]
Recording input currents through individual synapses is not possible in most NEST neuron models. The reason is efficiency: As soon as a spike arrives at a neuron, its effect is summed in an input buffer with all other spikes with the same spike arrival time. Therefore, only the total input current at each time step is recordable directly.

If you only want to record input currents through a small number of synapses and have only non-plastic synapses, you could proceed as follows. I assume below that you want to record the current through a synapse from neuron A onto neuron B.

1. Build your network.
2. Use `GetConnections` to obtain the synapse between A and B.
3. Create a new `iaf_psc_alpha` neuron C with the same parameters as B.
4. Connect A to C with the same synapse parameters as for the A->B connection.
5. Record the synaptic current from C.

Another option would be to use the `iaf_psc_alpha_multisynapse` model. If you know in advance how many incoming synapses neuron B has, let's say n, you could set up B as an `iaf_psc_alpha_multisynapse` neuron with n time constants (which can all be identical) and then connect each presynaptic neuron to a specific `receptor_type` in B. You can then record all input currents independently. If your network is larger, you may want to build your network first with the normal `iaf_psc_alpha` model, then extract connectivity with `GetConnections` and then build the network anew, explicitly creating the connections to `iaf_psc_alpha_multisynapse` neurons with the proper number of time constants/receptor types. Simulation time will increase when using the multisynapse model, so if you only need the input currents to a small number of neurons, you may want to leave the remaining neurons as normal `iaf_psc_alpha`.

@clinssen @pnbabu Would it be possible with NESTML to generate a version of `iaf_psc_alpha` (and other models) with a separate input buffer for each synapse to allow recording of individual input currents? It would come with a significant performance penalty, but if the currents are needed, it might be worth it.

**Comment by pnbabu** [comment]
We have a `Multiple input synapse` example in NESTML where we can record currents from individual synapses: https://nestml.readthedocs.io/en/v5.0.0/nestml_language/neurons_in_nestml.html?highlight=multisynapse#multiple-input-synapses

The corresponding NESTML model: https://github.com/nest/nestml/blob/master/tests/nest_tests/resources/iaf_psc_exp_multisynapse.nestml

In this example, separate input buffers are created for each spike input port which can then be recorded using a multimeter. I hope this helps.

**Comment by krzyLadda** [comment]
@heplesser @pnbabu 
I did exactly what you described in the points, but it increases the calculation time significantly, and I was looking for more optimal way.

The idea of receptors of different types or different input ports also came to my mind, but I didn't know that i can add them myself. That probably solves the problem. 

Thank you for your help!
