### ISSUE TITLE
is nest-simulator v3 available as a conda package?

### ISSUE THREAD

**Issue by fire-papaya** [nest/nest-simulator#2460]
**Describe the flaw**
In [installation part](https://nest-simulator.readthedocs.io/en/v3.3/installation/index.html) of the docs, in Conda tab there is a warning `The Conda package is only available for NEST 2.X. If you want to use NEST 3.X, please see other installation options.` But on the [conda forge](https://anaconda.org/conda-forge/nest-simulator) version is stated to be 3.3

**Suggest an improvement**
Remove the warning in Conda tab

**Supporting materials**
[link to installation docs](https://nest-simulator.readthedocs.io/en/v3.3/installation/index.html) 
[link to conda-forge](https://anaconda.org/conda-forge/nest-simulator)

**Desktop/Environment**
Conda installation

**Additional context**
-/--/-

**Comment by heplesser** [comment]
Conda packages for NEST 3.3 became available on conda-forge only after NEST 3.3 was released. Since our documentation is versioned and NEST ReadTheDocs documentation by default shows the documentation version of the most recent release, the information about the conda packages is not included there. The "latest" version of the installation documentation is up to date (https://nest-simulator.readthedocs.io/en/latest/installation/conda_forge.html#conda-forge-install).

I will close the issue.
