### ISSUE TITLE
PyNN 0.7.5 setup fails with NEST 2.10.0

### ISSUE THREAD

**Issue by albada** [nest/nest-simulator#252]
pyNN.nest.setup() tries to set minimal and maximal delays, but this causes an error because gap_junction does not have a delay.

**Comment by jougs** [comment]
@apdavison: How do we handle old versions of PyNN? Are they just deprecated and not expected to run with new versions of NEST? Thanks!

**Comment by apdavison** [comment]
PyNN 0.7.x is only tested with NEST 2.2, although I think some people have successfully used more recent versions of NEST.

Normally, old versions of PyNN are only expected to run with the version of NEST that was current when they were released.

The problem here is that the neuromorphic hardware systems in HBP only support the PyNN 0.7 API (0.8 support is underway), so anyone who wants to use both NEST and neuromorphic hardware probably needs PyNN 0.7.x. (although writing code which is compatible with both 0.7 and 0.8 is usually possible).

Anyone who does not need to use neuromorphic hardware should use PyNN 0.8 (NEST 2.8 supported in the latest version on PyPI, 2.10 supported in the master branch).

If you do need neuromorphic hardware, I suggest using NEST 2.2 if possible. If you really need a more recent version, please comment on this ticket.

**Comment by heplesser** [comment]
I think @apdavison's comment provides a good explanation and work-around. I am therefore closing this issue.
