### ISSUE TITLE
CI cmake configures NEST builds without readline

### ISSUE THREAD

**Issue by steffengraber** [nest/nest-simulator#2966]
Describe the bug

Have observed several times now that cmake in the CI is reporting "Use Readline: No"

To Reproduce

You can see it for example here:
https://github.com/nest/nest-simulator/actions/runs/6348332376/job/17244765370#step:15:182

Expected behavior
If this is not intentional, it should be "Use Readline: Yes".

Additional context

This seems to be due to the line:
https://github.com/nest/nest-simulator/blob/b88b099d71fe10c73d4443edd15bdbd93d2d77ae/.github/workflows/nestbuildmatrix.yml#L581

Since there is no readline in matrix.use it is always switched OFF.

**Comment by steffengraber** [comment]
@terhorstd If this behavior is OK, the issue can be closed.  
Otherwise, `readline` should at least be included in the full installation, or the line `-Dwith-readline=${{ contains(matrix.use, 'readline') && 'ON' || 'OFF' }} \` can be deleted completely and the default value `ON` be set.

**Comment by terhorstd** [comment]
Technically you are right and `readline` should be added to the full build. However, having it in or not would not have any effect other than requiring the install of the additional dependency.
* no test would fail since readline is only used when interactively working in sli (in the test suite sli reads from files). Pytests are independent anyways.
* in the upcoming refactoring sli will be removed and with it `readline` is not a dependency of NEST anymore, so we would need to remove it anyway.

**Comment by steffengraber** [comment]
Thank you for your feedback. With this, the issue can be closed.
