### ISSUE TITLE
How do you run Potjans_2014 in full scale?

### ISSUE THREAD

**Issue by bjourne** [nest/nest-simulator#3122]
Is it possible to run the above example from the PyNEST directory in full scale? If I change `"N_scaling"` and `"K_scaling"` to 1.0, NEST errors out with:

    nest.lib.hl_api_exceptions.NESTErrors.Too many connections: at most 134217727 connections 
    supported per virtual process and synapse model.: Too many connections: at most 134217727 
    connections supported per virtual process and synapse model. in SLI function Connect_g_g_D_D: 

Does NEST have to be compiled in some special way to handle large models? I have a lot of memory on my computer so 134 million connections is not a problem.

**Comment by bjourne** [comment]
Thanks. I changed the number of threads to 8 by setting `"local_num_threads": 8,`. This however seem to affect the simulation and I don't get the same results as when I run it with 1 thread.

**Comment by heplesser** [comment]
Due to the way random number generators work in NEST, different numbers of virtual processes (MPI ranks times OpenMP threads) will yield different random number sequences and thus different detailed spike patterns. But if you look at measures such as average firing rates, inter-spike interval distributions or cross-correlations, they should not differ significantly for different numbers of parallel processes.

**Comment by terhorstd** [comment]
Thanks for the question! If this is not solved, please reopen.
