### ISSUE TITLE
Can't import nest after having updated to ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by kopxiong** [nest/nest-simulator#316]
ImportError                               Traceback (most recent call last)
<ipython-input-1-c493c116876b> in <module>()
----> 1 import nest

/home/andy/opt/nest/lib/python2.7/site-packages/nest/__init__.py in <module>()
     50 
     51 
---> 52 from . import pynestkernel as _kernel
     53 import lib.hl_api_helper as hl_api
     54 

ImportError: libgsl.so.0: cannot open shared object file: No such file or directory

**Comment by heplesser** [comment]
@kopxiong The problem here is that NEST does not find the GNU Science Library, gsl. Is GSL installed on your system, and did you recompile NEST after updating to 16.04? 

The [NEST User mailing list](http://www.nest-simulator.org/community/) is a better place for questions like this one. Could you send any further communication in the matter there?

**Comment by kopxiong** [comment]
@heplesser After I recompiled NEST the issue was fixed. Thanks a lot!
