### ISSUE TITLE
Clearly document that threading in NEST should not be combined with multiple threads in Python

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#361]
Threading with python is bad.
Threading with Nest & python is really bad.
Threading with Nest & python & openmp is really really bad (SEGV bad often).
The question is: should this simply be declared "cave canem", or should we preempt by checking that python is running on the main thread (and to what extent is even that well-defined?) when nest is entered if openmp is active. I'm referring to having multiple threads created from python, while leaving unchanged the openmp threading model of nest.

Or is there some third idea about blowing up in a well-defined way with multiple threads?

**Comment by sanjayankur31** [comment]
I think checking if python is running on the main thread and aborting with an error if it isn't is a good way to go - when nest supports openmp and mpi, I see no reason for people to need multiple python threads.

Checking for the main thread is simple enough: http://stackoverflow.com/questions/23206787/check-if-current-thread-is-main-thread-in-python

To begin with, some mention of this in the user docs would be nice?

**Comment by apeyser** [comment]
What "threads in python" are you specifically referring to? Which module running what? Just the standard threading module?

In general, you're right -- just don't do threads in python. Ever. It's (almost?) never the sensible thing to do. 

I don't think there's any general solution -- but checking if you happen to be started from the main thread may avoid some of the most obvious mistakes.

**Comment by jessica-mitchell** [comment]
@heplesser  There seems to be some discussion in this topic and I'm unsure what the user docs should include. 
Are we aiming to warn users against threading? When does this come up as an issue for users? Why would a user want to use threading in the first place? 
@apeyser indicated there are different types; so is this threading referring to a problem in some specific instance?  
thanks

**Comment by apeyser** [comment]
@jessica-mitchell: to be more exact, threading "under the covers" within a C library that does not recur to python isn't a problem. "Threading" which is actually multiprocessing in python using the `multiprocessing` module isn't a problem. But either directly calling threads in python or having a multithreaded C program that executes any python within multiple threads is a problem.

So NEST in Python belongs to the "under the covers" case -- it is multithreaded, but the threads all belong to NEST and NEST doesn't call python from inside the threads. If you want to do that, you need to capture the global interpreter lock --- but, since NEST is OpenMP multithreaded, you'd have to implement your threads to play nicely with OpenMP, and not simply allocate pthreads at will which can both disrupt openmp and NEST's enumeration of threads and thread-based data structures. The sensible conclusion is just don't bother with threading.

The common user's case is that a user attempts to couple NEST to a GUI or analysis tool by running both within a single process, each one running on separate threads, and each one executing python code. The solution is to run multiple processes (using say `multiprocessing`) and have processes talk to each other through a pipe (such as `Queue`). This also makes it easier to scale the tool: for a gui scenario, see https://www.frontiersin.org/articles/10.3389/fninf.2018.00032/full . Going from multiprocessing --> cluster computing is much easier than going from multithreading --> multiprocessing.

**Comment by heplesser** [comment]
@jessica-mitchell @apeyser said it all: the entire problem here was created when people tried to build GUIs around NEST using multithreading.

**Comment by apeyser** [comment]
@heplesser @jessica-mitchell And thus we are building a gui infrastructure for several simulators!
