### ISSUE TITLE
Incorrect summation of synaptic currents for `iaf_psc_exp_ps`

### ISSUE THREAD

**Issue by apdavison** [nest/nest-simulator#368]
When two inputs, with equal but opposite weights, converge on an `iaf_psc_exp_ps` neuron with different time constants for the `ex` and `in` synapses, the voltage trace is flat. This problem does not occur with `iaf_psc_exp` or if the inputs arrive at different times.

To reproduce, run the following once with `precise=True`, again with `precise=False`:

``` python
import matplotlib.pyplot as plt
import nest

precise = True
relative_delay = 0.0  # the problem does not occur if this is positive

nest.SetKernelStatus({'off_grid_spiking': precise})

if precise:
    neuron_model = 'iaf_psc_exp_ps'
    filename = "with_ps"
else:
    neuron_model = 'iaf_psc_exp'
    filename = "without_ps"

if relative_delay:
    filename += "_delay"

neuron = nest.Create(neuron_model, 1, {'tau_syn_ex': 12.0, 'tau_syn_in': 4.0, 't_ref': 0.1})

spike_sourceD = nest.Create('spike_generator', 1)
spike_sourceR = nest.Create('spike_generator', 1)
nest.SetStatus(spike_sourceD, 'spike_times', [[40.0]])
nest.SetStatus(spike_sourceR, 'spike_times', [[40.0]])

nest.CopyModel('static_synapse', 'decay_syn', {'weight': 200.0, 'delay': 0.5})
nest.CopyModel('static_synapse', 'rise_syn', {'weight': -200.0, 'delay': 0.5 + relative_delay})

nest.Connect(spike_sourceD, neuron, syn_spec='decay_syn')
nest.Connect(spike_sourceR, neuron, syn_spec='rise_syn')

recorder = nest.Create('multimeter')
nest.SetStatus(recorder, {'withtime': True, 'record_from': ['V_m']})
nest.Connect(recorder, neuron, 'all_to_all')

nest.Simulate(200.0)

data = nest.GetStatus(recorder)[0]['events']
senders = data['senders']
times = data['times']
vm = data['V_m']

for n in neuron:
    plt.plot(times[senders==n], vm[senders==n])

plt.savefig(filename + ".png")
```

_`precise = False`_
![without_ps](https://cloud.githubusercontent.com/assets/260552/15579733/247cd356-2366-11e6-80e6-b56cbcb92d26.png)

_`precise = True`_
![with_ps](https://cloud.githubusercontent.com/assets/260552/15579747/2b4e09c0-2366-11e6-8a4d-8f71a25efff2.png)

NEST: 2.10.0, Python: 3.4.2

Thanks to Hajime Yamauchi for the original bug report to the NeuralEnsemble Google group.

**Comment by heplesser** [comment]
One ignores Donald K at ones own peril: premature optimization is the root of all evil .... The problem is that [`SliceRingBuffer::get_next_spike()`](https://github.com/nest/nest-simulator/blob/abe8f7275468db5e65c11fd3e204a84241e6800a/precise/slice_ring_buffer.h#L207) sums all spikes arriving at *exactly* the same time and then returns the summed weight. In the test case, this sum is zero, thus the flat membrane potential.

This was not a problem really in the original `iaf_psc_alpha_canon` model, because that had only a single synaptic time constant for both excitatory and inhibitory input. `iaf_psc_exp_ps` allows for different time constants, but still puts [all spikes into one buffer](https://github.com/nest/nest-simulator/blob/abe8f7275468db5e65c11fd3e204a84241e6800a/precise/iaf_psc_exp_ps.cpp#L407) and only distinguishes between E and I spikes [when the buffer is read out](https://github.com/nest/nest-simulator/blob/abe8f7275468db5e65c11fd3e204a84241e6800a/precise/iaf_psc_exp_ps.cpp#L361). At this point, it gets the summed weights of simultaneous spikes and we are in trouble.

The proper solution for this is to place excitatory and inhibitory spikes in separate buffers in the `handle()` method, as is done in [`iaf_psc_exp`](https://github.com/nest/nest-simulator/blob/abe8f7275468db5e65c11fd3e204a84241e6800a/models/iaf_psc_exp.cpp#L333).

One should probably also remove the spike accumulation from `SliceRingBuffer::get_next_spike()`, since the probability of simultaneous spikes in a precise simulation is vanishing (spike offsets would have to agree to the last bit).

**Comment by terhorstd** [comment]
Note also the discussion on buffers in multi-synapse models in the [2016-09-19-Open-NEST-Developer-Video-Conference](https://github.com/nest/nest-simulator/wiki/2016-09-19-Open-NEST-Developer-Video-Conference)...
