### ISSUE TITLE
PyNEST test fail during make installcheck

### ISSUE THREAD

**Issue by shahidbright** [nest/nest-simulator#398]
Hi,

after running make installcheck command, everything was good except I got one error;

NEST Testsuite Summary
----------------------
  NEST Executable: /home/shahid-linux/anaconda2/bin/nest
  SLI Executable : /home/shahid-linux/anaconda2/bin/sli
  Total number of tests: 206
     Passed: 205
     Failed: 1 (1 PyNEST)

What to do and what will be its consequences ? I am new to PyNN and NEST.

[reports.tar.gz](https://github.com/nest/nest-simulator/files/314223/reports.tar.gz)

**Comment by tammoippen** [comment]
Hi @shahidbright,

The issue is [known](https://github.com/nest/nest-simulator/issues/210#issuecomment-175524931). See #210 for a discussion. In #323 the issue was fixed, so I assume you are using NEST 2.10?

The problem is that PyNEST only finds the `libreadline.so` from Anaconda, which is lacking some symbols, i.e. it does not link against `libncurses`. You can either install NEST from the master branch (the build system changed to cmake, see INSTALL) or use PyNEST with some effort: 
* always include readline before you include NEST, e.g.:
 
  ```Python
  import readline
  import nest
  ```
* Preload `libncurses` before you start NEST: 

        LD_PRELOAD=/lib/x86_64-linux-gnu/libncursesw.so.5 python pynestscript.py

Best, Tammo

**Comment by apeyser** [comment]
Duplicate. Closed.
