### ISSUE TITLE
Use pandas.read_csv instead of numpy.loadtxt

### ISSUE THREAD

**Issue by sanjayankur31** [nest/nest-simulator#400]
This explains it: http://akuederle.com/stop-using-numpy-loadtxt. (numpy.loadtxt is extremely slow compared to pandas.read_csv.)

One place where numpy.loadtxt is used is in the [raster_plot.py](https://github.com/nest/nest-simulator/blob/master/pynest/nest/raster_plot.py) file. 

Not the most urgent issue, but something that can be updated when there's time.

**Comment by heplesser** [comment]
@sanjayankur31 Thank you for pointing this out! I think we should take this up at one of the next developer meetings, since it would make Pandas a requirement for PyNEST. I think there are many excellent reasons for this, but we should still discuss it in a bigger group.

As an aside: For interactive work, you can pass the `events` dictionary returned by `GetStatus` on a recording device directly into the constructor of a Pandas `DataFrame` and start analysing. For a few examples, see the [notebooks in my course material](https://bitbucket.org/heplesser/nmbu_fys388_v2015/) for the computational neuroscience course at NMBU.

**Comment by apeyser** [comment]
Suggestion: try to use pandas, and if that fails fallback to our current code
@sanjayankur31 If you try that approach, we'll be happy to extend raster_plot to use panda if it's available
