### ISSUE TITLE
Consider supporting HDF5/netCDF for file outputs

### ISSUE THREAD

**Issue by sanjayankur31** [nest/nest-simulator#407]
I'm running some simulations - 6000 seconds simulation time - which isn't really too long. I do however have spike files that are 25Gbs to process. Using human readable ASCII formats is nice, but it increases file size and I/O - and I/O is usually the performance bottle neck nowadays. I was looking at how one can improve on this, and the usual solution is to use binary files - but binary files are not portable and therefore HDF5 or netCDF have been developed. They provide tools and libraries to manipulate/view/convert data and so on already. HDF for example also supports parallel I/O and random access. 

While it isn't a trivial feature to add, I do think this would be a nice feature in NEST which is meant for large networks and clusters and expects to produce large amounts of data.

More on HDF here: https://www.hdfgroup.org/why_hdf/

**Comment by sanjayankur31** [comment]
I'd written a [binary spike monitor for Auryn](https://github.com/fzenke/auryn/blob/develop/src/BinarySpikeMonitor.cpp) which saved a lot of space and I/O - I wasn't aware of HDF then

**Comment by sanjayankur31** [comment]
Here's some data on this:

``` bash
$ wc -l spikes-E.gdf 
1324054745 spikes-E.gdf
$ h5import spikes-E.gdf -c spikesE.conf -outfile spikes-E.hf5
$ file spikes-E.gdf spikes-E.hf5 
spikes-E.gdf: ASCII text
spikes-E.hf5: Hierarchical Data Format (version 5) data
$ du -sch spikes-E.gdf spikes-E.hf5 
22G     spikes-E.gdf
9.9G    spikes-E.hf5
32G     total
```

Quite a reduction. I've also found that libraries such as [pandas support reading hdf natively](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_hdf.html).

**Comment by jougs** [comment]
Thanks for the suggestion and your data.

We (@apeyser, @wschenck, @sbillaudelle and I, amongst others) did a lot of research on new  I/O strategies for NEST recently and we're currently in the process of finalizing our code and try to make it available for the next release.

However, we decided against HDF5 in favor of a custom binary streaming format based on our benchmarks. Due to the heavy structuring inside the file, HDF5 is really slow to write to in massively parallel scenarios, when you can't reserve the file size in advance.

A first article about this work was published at ECCOMAS 2015 ([abstract book](http://juser.fz-juelich.de/record/202952/files/ProceedingsYIC-GACM-ACCES.pdf), search for *Schumann*)

**Comment by sanjayankur31** [comment]
Ah, awesome - I look forward to testing the new format (SIONlib?).

I'll just use ASCII + HDF for the time being.

**Comment by jougs** [comment]
Yes, the new format will be based on SIONlib. I'll update this issue when there's news.

**Comment by sanjayankur31** [comment]
Came across this paper on a "neuroscience simulation data format" - worth a look: http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4823348/

**Comment by jougs** [comment]
As we are getting closer to a first feature preview for nestio, I am closing this isssue. Further discussion about the handling of I/O can take place in the PR once it is opened.
