### ISSUE TITLE
NEST developer version specifies version to '2.10.0'

### ISSUE THREAD

**Issue by mschmidt87** [nest/nest-simulator#411]
The NEST developer version from github specifies its version number to '2.10.0' and is therefore easily confused with the official release version. This is true for the header that is shown on the startup of NEST and for `nest.version()`.

Optimally, this could instead give the commit hash of the source code that was actually used for the code.

**Comment by DimitriPlotnikov** [comment]
Hi, 
it is true an issue in the current version of NEST. However, I don't like the proposal to use the any hashcodes based on commits. It could lead to a problem, that NEST user would start to relay on a particular temporary version development version. 

Therefore, my proposal would be to call the current version like: 3.0.0-SNAPSHOT. It unambiguously states that it is a development version of the 3.0.0 release. This scheme is adopted from Maven, but it is already proved to work.

@mschmidt87 Would this proposal solve your problem? Could your otherwise elaborate on advantages of your proposal?

**Comment by mschmidt87** [comment]
Hi, your proposal would at least avoid confusion of the developer version with the release version. 

However, I still think that it would be better to have the commit hash displayed, because this enables true provenance tracking of which version of NEST you actually compiled and are using, when e.g. discovering a bug. So, whenever a user reports a bug or a problem with NEST, we can easily ask him for the exact version, which will make it easier to track the problem down.

**Comment by DimitriPlotnikov** [comment]
Hi,

from my point of view, all bugs must be reported on the latest version. If it is not there anymore, then the bug is solved:) We will discuss it one more time during the next NEST developer meeting and meet the final decision then.

**Comment by mschmidt87** [comment]
Okay, you have a point here. Still, I think it would be useful to have the executable indicate the exact commit hash, I have stumbled across this quite a few times during development and simulation work.

**Comment by DimitriPlotnikov** [comment]
Hello @mschmidt87,  
your points are correct and valid from the developer's point of view.  But for the enduser a commit hash is not really informative.  github enables you to checkout a particular pullrequest (https://help.github.com/articles/checking-out-pull-requests-locally/) and/or particular commit. In case that you really need to work with th specific commit, you can do it and keep track of the hash information locally. 

Beside that I made a pull request fixing the problem.

**Comment by apeyser** [comment]
But bug reports on the developer branch indicate that we are talking about the developer's point of view.The hash can go into a built file, and for release versions there'd be no hash, since it's a fixed release. 

The counter-point is that this makes the system more complex and buys us little, since we're talking a sophisticated user who was smart enough to at last have a tag pointing at his sources for his build, so he can report that hash if needed. And we've had problems in the past with the automated version files coming out of svn.

Either way, I'd suggest even-odd numbering. We're on 2.11, and the next release would be 2.12 or 3.0. After the release, the master branch would be 3.1 and so on

**Comment by heplesser** [comment]
@apeyser I suggest we discuss version numbering in the Developer VC on 22 Aug (the agenda for 8 Aug is full enough already).

@mschmidt87 If uncertainties about the version used occur in discussion with developers, it is always available through `statusdict/rcsinfo :: =`, so I think it is not necessary to provide it in the startup message.

@DimitriPlotnikov I think you `-SNAPSHOT` proposal makes sense.

**Comment by DimitriPlotnikov** [comment]
The PR https://github.com/nest/nest-simulator/pull/448 is already merged and the issue can be closed.

**Comment by jougs** [comment]
@DimitriPlotnikov: thanks for checking.
