### ISSUE TITLE
Extremely slow simulation of hh_psc_alpha neurons when V_m is very low

### ISSUE THREAD

**Issue by dnao** [nest/nest-simulator#419]
In the `hh_psc_alpha` and `hh_psc_alpha_gap` models, when V_m < -300 mV, the simulation time increases significantly and the realtime factor approaches 0. The code below should demonstrate the resulting slowdown in simulation time around 12-32 ms as a result of repeated inhibitory stimulus applied between 0 and 30 ms:

``` python
import nest
import nest.voltage_trace
import matplotlib.pyplot as plt

neuron_model = 'hh_psc_alpha'

nest.ResetKernel()
nest.SetKernelStatus({"print_time": True})

neurons = nest.Create(neuron_model)

noise = nest.Create('spike_generator',
    params = [{'spike_times': [ t/10.0 for t in range(1,300) ] } ] )

voltmeter = nest.Create('voltmeter')

nest.Connect( noise, neurons, syn_spec = { "model": "static_synapse", "weight":-150.0 } )
nest.Connect( voltmeter, neurons )

nest.Simulate(60)
nest.voltage_trace.from_device(voltmeter)
plt.show()
```

![Image of membrane potential](http://i.imgur.com/dfxJxth.png)

For 'typical' values of membrane potential (between -80 and 40 mV ) the simulation is very fast, but if a HH neuron receives a lot of inhibitory stimulus at once, then the membrane potential can become extremely negative.

My suspicion is that such extreme hyperpolarization should be considered unphysical. In that case, is the solution to ensure that a HH neuron never receives such a strong inhibitory stimulus? From what I can gather, such extreme values are not observed experimentally. In that case, I am curious as to whether this solution is an artifact from the choice of numerical approximation or if it is indeed valid given on the initial conditions (which may themselves be unphysical).

**Comment by heplesser** [comment]
@dnao I am not sure why the numerics slows down so much when the neuron hyperpolarizes extremely. It probably is due to the adaptive stepsize solver switching to very small time steps due to fast changes in state variables other than V_m. @DimitriPlotnikov, could you take a look at the details?

The main point, though, is that a hyperpolarization to -300 mV is entirely unphysiological: The membrane is polarized due to ion currents which are driven by potential gradients. Typically, the lowest reversal potential for inhibitory synapses (GABA) is around -90 mV, so there is no way the membrane potential could sink below that value. If you used a conductance-based model, the actual input current ( g * (V_m - V_rev) ) would drop to close to zero when V_m comes close to the reversal potential V_rev, no matter how much input arrives. 

When using a current-based model, this "saftey mechanism" does not exist, so you need to make sure that you use the model only in a context where it receives sufficiently balanced input so that the membrane potential does not drop much below -90 mV.

**Comment by heplesser** [comment]
Closing because this concerns an extreme, unphysiological border case only.
