### ISSUE TITLE
NodeManager::is_local_node returns wrong values for last rank

### ISSUE THREAD

**Issue by tillschumann** [nest/nest-simulator#430]
NodeManager::is_local_node( Node\* n ) seems to return always true for the last rank.

from my understanding:
vp is initialized with -1 for remote nodes.
therefore vp % n_sim_procs_ in mpi_manager_impl.h:55 returns id of last rank for remote nodes

**Comment by heplesser** [comment]
@tillschumann You are right that vp is -1 for remote nodes, but then, there are never pointers to remote nodes, so `is_local_node()` should only be called for local nodes with valid vp numbers. But clearly, the method name then is very misleading and there should be some checks: `const Node&` as input argument instead of `Node*` and assertion that `vp >= 0`.

**Comment by heplesser** [comment]
This will be fixed when integrating #480, therefore closing.
