### ISSUE TITLE
Inhibitory weight distribution

### ISSUE THREAD

**Issue by lepmik** [nest/nest-simulator#459]
Wen connecting two populations with pyNEST the sign of synaptic weights define if synapses are inhibitory or excitatory. Presently it does not seem to be possible to explicitly select an inhibitory weight distribution. Below is an example of a workaround and a suggestion for a fix.

```python
Connect(nodes_in, nodes_ex,
       {'rule': 'pairwise_bernoulli', 'p': p_in},
       syn_spec={'model': 'static_synapse',
                 'weight': {'distribution': 'lognormal',
                            'mu': mu_in,
                            'sigma': sigma_in},
                  "delay":delay})
conns = GetConnections(nodes_in, nodes_ex)
conn_vals = GetStatus(conns, 'weight')
SetStatus(conns, [{'weight': -1.*val} for val in conn_vals])
```

Comment from mailing list by Hans Ekkehard Plesser:
> At present, this is not possible in NEST, but I think it should be reasonably easy to implement. Take a look at the RandomParameter class defined in conn_parameter.{h,cpp}.
> 
> I we added an extra flag 'sign' with allowed values -1 and +1, the constructor could extract it from the dict defining the distribution and store it in a local variable sign_. The value_{int, double}() methods would then multiply the return value with sign_ before returning.
> 
> Note that any clipping of values would be applied to the original values before multiplying with sign_.

**Comment by heplesser** [comment]
This issue follows up ticket 887 in the old NEST trac.

**Comment by heplesser** [comment]
A more general approach would be to support arbitrary mathematical expressions for parameters. The question is how to implement this efficiently. Topology has *undocumented* support for this on the SLI level:
```
topology using
/p1 << /uniform << /min 0.5 /max 2.0 >> >> CreateParameter def
/p2 << /constant << /value 0.5 >> >> CreateParameter def
/pprod p1 p2 mul def
```
This is undocumented since we have not come up with a good solution for lifting this to the Python level yet. Something like
```python
p1 = nest.parameter.uniform(min=0.5, max=2.0)
p2 = nest.parameter.constant(0.5)
p3 = p1 * p2
```
might be feasible, but the question is how to allow for efficient evaluation of the resulting expression.

**Comment by mschmidt87** [comment]
Hi, I just stumbled upon this issue again. If I understood the Topology code correctly, it allows for the four basic operations of adding, substracting, multiplying and dividing parameters, which are implemented on the C++ level by the `SumParameter`, `DifferenceParameter` etc. classes. So, this is basically what we would need, right?
Wouldn't a solution be to do the following:
1. Port the implementation from Topology to the NEST Kernel in `conn_parameter.{h,cpp}`. 
2. Allow the user to specify such Parameters as in the Topology example that you gave and then pass them to the Connect function. Something like

    /p1 << /uniform << /min 0.5 /max 2.0 >> >> CreateParameter def
    /p2 << /constant << /value -1. >> >> CreateParameter def
    /pprod p1 p2 mul def
    << /model /static_synapse
          /weight pprod 
          /delay 1. 
    >> /syn_dict Set
    1 1 syn_dict Connect

So, instead of specifying a distribution, one could specify and combine parameters in this flexible way, which seems to be implemented in the topology module already.

**Comment by heplesser** [comment]
@mschmidt87 In principle, you are right. I will think about this carefully in the planned work to unify the topology and connect user interfaces. There are currently two problems with this approach:

1. Much of the syntax is very topology-centric with parameter names that do not generalize
1. The implementation is slow: each time a parameter is evaluated, NEST needs to do a tree traversal to recursively evaluate subexpressions.

I would like to have the generalization with revised syntax in place before adding this elsewhere in NEST.

I will try to create a proposal to address 1. soon. We can then handle the optimization of 2. later.

**Comment by jougs** [comment]
Maybe our compiler expert @DimitriPlotnikov can help optimizing this?

**Comment by DimitriPlotnikov** [comment]
@jougs @heplesser I understand only partially what is going on in this issue. 
1) Must be solved by domain experts
2) You can mimic an attribute grammar (add an attribute 'value' to each expression, walk through the tree and compute it once, retrieve cached value each time it is needed). My assistant student did it for NESTML expression sub-language and he is working on a short presentation explaining a visitor based approach to implement attribute grammars. As soon as it is done I can report on it.

Nevertheless: how often expressions are evaluated? Only during the network is built up? Also during the simulation?

**Comment by heplesser** [comment]
For a general solution to this, see #488.

@lepmik Would you consider closing this issue? Have you found a work-around?

**Comment by lepmik** [comment]
Still use the workaround I stated in the first post :)
