### ISSUE TITLE
hh_cond_exp_traub handles refractory time incorrectly

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#473]
[`hh_cond_exp_traub::calibrate()`](https://github.com/nest/nest-simulator/blob/0d58accc82b6b44801c82e502976889e3c37d80b/models/hh_cond_exp_traub.cpp#L371) sets `V_.RefractoryCounts_` to a hard-wired value of 20 time steps, independent of the simulation resolution. Neuron responses will therefore depend on resolution.

Note also that the refractory period cannot be changed by the user.

**Comment by Silmathoron** [comment]
Ok, here's news!
I made the changes to ``hh_cond_exp_traub``, but then I thought "ok, wth, I'll make a test to check all neurons implement ``t_ref`` correctly" (at least all those that have it)...
**But**... it turns out that:

1. there are model like ``amat2_psc_exp`` does not clamp the potential during refractory period, so I cannot check it directly (same for ``hh_*`` obviously)... would you have an idea regarding how we could check them?
2. Refractory time implementation is not consistent between ``aeif`` and ``iaf``/``gif_*`` models!!
3. Many iaf models do not implement ``t_ref``, which seems surprising...
4. I also have no idea how to test the precise models...

## AEIF vs IAF

For aeif models, the potential is reset at the timestep when the spike was emitted, whereas the reset
occurs on the following timestep for ``iaf``/``gif`` models.
Also the aeif models decrement ``r_`` at the beginning of ``update``, whereas iaf and gif do not.

I think there is a problem of interpretation of the refractory period:

- aeif models "seem to consider" that when a spike occurs, the spike was emitted at the beginning of the step, so the timestep containing the spike is considered in the refractory period.
- iaf and gif models do not see it that way, so there is an additional timestep compared to aeif...

**Comment by Silmathoron** [comment]
Ok, merging #575 solved part of the problem so I will at least be able to propose a fixed hh_cond_exp_traub and tests for almost all neurons implementing ``t_ref``.
A notable exception remains ``amat2_psc_exp`` which does not clamp the potential... any opinion on the matter?
What about the problem of non-refractory IAF models and precise models?

**Comment by heplesser** [comment]
- `amat2_psc_exp` does not clamp the potential. From Yamauchi et al (2011): "In addition, to avoid singular bursting, the neuron is not allowed to fire within an absolute refractory period τ_R even when the membrane poten- tial exceeds the threshold. If the membrane potential lies above the threshold after the period τ_R, the model assumes another spike."
- Which IAF models are non-refractory?
- Precise neurons should be refractory for exactly t_ref following an output spike. One way of testing this would be to drive them with a large I_e and check the spike times. Similar to test_iaf_ps_dc_t_accuracy.sli.

**Comment by Silmathoron** [comment]
Ok, so ``amat2_psc_exp`` is out.

Here is the current list of models I need to ignore:

    ignore_model = [
        "aeif_cond_alpha_RK5",
        "aeif_cond_alpha_multisynapse",
        "aeif_cond_beta_multisynapse",
        "amat2_psc_exp",
        "ginzburg_neuron",
        "hh_cond_exp_traub",
        "hh_psc_alpha",
        "hh_psc_alpha_gap",
        "ht_neuron",
        "iaf_chs_2007",
        "iaf_chxk_2008",
        "iaf_cond_alpha_mc",
        "iaf_psc_alpha_canon",
        "iaf_psc_alpha_presc",
        "iaf_psc_delta_canon",
        "iaf_psc_exp_ps",
        "iaf_tum_2000",
        "izhikevich",
        "mat2_psc_exp",
        "mcculloch_pitts_neuron",
        "parrot_neuron",
        "parrot_neuron_ps",
        "pp_pop_psc_delta",
        "pp_psc_delta",
        "sli_neuron",
    ]

* As RK5 will be removed and you fixed the multisynapses, this should be ok
* ``iaf_chs_200x`` have no ``t_ref``
* ``iaf_tum_2000`` has 2 refractory periods which are called ``t_ref_abs`` and ``tau_ref_tot``... it seems that ``t_ref_abs`` corresponds to the usual ``t_ref`` (V is clamped) so I could test this one...
* I guess ``mat2_psc_exp`` is the same as amat2...
* I have not taken care of precise models yet

**Comment by Silmathoron** [comment]
@heplesser I just tried, ad due to the implementation of the HH models, there is just no way I can test them...
Using the interspike, I managed to test the ``mat2`` and amat2`` models, as well as the precise models.
