### ISSUE TITLE
Remove subnets from NEST

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#480]
As decided in the [Developer VC on 8 Aug](https://github.com/nest/nest-simulator/wiki/2016-08-08-Open-NEST-Developer-Video-Conference), subnets are to be removed from NEST for the NEST3 release (#417).

This entails:
- Full GIDCollection support (#455) 
- `Create` returning `GIDCollection` instead of last gid (SLI) or a list of GIDs (Pynest)
- Transition from `0 << >> SetKernel` to `<< >> SetKernelStatus` in SLI 
- Adaptation of tests and examples where necessary (mostly SLI)
- Transition
- Significant code simplification:
  - removal of root subnet, and thus simplified initialization (**note**: the first node created shall still have GID 1, GID 0 will be unused in the future)
  - `add_node()` becomes simpler
  - adjustment of `PrintNetwork` (details to be determined)
- Support for advanced dry-run modes (#482)
- Adaptation of Topology module (#481)
- Possibly removal of `SiblingContainer` as well (#512)

**Comment by jougs** [comment]
@heplesser: as this work is already mostly finished in [our branch](https://github.com/compneuronmbu/nest-simulator/tree/fix-481-SubnetFreeTopology), I suggest to close this issue here in order to avoid confusion.

I have updated the [Remove subnets](https://github.com/nest/nest-simulator/projects/2) project to point to the code where the work takes/took place.

**Comment by jougs** [comment]
To my mind this issue does not contain much valuable information. I'm thus closing it for the sake of less clutter in the tracker. @heplesser: feel free to re-open if you think differently.
