### ISSUE TITLE
NEST allows multimeter connections to devices that do not support recording

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#578]
### Description of problem
NEST allows connections to devices that do not support recording.

### Version-Release or Git commit
Master @ 782d30a

### How reproducible?
Always

### Steps to Reproduce
```IPython
In [3]: scg = nest.Create('step_current_generator', params={'amplitude_times': [10., 50.], 'amplitude_values': [100., 200.]})
In [5]: mm = nest.Create('multimeter', params={'record_from': ['amplitude']})
In [6]: nest.Connect(mm, scg)   # Error message expected here
 In [7]: nest.Simulate(100)
n [8]: nest.GetStatus(mm)
Out[8]: 
({'events': {'amplitude': array([], dtype=float64),
   'senders': array([], dtype=int64),
   'times': array([], dtype=float64)},},)
```

### Actual results
- No error message, `events` dictionary has empty entries after simulation.
- No connection is created (checked by `nest.GetKernelStatus()['num_connections']`)

### Expected results
Error message upon `Connect` expected.

### Additional info
- The same problem also applies to other generators such as `dc_generator` and `spike_generator`.
- NEST issue a proper error message when trying to connect a multimeter with non-existing recordable to `iaf_psc_alpha`.

**Comment by hakonsbm** [comment]
Additionally, there are similar cases where an attempt to create a connection fails silently, such as when connecting a generator, voltmeter, subnet or volume_transmitter with each other or with themselves. The source of this behaviour lies in [`ConnectionManager::connect`](https://github.com/nest/nest-simulator/blob/master/nestkernel/connection_manager.cpp#L364) which simply calls `return` when it finds that there is no connection to be made. 

I have therefore tried replacing the guilty `return` function with a `throw IllegalConnection`. However this makes the regressiontest issue-211.sli fail, because it tries connecting a spike_generator with itself in [line 72](https://github.com/nest/nest-simulator/blob/master/testsuite/regressiontests/issue-211.sli#L72).

@jakobj Is there a special reason for the test to try creating this connection?

**Comment by jakobj** [comment]
@hakonsbm, sorry I just stumbled over this issue again. No, I think if you throw an exception, there is no reason to keep that test. That connection should not be possible, and you can maybe even add a test that makes sure that an exception is thrown.

**Comment by heplesser** [comment]
See also #663 and #658, which add recording to many stimulation devices. That may require adjustment to tests once #663 is merged.
