### ISSUE TITLE
Py3.6: invalid mode for dlopen()

### ISSUE THREAD

**Issue by Silmathoron** [nest/nest-simulator#632]
With Python 3.6, loading ``pynestkernel.so`` with dlopen cannot be done with the actual ``__init__.py``

```python
try:
    try:
        import dl
    except:
        import DLFCN as dl
    sys.setdlopenflags(dl.RTLD_NOW | dl.RTLD_GLOBAL)
except:
    # this is a hack for Python 2.6 on Mac, where RTDL_NOW is nowhere
    # to be found. See trac ticket #397
    import ctypes
    sys.setdlopenflags(ctypes.RTLD_GLOBAL)
```

With Py3.6, then correct call (or at least one that seems to work) is:
`` sys.setdlopenflags(os.RTLD_GLOBAL)`` (see [PyDoc](https://docs.python.org/3/library/sys.html#sys.setdlopenflags))

A correction could be

```python
try:
    try:
        import dl
    except:
        try:
            import DLFCN as dl
        except:
            import os as dl
    sys.setdlopenflags(dl.RTLD_NOW | dl.RTLD_GLOBAL)
except:
    # this is a hack for Python 2.6 on Mac, where RTDL_NOW is nowhere
    # to be found. See trac ticket #397
    import ctypes
    sys.setdlopenflags(ctypes.RTLD_GLOBAL)
```

If I understand correctly the [doc](https://docs.python.org/3/library/os.html#os.RTLD_GLOBAL), I think the dl flags were switch in ``os`` from 3.3, but I don't know if we can do better since I don't know what versions ``DLFCN`` is supposed to cover.

**Comment by heplesser** [comment]
@Silmathoron Thank's for your detective work. Actually, [`dl` has been deprecated since 2.6](https://docs.python.org/2/library/dl.html), and we definitely do not support anything before that, so `dl` (and `DLFCN`) should go. Under 2.x, we then need to use `ctypes` and under 3.x `os`. Also, `os` provides `RTLD_NOW` on the Mac, while `ctypes` doesn't. I will post a PR shortly.
