### ISSUE TITLE
Trailing tab in output files of weight_recorder

### ISSUE THREAD

**Issue by mschmidt87** [nest/nest-simulator#674]
The `weight_recorder` introduced in #497 stores the recorded events in a tab-separated file. It introduces a trailing tab in each line. This is certainly a tiny detail but it causes some trouble when loading the data.
For instance, when I'm trying to load the data using the pandas library, e.g. using
    
    pd.read_csv('weights.csv', sep='\t')

this leads to errors in the create data object because the routine misinterprets the trailing tab to precede a data entry. To my understanding, trailing separators also violate the definition of the csv/tsv format. 
I therefore suggest to get rid of the trailing tab, which can be easily done by changing line 732 in recording_device.cpp . I will create a pull request for this.

**Comment by mschmidt87** [comment]
Actually, I came across the same problem in the output files of the `spike_detector`, which also prints a `\t` at the end of each line. The case here is a little more complicated because this detector has multiple options regarding its output. For instance, it can also print time in steps and then give the offset to the simulation step in addition (if `precise_times` is set to `True`). Thus, one has to built in more control statements in the `print_time_` function in `recording_device.cpp`.

My proposed solution in #675 is not general enough, because the field `weight` is not only used by the weight_detector and does not necessarily appear at the end of the line in the output files. What about introducing a flag `end_of_line` for each print function that determines whether to print a separator or not.

Or should we just keep the current procedure and accept this inconsistency?

**Comment by heplesser** [comment]
I originally designed the output format with trailing tab for simplicity. In this way, one can always append more output to a line without having to check whether one is at the beginning of a line or not. I did not realize then that trailing whitespace may lead to problems elsewhere. Since any type of output can be turned off (eg, we cannot rely on each line starting with a GID), each entry printed on a line must be able to "serve" as first, middle or last entry on a line.

I see two possible solutions: One is to add a flag indicating whether one is at the beginning of a line and print a tab ahead of the entry value only if not at the beginning of line. The other would be to output tabs as now, but then to delete the last character output just before outputting the end of line character; I am not entirely sure though, that that is possible in C++.

**Comment by mschmidt87** [comment]
Thanks for thinking about possible solutions. I would favor your first suggestion. However, I'd say that we can leave the functions as they are for now. Both `numpy` and `pandas` are able to deal with this trailing tab, so we don't have a use case where the current file format fails and can stick with the simple procedure that is currently implemented.

**Comment by heplesser** [comment]
@mschmidt87 Okay, I will close the issue and the PR then. Once we have the coming NESTIO infrastructure in place, the problem should disappear anyways.
