### ISSUE TITLE
PyNEST Tests complain about missing files when not using Nosetests

### ISSUE THREAD

**Issue by terhorstd** [nest/nest-simulator#677]
when running `make installcheck` on a system with Nosetests not configured properly, a file is not found. Nevertheless the suite returns no failed test.

```
Phase 7: Running PyNEST tests.
------------------------------

  Nosetests unavailable. Using fallback test harness.
  Fewer tests will be excuted.

python: can't open file 'test_sp/mpitest_issue_578_sp.py': [Errno 2] No such file or directory
python: can't open file 'test_sp/mpitest_issue_578_sp.py': [Errno 2] No such file or directory
  Running test test_DivisionByZero...
  Running test test_InvalidGIDCollection...
  Running test test_Raise...
```

**Comment by heplesser** [comment]
When running with Nosetests available, the tests in `mpitest_issue_578_sp.py` are not executed at all.

I am wondering if we should (a) remove support for anything except nosetest (which is pretty standard today) and (b) double-check that nosetests really finds all our tests. I will create a new issue for this.

**Comment by heplesser** [comment]
Defer until we have a decision on #761.

**Comment by heplesser** [comment]
@stinebuu Could you check if your recent work on tests solves this problem? 

We should probably close this issue, since it is superseded by our move towards pyest.

**Comment by stinebuu** [comment]
@heplesser The testsuite does not complain about the missing file with #1019. I tried the master testsuite without Nosetests as well, and I do not get a complaint about `mpitest_issue_578_sp.py` there either, so it might just be my configurations or something that does not lead to a complaint, but I still think it is safe to close the issue.

As you said in a comment above, the test `mpitest_issue_578_sp.py` is not executed at all, with or without Nosetests. Probably because of its name. The test fails when I try to run it by hand. I can fix it, make it run with the testuite and make a PR.

**Comment by heplesser** [comment]
@stinebuu Please fix the test and make it run.
