### ISSUE TITLE
SHA256 changed for 2.12.0 since release

### ISSUE THREAD

**Issue by physicalist** [nest/nest-simulator#687]
There is surely a simple explanation, but it seems that the sha256 for nest-2.12.0.tar.gz has changed sometime after it was released. This issue surfaced in @tammoippen's PR, [homebrew-science/#5293](https://github.com/Homebrew/homebrew-science/pull/5293). I still had the 'original' in my Homebrew cache (sha256: 6b5ca7680f758...), and comparing it to the currently linked file (sha256: bac578f38bb06...) yielded no actual difference in the extracted files. The .tar archives are different though, among other things the base directory in the 'original' is `nest-simulator-2.12.0` instead of simply `nest-2.12.0`, and the size of the .tar.gz files differ by roughly 100kb due to that.
I guess the takeaway message from this is: if you update the archive after release, mention it somewhere, and update the Homebrew formula to reflect it :)
(I'm actually surprised nobody complained yet that Homebrew refuses to build NEST due to the sha256 mismatch!)

**Comment by heplesser** [comment]
@jougs @steffengraber Could this be due to the fix for archive/path name inconsistencies that you applied?

@physicalist @tammoippen Homebrew support for NEST is an "spare time effort" by the small number of Mac enthusiasts in the otherwise very linuxy NEST developer community.

**Comment by physicalist** [comment]
@heplesser Yes and you may count me into this small number of enthusiasts ;)
I have written my own NEST formula in the past but it was never fit for production (I just noticed for the first time that @tammoippen based his formula on my long-forgotten PR, yay!).
The above was by no means a critique, there are not enough words to express my gratitude towards the NEST developers and contributors. My humble intention here was to say, OK we learned something, and to write it down for future reference (i.e., for the Google memory ;-] ).

**Comment by iMichka** [comment]
Hi. I'm one of the homebrew maintainers.

@heplesser don't worry, we are not asking the nest maintainers to update the formula. This is up to the homebrew users/maintainers to take care of this. So @physicalist 's wish that you should do is not exactly how it is supposed to work. In general everything works fine and upstream should not be bothered with packaging problems. That's our role :)

The point which is more annoying here is the sha256 change. I guess the tag was moved from one commit to a different one. We do have this check for security reasons: if the sha256 changes this means the upstream sources have changed. This can be due to:
- the upstream server got hacked (really bad)
- somebody moved a git tag (this being 99% of the cases we see)

There is no harm to make mistakes, and release a version which has a bug. This happened to me too on my own open source projects. The right policy is to push a fix, create a new tag and a new release.
It has also the advantage that on the homebrew side, we do not try to chase a moving target.

Also, as this is a science-oriented project, it is good for reproducible science to not move tags around. In the worst case I could publish a paper tomorrow saying I used version X.Y; but that now points to a different commit and the results are slightly different. Not a funny situation to be in. But I digress.

So no offense here; we will update nest with the new sha256. If this happens more often we will just mirror the current tar file to make sure our builds are working. We just try to sensibilise maintainers when this happens.

@physicalist nobody complained about it because most people install with default options, and get prebuilt binaries through the bottles. These have their own sha256 :)

**Comment by apeyser** [comment]
Yup, it's probably a good idea to have nest-X.Y.Z.0 and nest-X.Y.Z.1... even for trivial changes, since these don't (shouldn't) happen that often. Even if it's not a bug and "should" make no difference, just to minimize confusion of the "Hey, the path changed" type.

Thanks @iMichka for the suggestion.

**Comment by physicalist** [comment]
@iMichka @apeyser Great suggestions. Bumping the revision is an even better approach than my late-night bleary-eyed "idea" ;)
@iMichka you have a point regarding the bottles. I just assumed more people were using the Python bindings, but I guess they all updated right away when the sha256 hadn't changed yet :)
In any case, thank you @iMichka for taking the time & effort!

**Comment by heplesser** [comment]
@iMichka @tammoippen @physicalist @jougs What happened is that we just exchanged the nest-2.12.0.tar.gz tarball on Github, changing the name of the top level directory inside the archive from nest-simulator-2.12.0 to nest-2.12.0, so that the name of the unpacked directory is consistent with the name of the archive. The content did not otherwise change and we did not move a tag.

The question concerning the NEST homebrew formula is then maybe if it should refer to this manually uploaded tarball or whether it should rather use the tarball that Github creates automatically. We upload our own tarball in addition, because at least under certain conditions (eg download using wget), the Github-created tarball is downloaded as just v2.12.0.tar.gz with no "nest-simulator" in it.

**Comment by jougs** [comment]
Sorry for causing this confusion. I've recently exchanged the manually uploaded tarball to fix a path inconsistency with previous releases of NEST, not knowing that you relied on the SHA of that file.

I guess it would in general be more safe for you to just use [the other tar.gz](https://github.com/nest/nest-simulator/archive/v2.12.0.tar.gz) for packaging, as that is auto-created by GitHub to always contain master at time of the tag.

@terhorstd and I were actually even thinking of not providing our own `make dist` generated tarballs anymore after the 2.12.0 release, as the content does not really differ from the one provided by GitHub.
