### ISSUE TITLE
nest.test() failed

### ISSUE THREAD

**Issue by shlomita** [nest/nest-simulator#690]
Hi,

I install NEST 2.12.0 on centos7, running python 2.7.12.

When I run 
    _nest.version()_ 

I get: 
    _u'N\x00E\x00 2\x00.\x001\x00'_

When I run 
    _nest.test()_

I get: 
     _...
     self.assertIn('SE2', neuron_synaptic_elements)
AssertionError: 'SE2' not found in {u'S\x00E': {u't\x00a\x00u\x00_\x00v\x00': 0.1, u'z': 10.0, u'z\x00_\x00c\x00o\x00n\x00n': 0, u'e\x00t': 0.1, u'c\x00o\x00n\x00t\x00i\x00': True, u'g\x00r\x00o\x00w\x00t\x00h': 1.0, u'e\x00p': 0.7, u'g\x00r\x00o\x00w\x00t\x00h\x00': u'g\x00a\x00u\x00s\x00'}}
    ... 
    Ran 229 tests in 3.002s
    FAILED (failures=19, errors=154, skipped=6)_

What can cause the problem?

Thanks.

**Comment by heplesser** [comment]
This looks strange and I cannot reproduce it on OSX 10.11 with Python 2.7.12. It looks a bit as if it could be a unicode problem, somehow lots of 0-bytes popping up inside strings. Could you provide the configuration report provided at the end of the `cmake` run? What happens when you run `make installcheck` in the build directory?

I assume Python is working fine otherwise?

**Comment by shlomita** [comment]
Hi,

We have few version of python installed on the system + the python came with the Operation System.
Each user can work with any python he like.

I need to install Nest and then users can run it from any python they choose.
With one of the python 2.7, then can run it okay but with the other not and get the error I sent in my previous message.

I tried to compile Nest again to give you the logs, but I did not success to recompile it.
Anyway, with one of version, that came with the OS, I got:
Building CXX object sli/CMakeFiles/sli_lib.dir/typechk.cc.o
Traceback (most recent call last):
  File "generate_help.py", line 102, in <module>
    require = check_ifdef(item, filetext, dcs)
  File "/apps/src_7/shlomit/nest/nest-simulator/extras/help_generator/helpers.py
", line 48, in check_ifdef
    require_reg = re.compile('HAVE\_((.*?)*)\n')
  File "/usr/lib64/python2.7/re.py", line 190, in compile
    return _compile(pattern, flags)
  File "/usr/lib64/python2.7/re.py", line 242, in _compile
    raise error, v # invalid expression
sre_constants.error: nothing to repeat
make[2]: *** [generate_help] Error 1
make[1]: *** [doc/CMakeFiles/generate_help.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Linking CXX shared library libsli.so
[ 27%] Built target sli_lib
make: *** [all] Error 2

with other version of python, cmake it gives warning:
Could NOT find PythonLibs: Found unsuitable version "2.7.5", but required is
exact version "2.7.12" (found /usr/lib64/libpython2.7.so
It not found the library that installed in different place then the default system.
It did not create the subdirectory lib64/python2.7 in nest installation directory. so I have under nest/lib64 only files lib*.so.

Anyway attach log of the second situation.

All python looks like work okay.

Thank you for your prompt response.

**Comment by heplesser** [comment]
@shlomita Python 2.7.5 has a bug in its regular expression module. You need at least version 2.7.8 for help generation to work, see post my Nilton Kamiji on NEST User on 8 March.

Furthermore, you cannot mix NEST with different Python versions. If you compile NEST with a given Python version, you can only use that version of NEST with the same Python version. You can build NEST in separate directories for different Python versions, but you then must make sure that the users set all paths correctly before starting Python. To help users with this, NEST creates a `nest_vars.sh` script in the directory where the NEST binary is installed. You need to source this file, as described as the end of the Configuration Report provided by CMake:
```
To set necessary environment variables, add the following line
to your ~/.bashrc :
  source /path_to/nest/2.12.0X/bin/nest_vars.sh
``` 

To avoid any interference due to cache files and similar, I strongly recommend that you delete the entire build directory and recreate it before you attempt a new build.

**Comment by heplesser** [comment]
@shlomita Have you been able to solve this problem by re-compiling? If so, please close the issue.

**Comment by shlomita** [comment]
It work only with python I compile NEST with.
