### ISSUE TITLE
NEST Deadlock if exception thrown in update

### ISSUE THREAD

**Issue by maharjun** [nest/nest-simulator#718]
It Appears that the following situation leads to a deadlock in the v2.12.0 commit. When an exception is raised on any one thread and not on the other thread in the same simulation slice, the loop for that thread only is terminated by the following condition in the while loop. The rest of the threads then stall on the next barrier leading to a deadlock.

```c++

    } while ( to_do_ > 0 and not exit_on_user_signal_
      and not exceptions_raised.at( thrd ) );

```

On a related note, how feasible would it be to implement error handling across MPI Processes? (For example by sending an additional integer during the allgather to signal the state (Error or not) of the MPI Process and then conditionally (i.e. if any one process is in an error state)  gather the exception message and throw a consistent exception across processes?

**Comment by heplesser** [comment]
@maharjun Thank you for reporting this. Do you have a reproducer that we could use as the basis of a regression test?

I believe that the fix is reasonably straightforward: We can introduce a loop in the `omp master` section beginning at [simulation_manager.cpp:837](https://github.com/nest/nest-simulator/blob/7d3c92fca72f11bc7761a3209983d0d28edd3736/nestkernel/simulation_manager.cpp#L837) to check if any thread has raised an exception and set a flag accordingly that is then checked at oin the `while` condition.

**Comment by maharjun** [comment]
I have code in the following repository that causes a deadlock, although I'm not sure one detects a deadlock in a unit test, I have the  neuron model and network setup with all the instructions to install and test at the following branch of my repository

https://github.com/IGITUGraz/SpikeDetectorFuse/tree/NESTExceptionDeadlockTest
