### ISSUE TITLE
Threading Issues When OMP_NUM_THREADS != local_num_threads

### ISSUE THREAD

**Issue by kennysharma** [nest/nest-simulator#725]
### Description of problem:
If you use Nest within a multi-threaded application where any thread can create connections AND you have the environment variable `OMP_NUM_THREADS` set to a different value than `local_num_threads` in the Nest kernel, you will encounter issues such as `Connect(...)` calls succeeding despite not actually creating the underlying connections.

It appears as though this was considered in some of the nest kernel, but not all as files - e.g. `nestkernel/connection_manager.cpp` includes a safeguard to manually set `OMP_NUM_THREADS`:

```C++
#ifdef _OPENMP
  std::string msg;
  msg = String::compose( "Setting OpenMP num_threads to %1.", net_.get_num_threads() );
  net_.message( SLIInterpreter::M_DEBUG, "ConnectionManager::get_connections", msg );
  omp_set_num_threads( net_.get_num_threads() );
#endif
```

within the `get_connections` method.

This safeguard code is absent in `nestkernel/conn_builder.cpp`, meaning execution from a different thread that has a different `OMP_NUM_THREADS` environment variable set causes connections to not actually be made. For example if `OMP_NUM_THREADS=1` but `local_num_threads=8`, only that first thread will be checked to see if a connection can be made.

Further, there are no checks to ensure that connections are actually made after iterating "all" threads, so the various `connect_` methods return successfully even though no connection was made. It may be good to ensure that at least one thread makes it through all of the various cases to call the connection creation method. There are likely other areas impacted by this, but this was the first issue that we encountered.

Our use case and application is rather specific (Human Brain Project Neurorobotics Platform), but I suspect this could be encountered in other multi-threaded applications.

### Version-Release or Git commit:
Nest 2.10.0 used for debugging, but also tested against 2.12.0 release and latest commit 7d3c92fca72f11bc7761a3209983d0d28edd3736

### How reproducible: (Always/Sometimes/Unsure)
Always

### Steps to Reproduce:
1. In a Bash terminal:
`export OMP_NUM_THREADS=1`

2. Run this script in the same terminal:

```python
import nest
from threading import Thread

nest.SetKernelStatus({'local_num_threads': 8,
                      'resolution': 0.1})

population = nest.Create('iaf_psc_alpha', 2)

def connect():
  generator = nest.Create('poisson_generator')
  nest.CopyModel('static_synapse', 'excitatory', {'weight': 0.00015, 'delay': 0.1})
  nest.Connect(generator, population, syn_spec='excitatory')

thread = Thread(target=connect)
thread.start()
thread.join()

assert len(nest.GetConnections()) == 2, 'Connection was not created!'
```
3. This should produce an AssertionError.

4. If you `export OMP_NUM_THREADS=8` and rerun, there will be no error.

### Actual results:
No connections are created and no errors are produced within Nest (via PyNN (see below) this does produce an error because it assumes the connection was created).

### Expected results:
A pair of connections should have been created.

### Additional info:
You can workaround this issue by ensuring if `OMP_NUM_THREADS` is in your environment, it matches the number of threads you set in the Nest kernel.

PyNN equivalent script (for completeness):
```python
import pyNN.nest as sim 
from threading import Thread

sim.setup(timestep=0.1, min_delay=0.1,threads=8)

population = sim.Population(size=2, cellclass=sim.IF_cond_alpha())

def connect():
  generator = sim.Population(1, sim.SpikeSourcePoisson())
  sim.Projection(presynaptic_population=generator,
                 postsynaptic_population=population,
                 connector=sim.AllToAllConnector(),
                 synapse_type=sim.StaticSynapse(weight=0.00015, delay=0.1))

thread = Thread(target=connect)
thread.start()
thread.join()
```

**Comment by heplesser** [comment]
@kennysharma Thank you for your very detailed report! I can reproduce this with the current master on MacOS and made the following observations:

- All works well with `OMP_NUM_THREADS` from 3 to 8; things go well from 3 most likely because there are only two neurons.
- For `OMP_NUM_THREADS` greater than 8, the script leads to a segmentation fault.
- The call to [`omp_set_num_threads()` in `connection_manager.cpp`](https://github.com/nest/nest-simulator/blob/7d3c92fca72f11bc7761a3209983d0d28edd3736/nestkernel/connection_manager.cpp#L1118) is, as far as I can see, meaningless, because the number of threads is
    -  [fixed during a simulation](https://github.com/nest/nest-simulator/blob/7d3c92fca72f11bc7761a3209983d0d28edd3736/nestkernel/vp_manager.cpp#L59)
    - initialized to [1 when `vp_manager` is initialized](https://github.com/nest/nest-simulator/blob/7d3c92fca72f11bc7761a3209983d0d28edd3736/nestkernel/vp_manager.cpp#L61)
    - modified only [when `local_num_threads` is changed](https://github.com/nest/nest-simulator/blob/7d3c92fca72f11bc7761a3209983d0d28edd3736/nestkernel/vp_manager.cpp#L129)

I suspect that the problem may arise from your combination of threading in NEST with threading at the Python level using the `threading` module. This is a use case that we have so far never considered in the design of NEST and I have at present no idea of the consequences.

It may be useful to discuss this in the next [NEST Developer Video Conference](https://github.com/nest/nest-simulator/wiki/2017-05-29-Open-NEST-Developer-Video-Conference).

**Comment by kennysharma** [comment]
> The call to omp_set_num_threads() in connection_manager.cpp is, as far as I can see, 

From my testing, if I insert a call to `omp_set_num_threads` (the same block of code I referenced above) into the top of `nest::ConnBuilder::connect()` in `nestkernel/conn_builder.cpp` and re-compile, I no longer get an error in the test code at least with my local Nest 2.10.0 build.

I commented it out again and rebuilt in the same terminal to verify it wasn't some lingering variable and the issue reappeared, so it is doing something at some level.

Even more interesting was that the nest kernel knows `net_.get_num_threads()` is 8 in those code blocks, but only one thread is running without a call to `omp_set_num_threads` before the `#pragma omp parallel`. I'm equally confused as to why that would be an issue. I'll let you know if I have an opportunity to look further into it.

**Comment by heplesser** [comment]
Just a speculation: NEST relies on omp_dynamic being set to false, so that the number of threads remains fixed. If Python's threading package changes that setting to true or explicitly changes the number of threads (e.g. based on OMP_NUM_THREADS), then NEST will be in trouble when control returns to NEST. Inserting explicit omp_set_num_threads() calls in certain places in NEST code would fix this. 

If this is the case, we should think about a clean approach to ensuring stable thread numbers in NEST instead of spreading omp_set_num_threads() calls throughout the code.

**Comment by kennysharma** [comment]
As a followup (and for additional context for the NEST Developer Video Conference), it appears that we have OMP_NUM_THREADS explicitly set to avoid segmentation faults in Nest that occur when the number of threads is confused. I was not part of the team back then, but it's quite easy to produce crashes in a few different places.

Here's a minimal example to produce crash (tested against Nest 2.10.0 again):

```python
import nest
from threading import Thread

nest.SetKernelStatus({'local_num_threads': 1}) 

population = nest.Create('iaf_psc_alpha', 1)

def run():
  nest.Simulate(1.0)

thread = Thread(target=run)
thread.start()
thread.join()
```

This is a trivial example where you want to keep the blocking Nest calls on a separate thread while your main application handles user input or any other tasks.

This particular crash is in `nest::Scheduler::prepare_nodes()`, but it's also possible to produce errors where Nest crashes trying to index RNG seeds at an index greater than the number supplied (PyNN explicitly requires/sets the RNG seeds when setting `local_num_threads`).

**Comment by heplesser** [comment]
This will become easier to solve once we implement a strict logical separation between virtual processes and open mp threads; currently in early stages in connection with NEST3 work.

**Comment by kennysharma** [comment]
A brief followup, I am currently testing the most basic solution in our local Nest 2.10 fork of adding:

```c++
#ifdef _OPENMP
  omp_set_num_threads( net_.get_num_threads() );
#endif
```
to any methods containing omp pragma statements:

```c++
#pramga omp parallel
#pramga omp critical
```
and everything appears to be working and performing properly (though we'll need to do a bunch of regression testing to make sure).

I know this isn't a "clean" solution that would be accepted upstream, but it will serve as a temporary stop-gap measure for our needs. We'll look forward to testing with Nest 3.0 in the future with the proper solution.

**Comment by jougs** [comment]
The fundamental problem here is that there is no (and in general can't be) well-defined behavior if two "applications" in the same process use conflicting thread configurations.

NEST was not at all designed for a use case like this. It heavily relies on the fact that the number of threads is completely under its own control. Even with guards like proposed [above]( https://github.com/nest/nest-simulator/issues/725#issuecomment-320591352) in place one can't be sure that things like the ownership of data structures by threads are preserved, which might ruin cache utilization and in sequence could be detrimental to performance.

The proper way to go here is to use multi-processing (e.g. via Python's [multiprocessing](https://docs.python.org/2.7/library/multiprocessing.html) module) and have NEST run in one process and everything else in another.

**Comment by Silmathoron** [comment]
Hey @jougs, I'm also encountering some segfault errors due to mostly harmless combinations of NEST import with other CPP-interfaced python libraries and, before I open a new issue and start a PR about it, I would like to understand what you mean about the "ownership of data structures by threads".

I sounds weird to me (I've never heard of threads "owning" anything), and as far as I've looked, we keep everything in stl containers which are perfectly safe regardless of the thread number.
On the other hand, the way these containers are currently addressed is not resilient against changes in the number of threads, but this does not seem to be a major issue (it just requires some rewriting of several parallel sections).

Am I missing something? Also I thought I remembered some people were actually working on making these changes, have there been news from them?

**Comment by jougs** [comment]
I'm following up here just for the record, despite this issue being ancient and closed.

What I meant by "ownership" is the fact that a data structure is allocated in the memory attached to the core a thread is running on when it creates the data structure. The reason for this being that accessing data on non-local memory is much more costly than it is for local memory.

NEST performance and scaling is to a large part as good as it is, because we heavily exploit this so-called first touch principle by having all essential data structures once per thread. For this to work well, we also expect hat threads don't change identity or (worst case) migrate to other cores, where their data is not thread-local anymore, which would in turn require expensive data transfers and usually thrashes the caches of the pertaining cores and thus ruins performance.

I hope that this is clearer than what I wrote before.
