### ISSUE TITLE
Feature needed: neuron updating weights

### ISSUE THREAD

**Issue by sepehrmn** [nest/nest-simulator#764]
I need the neuron to perform the computations for updating weights and have it set the weight on each synapse. I would also need to access connection weights (but I suppose this could be stored during the network creation time). One way to do so would be to try to get a pointer for each incoming connection on the neuron. There are two different synapses. At some point during the simulation, I would rewire the network, switch synapse types, and perhaps add new connections. 

One concern is how the connectome memory management is handled (i.e., if I store pointers, and the underlying data structure is a vector, the pointers would become invalid if, for example, a new element is added to the connectome).  I was first thinking about doing it during network creation using the rport but std::vector memory copies would make this not work. but now I'm thinking about a function that neurons can call on the connection manager (in calibrate) to get pointers.

This is required only for a specific and a bit different model currently under development as part of an HBP project. I am opening this issue to determine the best way to implement this.

**Comment by SepehrMN** [comment]
@jougs @heplesser @apeyser Would you please be so kind as to comment as soon as convenient? I need this feature very soon. I can implement a solution that does not involve a major rework. I think it would be best that I receive suggestions from the NEST core people who have worked on the kernel.

**Comment by apeyser** [comment]
@SepehrMN I don't think @jougs and @heplesser are around for a few more weeks, and they know the connection infrastructure better than I do.

Maybe @suku248 or @abigailm can make a suggestion? How can @SepehrMN get access to the synaptic models from inside the neuron model? Or visa-versa? (that may be a better approach).

**Comment by heplesser** [comment]
@SepehrMN Could you provide more information on the model you are attempting to implement, maybe provide a reference to a paper describing the model? 

Generally, access to the incoming synapses of a neuron is difficult, since synapses are sorted by sender neuron in memory. Keeping pointers to synapses is dangerous indeed, since those pointers would be invalidated by memory reallocation during network construction. But each connection is uniquely specificied by the tuple `(sender gid, target thread, synapse type, port)`. That tuple can be used to index the connection infrastructure via `kernel().connection_manager.[set|get]_synapse_status()`. The problem is that the target neuron at present has no way of obtaining the `port` number. `Connection< targetidentifierT >::check_connection_()` would have to send `port` along when calling `source.send_test_event( target, receptor_type, get_syn_id(), false )`. Then the target neuron could, on every call to its `handles_test_event()` store the necessary index information and use that table to access connections later.

For this to work, `GenericConnectorModel< ConnectionT >::add_connection()` would have to check the `conn` connector passed to it for the number of connections of the given synapse type that it contains already and then pass this number as `port` (i.e., the index of the next connection to be registered in `conn`).

**Comment by SepehrMN** [comment]
@heplesser Many thanks! I will investigate this!

This is related to #606. The information-theoretic framework for creating goal functions for neurons is described in [1]. The theoretic background is described in [2]. The neuron model I currently have implemented in Python to work with it, which I will submit for merging once it is fully in C++, is described in [3] and studied further in [4][5][6].

   [1] M Wibral, V Priesemann, J W. Kay, J T Lizier, W A Phillips, (2017). Partial information decomposition as a unified approach to the specification of neural goal functions. Brain and Cognition.
   [2] N Bertschinger, J Rauh, E Olbrich, J Jost, N Ay, (2014). Quantifying unique information. Entropy.
   [3] J Kay, WA Phillips (2011). Coherent infomax as a computational goal for neural systems. Bull Math Biol.
   [4] J Kay (1994). Technical Report, Biomathematics and Statistics Scotland
   [5] J Kay and WA Phillips (1994). Technical Report CCCN-15.
   [6] D Smyth, J Kay, WA Phillips (1996). Network: Computation in Neural Systems.

**Comment by sepehrmn** [comment]
I am working on making a pull request and closing this issue. There have been changes in NEST and also the model which I will discuss there.
