### ISSUE TITLE
random number generator in noise generator

### ISSUE THREAD

**Issue by wangsihao** [nest/nest-simulator#790]
Hi

In nest, I want to test different noises generated by noise generator with same parameter, how can I set seed to generate different noises, it seems right now the noises generated by same parameters are  same. Thanks

**Comment by mschmidt87** [comment]
Hi,
in order to obtain different realizations of noise, you have to set the seeds for the random number generators of NEST. 

In your case, you would need to do
`nest.SetKernelStatus({'rng_seeds': 123})`
and then vary the value of the seeds between trials to obtain different realizations.

In the documentation on nest-simulator.org, you will find a complete explanation of random numbers in NEST: [http://www.nest-simulator.org/random-numbers/](http://www.nest-simulator.org/random-numbers/).

If you have further problems, please use the NEST-USER mailing list (see [here](http://www.nest-simulator.org/community/) ).
