### ISSUE TITLE
Make of extension module fails while linking

### ISSUE THREAD

**Issue by flinz** [nest/nest-simulator#794]
I am trying to convert a synapse model previously written to be part of the nest-core (https://github.com/nest/nest-simulator/pull/544) to a contributed module.

Please find the source code in https://github.com/flinz/nest-module-STDPStructplast).

The build works fine up until linking the resulting shared library, where i fails with:
```bash
[ 50%] Linking CXX shared library libstdp_structpl_module.dylib
Undefined symbols for architecture x86_64:
  "nest::ConnectorModel::ConnectorModel(std::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, bool)", referenced from:
      void nest::ModelManager::register_connection_model<stdpstructpl::STDPStructplConnectionHom<nest::TargetIdentifierIndex> >(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) in stdp_structpl_module.cpp.o
      void nest::ModelManager::register_connection_model<stdpstructpl::STDPStructplConnectionHom<nest::TargetIdentifierPtrRport> >(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) in stdp_structpl_module.cpp.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[2]: *** [src/libstdp_structpl_module.dylib] Error 1
make[1]: *** [src/CMakeFiles/stdp_structpl_module_lib.dir/all] Error 2
```

I am building on OSX with gcc/gxx 4.9. Here is a more explicit [log of build process](https://github.com/nest/nest-simulator/files/1190907/buildlog.txt). I have also tried including both ``nest_install/lib/`` and ``mmb/src`` in my DYLD_LIBRARY_PATH, to no avail.

I think it might possibly be some issues with namespaces.. I would be grateful for any help.

**Comment by heplesser** [comment]
@flinz Do you get the same linker error when building the example `MyModule` included? I tested your module code  with my build setup and it linked (macOS 10.12.6, gcc 7.1.0 from Homebrew). Thus I think that you hunch that this may be related to namespaces may be right. 

Is there any chance you could test with a newer compiler? It could also be useful to run `make VERBOSE=1` to see the actual compiler and linker invocations with all options.

Note that the model name in `..._LTX_mod` [defined here](https://github.com/flinz/nest-module-STDPStructplast/blob/4d7745d3cee14748998b2a0a5edad11220307ffc/src/stdp_structpl_module.cpp#L72) must be identical to the module file name:
```c++
stdpstructpl::STDPStructplastModule stdp_structpl_module_LTX_mod;
```
Otherwise, you will get an unspecific dynamic module loader error when running `(stdp_structpl_module) Install`.

With that fix in place, the module begins to load, but then fails to run the SLI file for the module because `InitSynapseUpdater` is not defined.

**Comment by flinz** [comment]
Of course I didn't check the obvious first - gcc4.9 apparently has problems building even the MyModule example. [Here is the verbose output,](https://github.com/nest/nest-simulator/files/1193497/buildlog2.txt) should you want to follow this up further..

With AppleClang 8.0.0.8000042 the example works. I will follow up with news on compiling my own module.

**Comment by heplesser** [comment]
@flinz Thanks for checking. Given that gcc-4.x is dated and this problem appears to be specific to macOS, I think I need to focus my energies elsewhere. I will thus close this issue.
