### ISSUE TITLE
`parrot_neuron` should exploit spike multiplicity

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#82]
`parrot_neuron` currently emits spikes using a loop

```
for ( ulong_t i_spike = 0; i_spike < current_spikes_n; i_spike++ )
  network()->send( *this, se, lag );
```

This is inefficient---why don't we use multiplicity and make just a single `network->send()` call?

**Comment by flinz** [comment]
Since i am already working on the parrot_neuron, I changed this to use multiplicity (see the branch https://github.com/flinz/nest-simulator/tree/issue-parrot_neuron-multiplicity) and added a test to confirm. 

This branch is based off my branch already containing new tests for the parrot neuron (https://github.com/flinz/nest-simulator/tree/parrot-multiport), so I will open a pull request once that one is merged.

**Comment by flinz** [comment]
@heplesser I think this can be closed, since a fix was merged.

**Comment by jougs** [comment]
Definitely.
