### ISSUE TITLE
Uniform distribution of delays isn't uniform

### ISSUE THREAD

**Issue by luis-rr** [nest/nest-simulator#833]
Hi! I just ran into an odd behaviour when trying to create a uniform distribution of delays for my network. I'm new to Nest so I apologise if I'm misinterpreting the results or if this is a known issue.

_Description of problem:_

Uniform distribution of delays is not uniform. Edge values are less probable than middle ones.

_Version-Release or Git commit:_
nest-2.12.0

_How reproducible:_
Always

_Steps to Reproduce:_
This is an example, generating numbers in the **range [1-2]**
```python
import nest
import numpy as np

neurons = nest.Create("iaf_cond_exp", n=100)
nest.Connect(neurons, neurons,
             syn_spec={'delay': {'distribution': 'uniform', 'low': 1., 'high': 2.}})

conns = nest.GetStatus(nest.GetConnections())

delays = [c['delay'] for c in conns]

values, count = np.unique(delays, return_counts=True)
probs = zip(values, count.astype(np.float) / np.sum(count))

for i in [0, 5, -1]:
    print 'Probability of item %.1f: %2f' % probs[i]
```
you can also see the distribution with
```python
from matplotlib import pyplot as plt

_, plots = plt.subplots(nrows=2)
hist, bins = np.histogram(delays, bins=20)
plots[0].bar(bins[:-1], hist, bins[1:] - bins[:-1], align='edge')
plots[1].plot(np.sort(delays), 'o')
plt.show()
```
_Actual results:_
Something like
Probability of item 1.0: 0.05
Probability of item 1.5: 0.01
Probability of item 2.0: 0.05

_Expected results:_
An equal probability for all items
Probability of item 1.0: 0.090909
Probability of item 1.5: 0.090909
Probability of item 2.0: 0.090909

_Additional info:_
This sounds to me like you are generating a floating value for the delays in the whole range [1-2] and afterwards rounding it to one decimal. This is wrong because there're half as many numbers in [1-1.05] (that will get rounded to 1) than there are in [1.05-1.15] (that will get rounded to 1.1). You'd need to either, generate them between [0.95-2.05] or, better, generate integers in the range [10-20] and then divide by 10.

**Comment by heplesser** [comment]
@luis-rr Thanks for your report. I think this is traceable to `nest_time.h`

```c++
  /**
   * Convert between delays given in steps and milliseconds.
   * This is not a reversible operation, since steps have a finite
   * rounding resolution. This is not a truncation, but rounding as per
   * ld_round, which is different from ms_stamp --> Time mapping, which rounds
   * up. See #903.
   */
  static delay
  delay_ms_to_steps( double ms )
  {
    return ld_round( ms * Range::STEPS_PER_MS );
  }
```

and further `numerics.h`

```c++
/**
 * Round to nearest int, rounding midpoints upwards.
 *
 * @return Result as long
 * @note [-1/2, 1/2) -> 0 and in general [ (2n-1)/2, (2n+1)/2 ) -> n
 * @see dround
 */
long ld_round( double );
```

@jougs Could you dig out the discussion in the old trac issue trac.903 referenced above?

@hannahbos I am wondering what the most correct interpretation/solution in the context of NEST's time philosophy would be. Do you have any suggestions?

**Comment by heplesser** [comment]
The discussion on the old trac.903 issue did not contain any relevant information, it was only about the transition from always rounding up to rounding symmetrically.

This is foremost a matter of what users expect given the NEST syntax. I will put the matter on the agenda of the next Open Developer VC on 16 April.

**Comment by heplesser** [comment]
Some thoughts on this problem in preparation of the discussion in the [VC on 16 April](https://github.com/nest/nest-simulator/wiki/2018-04-16-Open-NEST-Developer-Video-Conference).

The rounding problem @luis-rr discovered arises because logically delays are a continuous quantity, while in the implementation they are a discrete quantity. We make the underlying assumption that, if we simulated the same network with increasingly finer resolution and thus increasingly finer delay distribution, then our network dynamics would converge against the limit of infinite resolution, i.e., continuous time and continuous delay distributions.

Let us now consider the unproblematic cases:
- If the delay distribution is explicitly given as a discrete distribution, we have no problem: the distribution is independent of the time resolution, requiring only that all possible discrete values are multiples of the resolution.
- If the delay distribution has infinite support (e.g. a Gaussian), we have no problem either, provided we ignore problems arising from negative delays and finite precision doubles. For any multiple of the resolution, there will always be and interval both left and right into which our random delay variable may fall, and be rounded to that multiple.

Problems only arise if we have a continuous distribution with finite (or semi-finite) support. In practice, this applies to the uniform distribution and all clipped distributions, there there is a hard cut-off. Without loss of generality, we can assume that this cut-off coincides with a multiple of the resolution. In that case, the cut-off value will be drawn with just half the probability of the multiples of resolution inside the support, as pointed out in the original post.

We consider first the uniform distribution. In that case, both approaches will yield the same mean delay, but different higher moments. Interestingly, though, for the approach currently implemented in NEST, higher moments converge quadratically towards their values for a continuous distribution as resolution is refined, while convergence is only linear for a solution for which all discrete delay values are chosen with equal probability. The next step would be a non-uniform distribution. Analysis will follow shortly.

**Comment by heplesser** [comment]
I have now performed a more detailed analysis which you will find in
[NEST_Delays_883.pdf](https://github.com/nest/nest-simulator/files/1914207/NEST_Delays_883.pdf).

This analysis shows that for at least up to the third moment, and for uniform, linear and quadratic distributions, assigning full or half weight to the corner points yields the same values in the limit of infinite resolution. Interestingly, the convergence to that limit is quadratic when assigning half weight, but only linear when assigning full weight. The same holds true for the expectations of Exp(-i omega delay), which appear in the spectral analysis of network activity (@hannahbos).

Therefore, I think we should retain the weighting that NEST currently uses. Users who want to weigh the corner points with equal probability, can do so by extending the limits by half a time step, e.g.,
```python
{'delay': {'distribution': 'uniform', 'low': 0.95, 'high': 2.05}}
```
to achieve equal probability at 1.0, 1.1, 1.2, ..., 2.0 for resolution 0.1.

**Comment by jougs** [comment]
@heplesser, @hakonsbm: has this been fixed by the new random number thingies in NEST 3.0? If yes, this should probably be closed.

**Comment by heplesser** [comment]
@jougs This is a deeper problem than just a technical fix. By next spring we should have a thorough analysis of the situation providing guidance to how to address this best.
