### ISSUE TITLE
Compiling nest 2.12.0 on debian 9 with 2 failed items in PyNEST

### ISSUE THREAD

**Issue by mmohaghegh** [nest/nest-simulator#842]
Hello,
Please find the contents of "report" directory in the compressed file attached.
Thanks a lot for the support
[reports.tar.gz](https://github.com/nest/nest-simulator/files/1405177/reports.tar.gz)

**Comment by jougs** [comment]
@mmohaghegh: The issues you are experiencing were fixed in [NEST 2.14.0](https://github.com/nest/nest-simulator/releases/tag/v2.14.0), releases on October 20, 2017. Please upgrade to the new version.

For the record: the title of this issue is misleading in that the problems are *not* actually compilation errors, but errors during the testsuite.
