### ISSUE TITLE
Precise models don't work with stdp_synapse?

### ISSUE THREAD

**Issue by apdavison** [nest/nest-simulator#85]
The following script:
```
import nest

cell1 = nest.Create('iaf_neuron')
cell2 = nest.Create('iaf_psc_exp_ps')

conn_dict = {"rule": "all_to_all"}
syn_dict = {"model": "stdp_synapse"}
nest.Connect(cell1, cell2, conn_dict, syn_dict)
```
gives
```
Traceback (most recent call last):
  File "tmp.py", line 8, in <module>
    nest.Connect(cell1, cell2, conn_dict, syn_dict)
  File "....lib/python2.7/site-packages/nest/hl_api.py", line 153, in stack_checker_func
    return f(*args, **kwargs)
  File "..../lib/python2.7/site-packages/nest/hl_api.py", line 1123, in Connect
    sr('Connect')
  File "....lib/python2.7/site-packages/nest/__init__.py", line 81, in catching_sli_run
    raise hl_api.NESTError("{0} in {1}{2}".format(errorname, commandname, message))
pynestkernel.NESTError: IllegalConnection in Connect_g_g_D_D: Creation of connection is not possible.
```
If I replace `'iaf_psc_exp_ps` with `'iaf_psc_exp`, it works fine. 

`nest.GetDefaults('iaf_psc_exp_ps')` shows no `tau_minus` parameter, and the same is true for some other precise models I looked at.

Is there a reason why `iaf_psc_exp_ps` cannot work with `stdp_synapse`? If so, please could this be documented (unless I missed the documentation). If not, please could this be implemented?

**Comment by heplesser** [comment]
@apdavison I can confirm this. It also applies to the other precise models. Technically speaking, the reason is that these models are derived directly from `Node`, not from `ArchivingNode`, whence `Node::register_stdp_connection()` throws `IllegalConnection`.

@abigailm @suku248 I am not sure if there is a deep reason for this or if it is rather an oversight? At present, the spike time history in `ArchivingNode` stores only time step information, so it would ignore precise timing information. But the spike history (`histentry`) stores spike times in ms, so it should not be too difficult to include offset information?

**Comment by abigailm** [comment]
There is no deep reason for this, I think. All that would need to happen is that that `Node::register_stdp_connection()` should act as in the non-precise models and that `set_spiketime(t)` is fed an appropriate time object that incorporates the offset
