### ISSUE TITLE
SetNumRecProcesses for weight_recorder

### ISSUE THREAD

**Issue by alberto-antonietti** [nest/nest-simulator#918]
I have noticed that the `nest.SetNumRecProcesses( )` function works only for spike_detectors and not for weight_recorders. Is that foreseen?

Having few MPI processes dedicated to the weight recording would accelerate simulations run with hundreds/thousands of MPI processes?

**Comment by heplesser** [comment]
@alberto-antonietti Unfortunately, the lack of a global weight recording possibility is a feature. Having a global spike detector is quite straightforward and cheap at runtime, since all spikes are transmitted to all MPI processes anyways. To provide global weight recording, we would have to transmit all weights, which are far more than spikes (if a neuron has a fan-out of 10.000, each spike translates into 10.000 weights).

We are working on a new IO interface for NEST that will work efficiently on highly parallel systems using SIONLIB.

**Comment by jougs** [comment]
Just a short addition: @apeyser, @wschenck and I are indeed working on a replacement for the was we write out data. The general idea is that specific backends are actually writing the data and a new backend based on [SIONlib](http://www.fz-juelich.de/ias/jsc/EN/Expertise/Support/Software/SIONlib/_node.html) allows to write the data from recorders in a binary streaming format very efficiently. We expect the code to land in master in one or two month.

As the code is currently under heavy development and the interface is still changing quite a bit, we unfortunately can't grant you access to the code at this point in time. We will, however update this ticket once the code is in a public pull request.

**Comment by terhorstd** [comment]
@jougs @apeyser  could you comment on the state of this?

**Comment by apeyser** [comment]
@terhorstd Weight recorders are more complex than all other detectors. It will have to wait for a second pass, after NESTIO is integrated.

**Comment by jougs** [comment]
`SetNumRecProcesses` and the global spike detector have been removed from NEST with the [merge of 5g](https://github.com/nest/nest-simulator/pull/920).

`weight_recorder` was re-enabled in [NESTio](https://github.com/jougs/nest-simulator/tree/nestio/) in https://github.com/jougs/nest-simulator/pull/29 and will also support efficient writing in parallel and distributed.

**Comment by jougs** [comment]
This feature request is addressed by th SIONlib recording backend, which is available in the `nest-3` branch as of the merge of #1283.
