### ISSUE TITLE
On-demand simulation model loading in NEST 3

### ISSUE THREAD

**Issue by ikitayama** [nest/nest-simulator#923]
What prevents the current ModelsModule::init() from on-demand model loading?

Not only the current form increases the build time when compiled with the Fujitsu toolchain, but as people keep adding their models in there, it will blow up in the near future.

**Comment by heplesser** [comment]
@ikitayama You raise an interesting point, which has two aspects that we may want to discuss separately. 
One is the fact that especially modelsmodule can take a very long time to compile due to the large number of models contained. It is my impression (although I have not systematically tested this), that intra-procedural optimization attempts by the compiler contribute very significantly to build time, while making little difference to runtime. To address this, one could consider compiling parts of NEST without IPO or to split modelsmodule into smaller parts that could be compiled selectively.
The other issue is the actual loading of model code when NEST is executed. Again, I have not performed any systematic analysis of how much time is spent to load NEST code. Do you have experience with this that indicates that the number of models in NEST does make a difference for the time NEST takes to start up?

**Comment by ikitayama** [comment]
@heplesser I'm not sure if the IPO is the issue, as on x86 I'm able to build NEST quickly. As documented in INSTALL file, I agree it is due to generation of many template classes during the
build. So depending on what toolchain one uses, the built time may significantly vary.

Secondly, I never took a closer look at the loading time at run time either, anyway, my point is
that the current state of models/modelsmodule.cpp doesn't look manageable from a 
code management point of view.

**Comment by heplesser** [comment]
We do not see an easy solution for this right now. I therefore close this issue for now.
