### ISSUE TITLE
Pre-release: Re-add iaf_neuron and ensure NEST 2.14 examples still run

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#942]
We deprecated `iaf_neuron` for NEST 3.0. In order to ensure that code that ran with 2.14 still runs with 2.16, we need to re-add it to the NEST 2.16 release branch (but not restore it in master). This should happen at the very end of the release preparation. Then ensure that 2.14 examples still run on 2.16 with identical examples (see #940 for directories with tests).

**Comment by heplesser** [comment]
@stinebuu Could you run this check with the newest master? Use the attached diff-file to restore `iaf_neuron` (hope it works, created the diff in May). Then see if examples from 2.14 still work.
 
[restore_iaf_neuron.diff.zip](https://github.com/nest/nest-simulator/files/2297109/restore_iaf_neuron.diff.zip)

**Comment by stinebuu** [comment]
@heplesser I have run all examples from 2.14 with newest master + `iaf_neuron`. It all seems fine too me! 

There are a few examples I am not able to run, this is mostly `music` examples and has to do with my `music` setup and not because we have changed something for 2.16. I am also not able to run `examples/nest/structural_plasticitly_benchmark.sli`, but I don't think we were able to run this example with 2.14 code either, because the error I get is `EnableStructuralPlasticity [Error]: Structural plasticity can not be used with multiple threads`, and we were not able to use structural placticity with multiple threads in 2.14 either. In 2.16 we don't use threads in the example, and when doing the same with the 2.14 example, I get it to run.

I have not compared the output of the 2.14 examples with the examples from the current master, as none of the 2.14 examples use the `iaf_neuron`. I don't think there should be any differences seeing as they all run and the kernel from the current master is used, but I can compare if you think that is best.

**Comment by heplesser** [comment]
@stinebuu That's good news!

- Concerning the structural plasticity example, we added protection against doing unstable things (running with multiple threads). Could you check that the 2.14 example runs if you change the number of threads to 1?
- Could you run some examples, e.g., some brunel examples with SLI code from 2.14 on NEST built with 2.14 and with the current pre-2.16 to ensure that they produce identical results?

**Comment by heplesser** [comment]
@stinebuu Excellent, so we are ready to go!
