### ISSUE TITLE
Avoid using types to distinguish secondary events

### ISSUE THREAD

**Issue by jakobj** [nest/nest-simulator#954]
@janhahne you have introduced an additional template argument here https://github.com/nest/nest-simulator/blob/master/nestkernel/event.h#L958 to distinguish several secondary events that might carry payload of the same type. did @suku248 and me reconstruct that correctly? in the following (https://github.com/nest/nest-simulator/blob/master/nestkernel/event.h#L1090 ff) you use different types to distinguish the events, which is quite confusing when first encountered, despite the comment. would it be possible to just number them? i.e.,  pass integers as template arguments instead of typenames? what if we run out of types?

**Comment by janhahne** [comment]
@jakobj @suku248 Yes you reconstructed this correctly. This was introduced with PR #856 in order to remove a lot of redundant code from `event.h` (also see the explanation in the PR description). The main reason for the second template argument are the static variables of the base class: Without the second argument all secondary events of the same template data type share the same static variables. This is no longer the case if there is a distinguishing second template argument. So any other second template argument that does the job is fine with me. (The current solution is only the first that came to my mind.)

I am sorry for the rather poor documentation on this!

**Comment by heplesser** [comment]
@jakobj @janhahne @suku248 By the magic of C++, you can actually use the derived class as the second template argument to distinguish the static elements, as in the following example:
```c++
template <typename Data, typename Subclass>
class Base
{
public:
  Base() {}
  void set_static( const std::string& t ) { static_value_ = t; }
  void print() { std::cout << static_value_ << std::endl; }

private:
  static std::string static_value_;
};

template <typename Data, typename Subclass>
std::string Base<Data, Subclass>::static_value_;

class A : public Base< int, A >
{
public:
  A() {}
};

class B : public Base< int, B >
{
public:
  B() {}
};

int main()
{
  A a;
  B b;
  
  a.set_static("Class A");
  b.set_static("Class B");

  a.print();
  b.print();

  return 0;
}
```

I would also suggest to replace `D` and `E` with more informative names for the template arguments.

**Comment by jakobj** [comment]
thanks for the replies @janhahne @heplesser ! sounds good. @janhahne would you please create a PR in which the second argument are replaced with the name of the subclass and maybe update the documentation?
