### ISSUE TITLE
ConnectionCreator::target_driven_connect_ does not handle exceptions correctly

### ISSUE THREAD

**Issue by heplesser** [nest/nest-simulator#977]
`ConnectionCreator::target_driven_connect_()` does not catch exceptions inside the thread-parallel context and re-throw the outside. This may lead to a crash if an exception is thrown while connections are created.

**Comment by stinebuu** [comment]
@heplesser As a side note, this is implemented in [the SubnetFreeTopology branch](https://github.com/compneuronmbu/nest-simulator/blob/fix-481-SubnetFreeTopology/topology/connection_creator_impl.h#263), so if this issue is not fixed by the time the subnetFree branch is merged into master, it will be fixed then.

**Comment by terhorstd** [comment]
this is fixed in NEST-3 branch.
