### ISSUE TITLE
Build of NEST statically fails 

### ISSUE THREAD

**Issue by ikitayama** [nest/nest-simulator#994]
```
cmake -DCMAKE_INSTALL_PREFIX:PATH=/home/itaru/opt/nest-20180803-static-gcc -Dwith-mpi=OFF -Dwith-openmp=ON -Dwith-python=OFF -Dwith-warning=OFF -Dwith-readline=OFF -Dstatic-libraries=ON /home/itaru/projects/nest-simulator
```
gives a dynamically linked nest, as shown below:
```
$ file nest/nest
nest/nest: ELF 64-bit LSB executable, ARM aarch64, version 1 (GNU/Linux), dynamically linked (uses shared libs), for GNU/Linux 3.7.0, BuildID[sha1]=524e52661359152f27f0515e2042ce0b5cce9091, not stripped
```

**Comment by ikitayama** [comment]
With Arm Clang, the build fails in the middle of it:

```
[ 32%] Built target sli_readline
Scanning dependencies of target sli
[ 33%] Building CXX object sli/CMakeFiles/sli.dir/puresli.cc.o
[ 33%] Linking CXX executable sli
/home/itaru/opt/binutils-20180727/bin/ld: cannot find -lgcc_s
/home/itaru/opt/binutils-20180727/bin/ld: cannot find -lgcc_s
/home/itaru/opt/binutils-20180727/bin/ld: /usr/lib/gcc/aarch64-redhat-linux/4.8.5/../../../../lib64/libpthread.a(libpthread.o): in function `sem_open':
(.text+0x7810): warning: the use of `mktemp' is dangerous, better use `mkstemp'
clang-5.0: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [sli/CMakeFiles/sli.dir/build.make:88: sli/sli] Error 1
make[1]: *** [CMakeFiles/Makefile2:628: sli/CMakeFiles/sli.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 33%] Linking CXX static library librandom.a
[ 33%] Built target random
make: *** [Makefile:163: all] Error 2
```

I'm building the latest master branch, with the CMake command below:
```
cmake -DCMAKE_CXX_COMPILER=armclang++ -DCMAKE_CXX_FLAGS="-Ofast -march=armv8-a+sve -static" -DCMAKE_INSTALL_PREFIX:PATH=/home/itaru/opt/nest-static-armclang -Dwith-mpi=OFF -Dwith-openmp=ON -Dwith-python=OFF -Dwith-gsl=ON -Dwith-warning=OFF -Dwith-readline=OFF -Dstatic-libraries=ON /home/itaru/projects/nest-simulator
```

**Comment by tammoippen** [comment]
Can you run `ldd path/to/nest` to see what is actually liked to nest. Sometimes `libc` or similar is not available as static lib, then the executable cannot be build static. If you have a look into `install-dir/lib/`, there should be all libraries from nest. If they have the `.a` suffix, the static build was as successful as it can be...

As with the compile error: it cannot find `-lgcc_s`... maybe clang is looking for a static version of it (due to the extra `--static` flag) and cannot find it? You could run `make VERBOSE=1` for building to see the actual build and link commands...

**Comment by tammoippen** [comment]
This looks quite good for the `-Dstatic-libraries=ON` part: `librandom.a` etc. is build correctly. Linking `randomtest` with the `--static` flag makes the linker look for static versions of `libgcc_s` (see the `-lgcc_s` parts), which it doesn't find. You can either

* install static versions of the system libraries
* compile without `--static`

**Comment by ikitayama** [comment]
@tammoippen building it without -static ended up producing a dynamically linked binary.

```
$ ldd nest/nest
	linux-vdso.so.1 =>  (0x000003ffae0d0000)
	libreadline.so.6 => /lib64/libreadline.so.6 (0x000003ffae040000)
	libncurses.so.5 => /lib64/libncurses.so.5 (0x000003ffadff0000)
	libtinfo.so.5 => /lib64/libtinfo.so.5 (0x000003ffadfa0000)
	libgcc_s.so.1 => /home/itaru/opt/gcc-20180726/lib64/libgcc_s.so.1 (0x000003ffadf60000)
	libstdc++.so.6 => /home/itaru/opt/gcc-20180726/lib64/libstdc++.so.6 (0x000003ffaddc0000)
	libm.so.6 => /lib64/libm.so.6 (0x000003ffadd00000)
	libomp.so => not found
	libpthread.so.0 => /lib64/libpthread.so.0 (0x000003ffadcc0000)
	libc.so.6 => /lib64/libc.so.6 (0x000003ffadb30000)
	/lib/ld-linux-aarch64.so.1 (0x000003ffae0e0000)
	libdl.so.2 => /lib64/libdl.so.2 (0x000003ffadb00000)
```

So -Dstatic-libraries=ON has no effect?

**Comment by tammoippen** [comment]
By the way: you should also add `-Dwith-ltdl=OFF` (responsible for (dynamically) loading user modules). As far as I suspect, this will not be possible with a static exe.

**Comment by ikitayama** [comment]
With Ubuntu GCC8, b6938b91 builds statically fine without making changes at all to CMake files.
It seems bringing libgcc_s.a to the system isn't the answer.

**Comment by ikitayama** [comment]
If I set to with-python to OFF, the libgcc_s is required at link time, but on most systems there's no
static version, so I'm having a problem. I use SLI as an interface to NEST, but for this case, should I
set it to the default (ON) value?

**Comment by ikitayama** [comment]
Arm Clang builds NEST fine the statically linked executables without making changes to the CMake files.

**Comment by ikitayama** [comment]
So has anyone succeeded in building NEST statically with GCC in the past.

**Comment by ikitayama** [comment]
@heplesser I confirm that as well on my macOS Sierra with GCC 8 from Homebrew.
However, doing the same on ThunderX (aarch64) with GCC 9 produces a dynamically
linked executable. If I supply the -static to the driver, the build complains that there's no static
version of libgc_s.

**Comment by ikitayama** [comment]
My userland packages are from CentOS 7.

**Comment by gtrensch** [comment]
I have made some attempts with an Ubuntu 16.04 and gcc-5.4.0 to build a static Nest module from the current master. It finally failed due to a missing libgcc_s.a. There seems to be no 64bit version!

As already mentioned by @tammoippen, the linker flags we use in Nest create a dynamically linked ELF file (`-Wl, -Bdynamic`) if no static version of the required library is available. `-Wl,-Bstatic,-lgcc_s` will force the linker to include the static version of libgcc. This recreates the issue on my system: `statically linked applications requires at runtime the shared libraries from the glibc version used for linking /usr/bin/ld: cannot find -lgcc_s`

Besides that I found, linking `-lreadline` additionally requires `-ltermcap` for static linking.

Question: Is there a special reason for the static linking?

**Comment by ikitayama** [comment]
@gtrensch yes. Our HW simulator requires applications be linked statically.

**Comment by gtrensch** [comment]
@ikitayama I have continued my attempts because I could not believe that static linking should not be possible. I used a simple c-main program for testing. Finally, I managed to build a static version of the Nest kernel from the current master.

If compiler option `--static` is set, externs refer to the static version of `glibc` and not `libgcc_s`.
```
>> gcc -c main.c -o main --static
>> file main
main: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), statically linked, ...
```
`readelf main -a` dislpays how externs are resolved.
This simple test also works on my Ubuntu with clang++-3.5!

For NEST this means all modules need to be compiled with `--static` (`-DCMAKE_CXX_FLAGS="--static"`). 

Linkage is a bit more complicated. It matters where options are placed. Thus, setting CMAKE_LD_FLAGS does not work. I ran `make` with option `VERBOSE=1` and manually solved the linker issues occurring. To get glibc statically linked you have to remove `-Wl,-Bdynamic` and append `-ltermcap`.

For the Nest kernel it then looks like the following:
`/usr/bin/c++   --static -std=c++11 -O2 -Wall -fopenmp -fdiagnostics-color=auto  -Wl,--no-as-needed CMakeFiles/nest.dir/main.cpp.o CMakeFiles/nest.dir/neststartup.cpp.o CMakeFiles/nest.dir/sli_neuron.cpp.o  -o nest -rdynamic ../libnestutil/libnestutil.a ../nestkernel/libnestkernel.a ../librandom/librandom.a ../sli/libsli.a ../sli/libsli_readline.a ../models/libmodels.a ../precise/libprecise.a ../topology/libtopology.a -Wl,-Bstatic -lreadline -lncurses ../nestkernel/libnestkernel.a ../librandom/librandom.a ../sli/libsli.a ../libnestutil/libnestutil.a -lgsl -lgslcblas -ltermcap`

```
>> file nest
nest: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), statically linked, ...
```

I did not build nest using `clang` but I suppose that will work the same way.

**Comment by ikitayama** [comment]
@gtrensch On our ThunderX system, there isn't a static version of readline package available, so I re-ran CMake with  `-Dwith-readline=OFF,` the build gets crashed at the last step saying no -lreadline etc., so I edited my `nest/CMakeFiles/nest.dir/link.txt`  to look like below:

```
/home/itaru/opt/gcc-20180726/bin/c++  -static -std=c++11 -O2 -Wall -fopenmp -fdiagnostics-color=auto  -rdynamic -Wl,--no-as-needed CMakeFiles/nest.dir/main.cpp.o
CMakeFiles/nest.dir/neststartup.cpp.o CMakeFiles/nest.dir/sli_neuron.cpp.o  -o nest
 ../libnestutil/libnestutil.a ../nestkernel/libnestkernel.a ../librandom/librandom.a ../sli/libsli.a
 ../sli/libsli_readline.a ../models/libmodels.a ../precise/libprecise.a ../topology/libtopology.a
 ../nestkernel/libnestkernel.a ../librandom/librandom.a ../sli/libsli.a ../libnestutil/libnestutil.a
```
The above gives me the statically linked NEST binary. I used GCC 9.0.0 which I built natively myself.

**Comment by ikitayama** [comment]
@gtrensch I didn't test either the upstream Clang, only Arm Clang, but I agree it should work as well.

**Comment by ikitayama** [comment]
@heplesser if you're happy, please go ahead and close this Issue.

**Comment by heplesser** [comment]
Thanks for working this out! @ikitayama Could you create a follow-up issue about the `-lreadline` which should not appear when NEST is linked when built with `-Dwith-readline=OFF`. I assume there is some error in a CMake file somewhere.

**Comment by ikitayama** [comment]
@heplesser Will do.
